
<div class="login-box">

    <div class="login-logo">
        <div class="image">
            <img src="<?=API_URL_LOGO."".$_SESSION['LOGO_SISTEMA']??''?>" alt="<?=$this->configuracao->dataEmpresa->nome_sistema??'Sem conexão / olá serviços'?>" class="brand-image img-circle " width="100" style="opacity: .8">
        </div>
        <a href="/" class="text-white"><b> <?=$this->configuracao->dataEmpresa->nome_sistema??''?></b></a>
    </div>
    <!-- /.login-logo -->
    <div class="card">
        <div class="card-body login-card-body">
            <p class="login-box-msg">Activar sua Conta</p>
            <div id="messagem"></div>

            <form method="post" id="quickFormLogin" onsubmit="return false">
                <div class="input-group mb-3 form-group">
                    <input type="number" name="phone" id="phone" class="form-control" placeholder="Telefone">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-envelope"></span>
                        </div>
                    </div>
                    <div class="input-group mb-2 form-group" id="erroemail">
                    </div>
                </div>

                <input type="hidden" name="token" id="token" class="form-control" value="<?= $this->authCsrf ?>">
                <div class="row">
                    <!-- /.col -->
                    <div class="col-4">
                        <button type="submit" class="btn btn-primary btn-block" id="login">Confirmar</button>
                    </div>
                    <!-- /.col -->
                </div>
            </form>

            <div class="social-auth-links text-center mb-3">
                <!--         <a href="#" class="btn btn-block btn-primary">
          <i class="fab fa-facebook mr-2"></i> Entrar com Facebook
        </a>
        <a href="#" class="btn btn-block btn-danger">
          <i class="fab fa-google-plus mr-2"></i> Entrar com Google
        </a> -->
            </div>
            <!-- /.social-auth-links -->

            <p class="mb-1">
                <a href="/forgot_password">Recuperar minha senha</a>
            </p>
            <p class="mb-0">
                <a href="/register" class="text-center">Criar conta</a>
            </p>
        </div>
        <!-- /.login-card-body -->
    </div>
</div>
