<!DOCTYPE html>

<html lang="en">



<head>

    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title> <?=$this->configuracao->dataEmpresa->nome_sistema??''?> | Confirmação</title>



    <!-- Google Font: Source Sans Pro -->

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">

    <!-- Font Awesome -->

    <link rel="stylesheet" href="../../plugins/fontawesome-free/css/all.min.css">

    <!-- icheck bootstrap -->

    <link rel="stylesheet" href="../../plugins/icheck-bootstrap/icheck-bootstrap.min.css">

    <!-- Theme style -->

    <link rel="stylesheet" href="../../dist/css/adminlte.min.css">

</head>



<body class="hold-transition login-page">

    <div class="login-box">

        <div class="card card-outline card-primary">

            <div class="card-header text-center">

                <a href="/l" class="h1"><b><?=$this->configuracao->dataEmpresa->nome_sistema??''?></b></a>

            </div>

            <div class="card-body">

                <p class="login-box-msg">Confirmação do Código, verifica sua caixa de e-mail</p>

                <form  method="post" accept="image/*" id="quickFormforgConfirm" class="mf_form_validate_forgEmail ajax_submit_forgot"  onsubmit="return false" enctype="multipart/form-data">



                <div class="input-group mb-3 form-group">

                    <input type="text" name="my_code" id="my_code" class="form-control" placeholder="Código enviado">

                    <input type="hidden" name="token" id="token" class="form-control" value="<?= $this->authCsrf ?>">

                    <div class="input-group-append">

                        <div class="input-group-text">

                            <span class="fas fa-envelope"></span>

                        </div>

                    </div>

                    <div class="input-group mb-2 form-group" id="errocodigo">

                    </div>



                </div>



                    <div class="row">

                        <div class="col-12">

                            <button type="submit" id="register" class="btn btn-primary btn-block">Confirmao código</button>

                        </div>

                        <!-- /.col -->

                    </div>

                </form>

                <p class="mt-3 mb-1">

                    <a href="/login">Login</a>

                </p>

            </div>

            <!-- /.login-card-body -->

        </div>

    </div>

    <!-- /.login-box -->



    <!-- jQuery -->

    <script src="../../plugins/jquery/jquery.min.js"></script>

    <!-- Bootstrap 4 -->

    <script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- AdminLTE App -->

    <script src="../../dist/js/adminlte.min.js"></script>

</body>



</html>

