<section data-bs-version="5.1" class="features1 cid-sUSFyo3iNC" id="features1-2s">
    <div class="container">
        <div class="row">

        </div>
        <div class="row">
            <div class="card col-12 col-md-6 col-lg-3">
                <div class="card-wrapper">
                    <div class="card-box align-center">
                        <div class="iconfont-wrapper">
                            <span class="mbr-iconfont mbrib-left-right" style="color: #B3B9BA; fill: #B3B9BA;"></span>
                        </div>
                        <h5 class="card-title mbr-fonts-style display-7"><strong>Sobre nós:</strong></h5>
                        <p class="card-text mbr-fonts-style display-7"><?= $this->configuracao['sobre_omnigrjas'] ?></p>
                    </div>
                </div>
            </div>
            <div class="card col-12 col-md-6 col-lg-3">
                <div class="card-wrapper">
                    <div class="card-box align-center">
                        <div class="iconfont-wrapper">
                            <span class="mbr-iconfont mbrib-left-right" style="color: #B3B9BA; fill: #B3B9BA;"></span>
                        </div>
                        <h5 class="card-title mbr-fonts-style display-7"><strong>Objecto social:</strong></h5>
                        <p class="card-text mbr-fonts-style display-7"><?= $this->configuracao['obejectivo_social'] ?></p>
                    </div>
                </div>
            </div>

            <div class="card col-12 col-md-6 col-lg-3">
                <div class="card-wrapper">
                    <div class="card-box align-center">
                        <div class="iconfont-wrapper">
                            <span class="mbr-iconfont mbrib-left-right" style="color: #B3B9BA; fill: #B3B9BA;"></span>
                        </div>
                        <h5 class="card-title mbr-fonts-style display-7"><strong>Nossa visão:&nbsp;</strong></h5>
                        <p class="card-text mbr-fonts-style display-7"><?= $this->configuracao['nossa_visao'] ?></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
