<div class="login-box">

    <div class="login-logo">
        <div class="image">
            <img src="<?= API_URL_LOGO . "" . $_SESSION['LOGO_SISTEMA'] ?? '' ?>" alt="<?= $this->configuracao->dataEmpresa->nome_sistema ?? 'Sem conexão / olá serviços' ?>" class="brand-image img-circle " width="100" style="opacity: .8">
        </div>
        <a href="/" class="text-white"><b> <?= $this->configuracao->dataEmpresa->nome_sistema ?? '' ?></b></a>
    </div>
    <!-- /.login-logo -->
    <div class="card">
        <div class="card-body login-card-body">
        <div class="lockscreen-name text-center font-weight-600 ">
                <h5>
                    <?= $_COOKIE['telefone_cook'] ?? '' ?>
                </h5>

            </div>
            <p class="login-box-msg">Activar sua Conta</p>
            <!-- User name -->

            <div id="messagem"></div>

            <form method="post" id="quickFormLogin" onsubmit="return false" class="align-items-center">
                <div class=" mb-3 form-group col-12 ">
                    <input type="text" name="codigo" maxlength="6" id="codigo" class="form-control" placeholder="XXXXXX">

                </div>
                <div class="input-group mb-2 form-group" id="errocodigo">

                </div>

                <input type="hidden" name="token" id="token" class="form-control" value="<?= $this->authCsrf ?>">
                <div class="row">
                    <!-- /.col -->
                    <div class="col-4">
                        <button type="submit" class="btn btn-primary btn-block" id="login">Confirmar</button>
                    </div>
                    <!-- /.col -->
                </div>
            </form>
            <small class="text-success">Verifica a sua caixa de Mensagem</small>


            <div class="social-auth-links text-center mb-3">
                <!--         <a href="#" class="btn btn-block btn-primary">
          <i class="fab fa-facebook mr-2"></i> Entrar com Facebook
        </a>
        <a href="#" class="btn btn-block btn-danger">
          <i class="fab fa-google-plus mr-2"></i> Entrar com Google
        </a> -->
            </div>
            <!-- /.social-auth-links -->

            <p class="mb-1">
                <a href="/forgot_password">termos e condições</a>
            </p>
            <p class="mb-0">
                <a href="/logout" class="text-center">terminar</a>
            </p>
        </div>
        <!-- /.login-card-body -->
    </div>
</div>
