  <!-- Content Wrapper. Contains page content -->

  <!-- Main content -->
  <section class="content">
      <!-- Default box -->
      <div class="card card-solid">
          <div class="card-body pb-0">
              <div class="row">
                  <?php foreach ($this->clienteData->data->data ?? [] as  $value) { ?>
                      <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch flex-column ">
                          <div class="card bg-light d-flex flex-fill">
                              <div class="card-header text-muted border-bottom-0">
                                  POCOTE
                              </div>
                              <div class="card-body pt-0">
                                  <div class="row">
                                      <div class="col-7">
                                          <h2 class="lead"><b><?= $value->nomepacote ?? '' ?></b></h2>
                                          <p class="text-muted text-sm"><b>IDEAL: </b><?= $value->text_ideal ?? '' ?></p>
                                          <ul class="ml-4 mb-0 fa-ul text-muted">
                                              <li class="small"><span class="fa-li"><i class="fas fa-envelope"></i></span>1SMS/<?= $value->qtduser . "Kz" ?></li>
                                              <li class="small"><span class="fa-li"><i class="fas fa-lg fa-building"></i></span>TOTAL: <?= $value->qtd_sms_user . "SMS" ?></li>
                                              <li class="small"><span class="fa-li"><i class="fas fa-money-bill"></i></span><?= $value->qtd_sms_user * $value->qtduser . "KZ" ?> </li>
                                          </ul>
                                      </div>
                                      <div class="col-5 text-center">
                                          <img src="<?= API_URL_LOGO . "" . $_SESSION['LOGO_SISTEMA'] ?? '' ?>" alt="COMERCIAL" class="img-circle img-fluid">
                                      </div>
                                  </div>
                              </div>
                              <div class="card-footer">
                                  <div class="text-right">

                                      <a href="#" class="btn btn-sm btn-primary animate__animated animate__slideInLeft" id="btnactive<?= $value->id ?>" onclick="comprapacote('<?= $value->id ?>')">
                                          <i class="fas fa-money-bill"></i> COMPRAR SMS
                                      </a>
                                  </div>
                              </div>
                          </div>
                      </div>
                      <input type="hidden" name="token" id="token" class="form-control" value="<?= $this->authCsrf ?>">
                  <?php } ?>
              </div>
          </div>

      </div>
      <!-- /.card -->
