<div class="wrapper">

    <!-- Navbar -->
    <!-- inicio menu top -->
    <?php include_once("menu_center.phtml"); ?>
    <!-- /.navbar -->
    <?php include_once("menu_lateral.phtml"); ?>
    <div class="content-wrapper">
        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <!-- Small boxes (Stat box) -->
                <div class="row">
                    <section class="col-lg-12 connectedSortable">
                        <!-- Main content -->
                        <section class="content">
                            <div class="row">
                                <section class="col-lg-12 connectedSortable">
                                    <!-- ///////////////////////////////////////////////////////////////////////////////////////// -->
                                    <table id="example1" class="table table-bordered table-striped example1_lede example_conf">
                                        <thead>
                                            <tr id="tr_change">
                                                <th>Tema da evento</th>
                                                <th>Para Igreja</th>
                                                <th>Dia da semana</th>
                                                <th>Hora de inicio</th>
                                                <th>Hora de termino</th>
                                                <th>Data da realização</th>
                                            </tr>

                                        </thead>
                                        <tbody id="corpo_institucional">

                                            <!-- for $this->category -->
                                            <?php foreach ($this->eventos ?? [] as $value) { ?>
                                                <tr>
                                                    <td><?= $value['tema_evento'] ?? '' ?></td>
                                                    <td> <?= $value['dia_da_semana'] ?? '' ?></td>
                                                    <td> <?= $value['nome_igrejas'] ?? '' ?></td>
                                                    <td><?= $value['hora_de_inicio'] ?? '' ?></td>
                                                    <td><?= $value['hora_de_termino'] ?? '' ?></td>
                                                    <td><?php
                                                        $data = new \DateTime($value['dia_da_semana_data'] ?? '');
                                                        $date_create = $data->format('d-M-Y g:i A');
                                                        echo $date_create; ?>
                                                    </td>

                                                </tr>
                                            <?php } ?>
                                            <!-- end for -->
                                        </tbody>
                                        <tfoot>
                                            <tr id="tr_change">
                                            <tr id="tr_change">
                                                <th>Tema da evento</th>
                                                <th>Para Igreja</th>
                                                <th>Dia da semana</th>
                                                <th>Hora de inicio</th>
                                                <th>Hora de termino</th>
                                                <th>Data da realização</th>

                                            </tr>
                                        </tfoot>
                                    </table>
                                    <!-- ///////////////////////////////////////////////////////////////////////////////////////// -->
                                </section>
                            </div>
                        </section>
                    </section>
                </div>
            </div>
        </section>
    </div>

    <footer class="main-footer">
        © zumu_sms.
        <a href="https://zumu_sms.com">zumu_sms</a>.- Desenvolvido pela <a href="https://qlerius.com" class="text-dark">Qlerius</a> </strong>
        <div class="float-right d-none d-sm-inline-block">
            <b>Version</b> 3.2.0
        </div>
    </footer>

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->

    </aside>
    <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->
