<!-- inicio menu top -->
<?php include_once("menu_center.phtml"); ?>
<!-- /.navbar -->
<?php include_once("menu_lateral.phtml"); ?>
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">ENVIAR SMS</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="">ENVIAR SMS</a></li>
                        <li class="breadcrumb-item active">CARREGAR CONTA</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->

            <div class="row animate__animated animate__heartBeat">
                <?php include_once("cardsSendSms.phtml"); ?>
            </div>
            <!-- /.card-body -->

            <div class="align-content-lg-between animate__animated animate__bounceIn">
                <div class="card-footer ">
                    <a class="btn btn-app bg-success componente" data-toggle="modal" data-target="#modal-default">
                        <i class="fas fa-plus"></i> NOVO
                    </a>
                </div>
            </div>

        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">

            <div class="row">
                <div class="col-12 ">
                    <div class="card  card-primary card-outline">

                        <div class="card-header">

                            <h3 class="card-title">

                                <i class="far fa-chart-bar"></i>
                                Mensagens
                            </h3>
                            <button type="button" class="btn btn-tool" data-card-widget="collapse">

                                <i class="fas fa-minus"></i>

                            </button>

                            <div class="card-tools">



                                <div class="col-12 col-sm-12 col-md-12">
                                    <div class="input-group form-group">

                                        <input type="text" name="pesquisar" id="pesquisar" value="<?= $_SESSION['pesquisar'] ?? '' ?>" onchange="getOperation()" class="form-control" placeholder="Mensagem">
                                        <div class="input-group-append">
                                            <div class="input-group-text">
                                                <a class="cursor-pointer" type="button" id="buscar" onclick="getOperation()">
                                                    <span class="fas fa-search"></span>
                                                </a>

                                            </div>
                                        </div>

                                    </div>
                                </div>

                            </div>

                        </div>

                        <!-- /.card-header -->
                        <div class="card-body">
                            <div id='Operation'>
                                <div class="d-flex justify-content-center">
                                    <div class="spinner-border text-primary" style="width: 50px; height: 50px;" role="status">
                                        <span class="visually-hidden"></span>
                                    </div>
                                </div>
                            </div>
                            <!--  {{ $dados['data']->links('vendor.pagination.bootstrap-5') }}-->
                        </div>
                    </div>
                </div>
                <!-- /.col -->
            </div>

            <!-- //////////////////////////////////////////// -->

            <div class="modal fade" id="modal-default">

                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content ">
                        <div class="overlay  d-none" id="ispinnermodalsend">
                            <i class="fas fa-2x fa-sync fa-spin"></i>
                        </div>
                        <div class="modal-header">
                            <h4 class="modal-title">ENVIAR MENSAGEM</h4>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="row">
                                <!-- left column -->
                                <div class="col-md-12 animate__animated animate__bounceIn">
                                    <!-- jquery validation -->
                                    <div class="card card-primary">

                                        <form method="post" name="from_membro" class="mf_form_validate_send ajax_submit_send" action="/sendOperationSms" enctype="multipart/form-data">
                                            <div class="card-body">
                                                <div class="row">
                                                    <div class="col-md-12">
                                                        <div class="form-group">
                                                            <label>APLICAÇÃO DE ENVIO </label>
                                                            <select class="form-control p-2 select2" style="width: 100%;" name="id_sender" id="id_sender">
                                                                <option selected="selected" value="">SELECIONAR</option>
                                                                <?php foreach ($this->data_senderActive->data??[] as $value) { ?>
                                                                    <option  value="<?=$value->id??''?>"><?=$value->name_sender_id??''?></option>
                                                                <?php } ?>

                                                            </select>
                                                            <div class="input-group mb-2 form-group" id="erroid_sender">
                                                            </div>
                                                        </div>
                                                    </div>

                                                    <div class="col-md-12">
                                                        <div class="form-group">
                                                            <label>ENVIO EM MASSA: ( .xslx ) <a href=" <?= API_URL ?>contacts_exemplar/<?= $_SESSION['NOME_EMAIL'] ?? '' ?>" target="_blank">Exemplar</a></label>
                                                            <input type="file" name="file" id="file" class="form-control" placeholder="">
                                                            <div class="input-group mb-2 form-group" id="erroarquivo_de_sms_pacote">
                                                            </div>
                                                        </div>
                                                    </div>

                                                    <div class="col-md-12">
                                                        <div class="form-group">
                                                            <label>DESTINATARIO</label>
                                                            <input type="text" name="number_phone" id="number_phone" class="form-control" placeholder="ex: 9xxxxxxxx, 9xxxxxxxx, 9xxxxxxxx">
                                                            <div class="input-group mb-2 form-group" id="erronumber_phone">
                                                            </div>
                                                        </div>
                                                    </div>

                                                    <div class="col-md-12">
                                                        <div class="form-group">
                                                            <label>CORPO DA MENSAGEM 1SMS/70 Caractres </label>
                                                            <textarea type="text" name="message_body" id="message_body" rows="5" class="form-control" placeholder="CORPO DA MENSAGEM"  onkeyup="contactar_char_1(this.value)"></textarea>
                                                            <div class="input-group mb-2 form-group" id="erromessage_body">
                                                            </div>
                                                        </div>
                                                        <div class="display-6 fs-1"><span id="number_caractres" class=" text-primary">Número de caracteres: 0</span> </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <input type="hidden" name="token" id="token" class="form-control" value="<?= $this->authCsrf ?>">
                                            <div class="modal-footer justify-content-between">
                                                <button type="submit" class="btn btn-primary btn-block" id="register">ENVIAR SMS</button>
                                            </div>
                                        </form>
                                    </div>
                                    <!-- /.card -->
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer justify-content-between">

                            <button type="button" class="btn btn-danger" data-dismiss="modal">CANCELAR</button>

                        </div>
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>

        </div>
    </section>
    <!-- /////////////////////////////////////////////////////////////////////////////////// -->
</div>

<?php include_once("footer_info.phtml"); ?>

<script>
    if (!!(window.addEventListener)) window.addEventListener('DOMContentLoaded', main);
    else window.attachEvent('onload', main);

    function main() {
        if (localStorage.getItem("theme") == 1) {
            $('body').addClass('dark-mode')
        }
        getOperation();

        //
    }
</script>

<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->

</aside>
<!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->
