<div class="wrapper">

    <!-- Navbar -->
    <!-- inicio menu top -->
    <?php include_once("menu_center.phtml"); ?>
    <!-- /.navbar -->
    <?php include_once("menu_lateral.phtml"); ?>
    <div class="content-wrapper">
        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <!-- Small boxes (Stat box) -->
                <div class="row">
                    <section class="col-lg-12 connectedSortable">
                        <!-- Main content -->
                        <section class="content">
                            <div class="row">
                                <section class="col-lg-12 connectedSortable">
                                    <!-- ///////////////////////////////////////////////////////////////////////////////////////// -->
                                    
                                    <!-- ///////////////////////////////////////////////////////////////////////////////////////// -->
                                </section>
                            </div>
                        </section>
                    </section>
                </div>
            </div>
        </section>
    </div>

    <footer class="main-footer">
        © zumu_sms.
        <a href="https://zumu_sms.com">zumu_sms</a>.- Desenvolvido pela <a href="https://qlerius.com" class="text-dark">Qlerius</a> </strong>
        <div class="float-right d-none d-sm-inline-block">
            <b>Version</b> 3.2.0
        </div>
    </footer>

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->

    </aside>
    <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->
