<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="d-flex justify-content-center">
          <img src="<?=$this->urlcaminho?>assets1/img/certo.gif" width="89"/>
        </div>

        <div class="row">
          <div class="col">
            <h2>Seja bem-vindo a <?=$this->presentacao['empresa'] ?? ''?> <?=$this->presentacao['marca'] ?? ''?></h2>
            
            <h4>Cadastro realizado com sucesso</h4>
            <h6>Informe a Senha Enviada em <span class=" text-success"> <?=$this->numero?>  </span></h6>

          </div>
        </div>
        <div class="row">
          <div class="col">
            <a href="/login" class="btn btn-primary btn-block">Clique aqui para fazer login!</a>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>



    
  