<?php
$count = 0;
foreach ($this->clienteData->data->data ?? [] as  $value) { ?>
    <?php if ($count == 0) { ?>


        <div class="col-lg-4 box" data-aos="zoom-in">
            <h3><?= $value->nomepacote ?? '' ?></h3>
            <h4>Kz<?= $value->qtd_sms_user * $value->qtduser . "KZ" ?><span></span></h4>
            <ul>
                <li><i class="bx bx-check"></i> Quam adipiscing vitae proin</li>
                <li><i class="bx bx-check"></i> Nec feugiat nisl pretium</li>
                <li><i class="bx bx-check"></i> Nulla at volutpat diam uteera</li>
                <li class="na"><i class="bx bx-x"></i> <span>Pharetra massa massa ultricies</span></li>
                <li class="na"><i class="bx bx-x"></i> <span>Massa ultricies mi quis hendrerit</span></li>
            </ul>
            <a href="#" class="get-started-btn">Login</a>
        </div>
        <?php
        if ($count == 2) { ?>

            <div class="col-lg-4 box featured" data-aos="zoom-in">
                <span class="featured-badge">Pacote</span>
                <h3>Business</h3>
                <h4>$29<span>per month</span></h4>
                <ul>
                    <li><i class="bx bx-check"></i> Quam adipiscing vitae proin</li>
                    <li><i class="bx bx-check"></i> Nec feugiat nisl pretium</li>
                    <li><i class="bx bx-check"></i> Nulla at volutpat diam uteera</li>
                    <li><i class="bx bx-check"></i> Pharetra massa massa ultricies</li>
                    <li><i class="bx bx-check"></i> Massa ultricies mi quis hendrerit</li>
                </ul>
                <a href="#" class="get-started-btn">Login</a>
            </div>

    <?php        }
    } ?>

<?php } ?>