<!DOCTYPE html>
<html lang="en" dir="ltr">


<!-- Mirrored from slidesigma.com/themes/html/martalaa/contact-us.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 08 Jun 2022 16:31:25 GMT -->

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>zumu_sms | Contactos</title>

    <!-- Favicon -->
    <link rel="icon" type="image/png" sizes="32x32" href="favicon.ico">

    <!-- partial:partial/__stylesheets.html -->
    <?php include_once("headercss.phtml"); ?>
    <script src="../../../../www.google.com/recaptcha/apifae7.js?render=6LceXdwUAAAAAM624k2Zezhs-jnmdJE8hjmhRMBh"></script>
    <!-- partial -->

</head>

<body>


    <?php include_once("menu_center.phtml"); ?>
    <!-- partial -->


    <!-- partial:partia/__subheader.html -->
    <div class="sigma_subheader dark-mode dark-overlay-2" style="background-image: url(assets/img/subheader.jpg)">

        <div class="container">
            <div class="sigma_subheader-inner">
                <div class="sigma_subheader-text">
                    <h1>Contactos</h1>
                    <p class="blockquote light">A zumu_sms pauta pelo rigor, responsabilidade, proximidade, Excelência e
                        Inovação. A dinâmica contemporânea exige superar os nossos limites. Por isso,
                        todos os dias devemos ser novos que se renovam</p>
                </div>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a class="btn-link" href="/">INICIO</a></li>
                        <li class="breadcrumb-item active" aria-current="page">CONTACTOS</li>
                    </ol>
                </nav>
            </div>
        </div>

    </div>
    <!-- partial -->

    <!-- Map Start  -->
    <div class="sigma_map">
        <iframe src="https://www.google.com/maps/embed?pb=!1m23!1m12!1m3!1d63064.51080757677!2d13.162999534545849!3d-8.923031715857702!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!4m8!3e1!4m0!4m5!1s0x1a51f4c4079d17d3%3A0x6a8b4ed30d316b45!2sSamba%2C%20Luanda!3m2!1d-8.8930366!2d13.1912875!5e0!3m2!1sen!2sao!4v1654808902715!5m2!1sen!2sao" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>
    <!-- Map End -->

    <!-- Contact form Start -->
    <div class="section mt-negative pt-0">
        <div class="container">

            <form class="sigma_box box-lg m-0 mf_form_validate ajax_submit" action="/envioemail" method="post" enctype="multipart/form-data">
                <div class="row">
                    <div class="col-lg-4">
                        <div class="form-group">
                            <i class="far fa-user"></i>
                            <input type="text" placeholder="Seu nome completo" class="form-control dark" name="name">
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="form-group bg-blue">
                            <i class="far fa-envelope "></i>
                            <input type="email" placeholder="Seu Endereço Email" class="form-control dark" name="email">
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="form-group">
                            <i class="far fa-pencil"></i>
                            <input type="text" placeholder="Assunto" class="form-control dark" name="Subesubject">
                        </div>
                    </div>
                    <input type="hidden" placeholder="token" class="form-control dark" value="<?= $this->authCsrf ?>" name="token">
                </div>
                <div class="form-group">
                    <textarea name="message" placeholder="Deixa a sua mensagen " cols="45" rows="5" class="form-control dark"></textarea>
                </div>
                <div class="text-center">
                    <button type="submit" class="sigma_btn-custom" id="button" name="button">Enviar</button>
                    <div class="server_response w-100">
                    </div>
                </div>
            </form>

        </div>
    </div>
    <!-- Contact form End -->

    <!-- Icons Start -->
    <div class="section section-padding pt-0">
        <div class="container">
            <div class="row">

                <div class="col-lg-4">
                    <div class="sigma_icon-block text-center light icon-block-7">
                        <i class="flaticon-email"></i>
                        <div class="sigma_icon-block-content">
                            <span>Enviar email <i class="far fa-arrow-right"></i> </span>
                            <h5> Email Address</h5>
                            <p>gestao@zumu_sms.com</p>
                            <p>admin@zumu_sms.com</p>


                        </div>
                        <div class="icon-wrapper">
                            <i class="flaticon-email"></i>
                        </div>
                    </div>
                </div>

                <div class="col-lg-4">
                    <div class="sigma_icon-block text-center light icon-block-7">
                        <i class="flaticon-telephone"></i>
                        <div class="sigma_icon-block-content">
                            <span>Ligue-nos agora <i class="far fa-arrow-right"></i> </span>
                            <h5> Telefone </h5>
                            <p> +244 998266618 </p>
                            <p> +244 998266619 </p>
                            <p> +244 930648704 </p>

                        </div>
                        <div class="icon-wrapper">
                            <i class="flaticon-telephone"></i>
                        </div>
                    </div>
                </div>

                <div class="col-lg-4">
                    <div class="sigma_icon-block text-center light icon-block-7">
                        <i class="flaticon-paper-plane"></i>
                        <div class="sigma_icon-block-content">
                            <span>Encontre-nos aqui<i class="far fa-arrow-right"></i> </span>
                            <h5> Localização </h5>
                            <p>Luanda, Município de Belas,,
                                Avenida 21 de Janeiro, Casa nº 31.
                            </p>
                            <p> Distrito Urbano da Samba, Bairro Morro Bento</p>
                        </div>
                        <div class="icon-wrapper">
                            <i class="flaticon-paper-plane"></i>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <!-- Icons End -->

    <!-- partial:partia/__footer.html -->
    <?php include_once("footer_zumu_sms.phtml"); ?>
    <!-- partial -->

    <!-- partial:partia/__scripts.html -->
    <script src="assets/js/plugins/jquery-3.4.1.min.js"></script>
    <script src="assets/js/plugins/popper.min.js"></script>
    <script src="assets/js/plugins/bootstrap.min.js"></script>
    <script src="assets/js/plugins/imagesloaded.min.js"></script>
    <script src="assets/js/plugins/jquery.magnific-popup.min.js"></script>
    <script src="assets/js/plugins/jquery.countdown.min.js"></script>
    <script src="assets/js/plugins/jquery.waypoints.min.js"></script>
    <script src="assets/js/plugins/jquery.counterup.min.js"></script>
    <script src="assets/js/plugins/jquery.zoom.min.js"></script>
    <script src="assets/js/plugins/jquery.inview.min.js"></script>
    <script src="assets/js/plugins/jquery.event.move.js"></script>
    <script src="assets/js/plugins/wow.min.js"></script>
    <script src="assets/js/plugins/isotope.pkgd.min.js"></script>
    <script src="assets/js/plugins/slick.min.js"></script>
    <script src="assets/js/plugins/ion.rangeSlider.min.js"></script>
    <script src="assets/js/plugins/jquery.validate.min.js"></script>
    <script src="dist/js/nesletter.js"></script>
    <script src="plugins/toastr/toastr.min.js"></script>
    <script src="assets/js/main.js"></script>
    <script src="assets/functions/mf_form.js"></script>
    <!-- partial -->

</body>


<!-- Mirrored from slidesigma.com/themes/html/martalaa/contact-us.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 08 Jun 2022 16:31:28 GMT -->

</html>
