<!-- partial:partia/__footer.html -->
<footer class="sigma_footer footer-2 sigma_footer-dark">

    <!-- Middle Footer -->
    <div class="sigma_footer-middle">
        <div class="container">
            <div class="row">
                <!-- Coupon Code Start -->
                <!--  <div class="row">
                    <div class="col-lg-4">
                        <div class="form-group mb-0">
                            <div class="input-group mb-0">
                                <input type="email" class="form-control" placeholder="Newletter" aria-label="Coupon Code" id="email_neslet">
                                <div class="input-group-append">
                                    <button class="sigma_btn-custom shadow-none" type="button" onclick="send_newletter()">Enviar</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div> -->
                <!-- Coupon Code End -->

            </div>
        </div>
    </div>


    <!-- Footer Bottom -->
    <div class="sigma_footer-bottom">
        <div class="container-fluid">
            <div class="sigma_footer-copyright">
                <p> © <?=$this->configuracao->dataEmpresa->nome_sistema??''?> </p>
            </div>
            <div class="sigma_footer-logo">
                <img src="<?=API_URL_LOGO."". $_SESSION['LOGO_SISTEMA']??''?>" alt="logo" width="80">
            </div>

            <ul class="sigma_sm square">
                <li>
                    <a href="https://facebook/zumu">
                        <i class="fab fa-facebook-f"></i>
                    </a>
                </li>
                <li>
                    <a href="https://linkedin/zumu">
                        <i class="fab fa-linkedin-in"></i>
                    </a>
                </li>
                <li>
                    <a href="https://twitter/zumu">
                        <i class="fab fa-twitter"></i>
                    </a>
                </li>
                <li>
                    <a href="https://youtube/zumu">
                        <i class="fab fa-youtube"></i>
                    </a>
                </li>
            </ul>
        </div>
    </div>

</footer>
<!-- partial -->
