<!DOCTYPE html>
<html lang="pt" dir="ltr">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $this->configuracao->dataEmpresa->nome_sistema ?? '' ?></title>
    <meta name="title" content="Sistema de envio de mensagem">
    <meta name="description" content="<?= $this->configuracao->dataEmpresa->nome_sistema ?? '' ?>">
    <!-- Favicon -->
    <link rel="icon" type="image/png" sizes="32x32" href="<?= API_URL_LOGO . "" . $_SESSION['LOGO_SISTEMA'] ?? '' ?>">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <?php include_once("headercss.phtml"); ?>
</head>
<style>
    body {
        background-color: #151F32 !important;
    }
</style>

<body>



    <?php include_once("menu_center.phtml"); ?>

    <!-- Banner Start -->
    <div class="sigma_banner banner-1 bg-cover light-overlay bg-center bg-norepeat " style="background-color: #151F32;">

        <div class="sigma_banner-slider">

            <!-- Banner Item Start -->
            <div class="sigma_banner-slider-inner">
                <div class="sigma_banner-text">
                    <div class="container position-relative">
                        <div class="row align-items-center">
                            <div class="col-lg-12">
                                <div class="sigma_box primary-bg banner-cta">
                                    <h1 class="text-white title">“<?= $this->configuracao->dataEmpresa->dica_sistema ?? '' ?>”</h1>
                                    <p class="blockquote light light-border mb-0"> <?= $this->configuracao->dataEmpresa->objectivo ?? '' ?></p>
                                    <div class="section-button d-flex float-right">
                                        <a href="/login" class="sigma_btn-custom secondary float-right">LOGIN <i class="far fa-arrow-right"></i> </a>
                                        <a href="/register" class="ms-3 sigma_btn-custom light text-white">CRIAR CONTA<i class="far fa-arrow-right"></i> </a>
                                    </div>
                                </div>

                            </div>
                        </div>
                        <img class="d-none d-lg-block" src="assets/img/zumu.png" alt="png" width="350">
                    </div>
                </div>
            </div>
            <!-- Banner Item End -->
            <!-- Banner Item Start -->
            <div class="sigma_banner-slider-inner">
                <div class="sigma_banner-text">
                    <div class="container position-relative">
                        <div class="row align-items-center">
                            <div class="offset-lg-6 col-lg-6">
                                <div class="sigma_box primary-bg banner-cta">
                                    <h1 class="text-white title">"JUNTAR EU FAÇO"</h1>
                                    <p class="blockquote light light-border mb-0"> 
	        							Profissionalize a comunicação com os seus clientes e parceiros</p>
                                    <div class="section-button d-flex align-items-center">

                                    </div>
                                </div>
                            </div>
                        </div>
                        <img class="d-none d-lg-block" src="assets/img/zumu.png" alt="png" width="350">
                    </div>
                </div>
            </div>
        </div>

    </div>

    <div class="section section-padding pt-0">
        <div class="container">
            <div class="section-title text-center">
                <p class="subtitle">ALGUNS DOS NOSSOS PACOTES</p>
                <h4 class="title text-white">PACOTES SMS</h4>
            </div>
            <div id='pacote'>
                <div class="d-flex justify-content-center">
                    <div class="spinner-border text-primary" style="width: 50px; height: 50px;" role="status">
                        <span class="visually-hidden"></span>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <!-- Banner End -->
    <input type="hidden" name="token" id="token" class="form-control" value="<?= $this->authCsrf ?>">
    <?php include_once("footer_zumu.phtml"); ?>


    <!-- partial:partia/__scripts.html -->
    <script src="assets/js/plugins/jquery-3.4.1.min.js"></script>
    <script src="assets/js/plugins/popper.min.js"></script>
    <script src="assets/js/plugins/bootstrap.min.js"></script>
    <script src="assets/js/plugins/imagesloaded.min.js"></script>
    <script src="assets/js/plugins/jquery.magnific-popup.min.js"></script>
    <script src="assets/js/plugins/jquery.countdown.min.js"></script>
    <script src="assets/js/plugins/jquery.waypoints.min.js"></script>
    <script src="assets/js/plugins/jquery.counterup.min.js"></script>
    <script src="assets/js/plugins/jquery.zoom.min.js"></script>
    <script src="assets/js/plugins/jquery.inview.min.js"></script>
    <script src="assets/js/plugins/jquery.event.move.js"></script>
    <script src="assets/js/plugins/wow.min.js"></script>
    <script src="assets/js/plugins/isotope.pkgd.min.js"></script>
    <script src="assets/js/plugins/slick.min.js"></script>
    <script src="assets/js/plugins/ion.rangeSlider.min.js"></script>
    <script src="dist/js/Pacotes.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <script src="assets/js/main.js"></script>
    <script>
        if (!!(window.addEventListener)) window.addEventListener('DOMContentLoaded', main);
        else window.attachEvent('onload', main);

        function main() {

            if (localStorage.getItem("theme") == 1) {
                $('body').addClass('dark-mode')
            }
            getPacotesSite();
        }
    </script>
    <!-- partial -->

</body>


<!-- Mirrored from slidesigma.com/themes/html/martalaa/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 08 Jun 2022 16:28:47 GMT -->

</html>