<!DOCTYPE html>
<html lang="pt" dir="ltr">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Termos & condições</title>

    <!-- Favicon -->
    <link rel="icon" type="image/png" sizes="32x32" href="favicon.ico">

  <!-- partial:partial/__stylesheets.html -->
  <?php include_once("headercss.phtml"); ?>

</head>

<body>
    <?php include_once("menu_center.phtml"); ?>
    <!-- partial -->

    <!-- partial:partia/__subheader.html -->
    <div class="sigma_subheader dark-overlay dark-overlay-2" style="background-image: url(assets/img/subheader.jpg)">

        <div class="container">
            <div class="sigma_subheader-inner">
                <div class="sigma_subheader-text">
                    <h1>Termos & Condições</h1>
                    <p class="blockquote light"> We are a church that belives in Jesus christ and the followers and We are a church that belives in Jesus christ </p>
                </div>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a class="btn-link" href="#">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Termos & Condições</li>
                    </ol>
                </nav>
            </div>
        </div>

    </div>
    <!-- partial -->

    <!-- Categories Start -->

        <div class="container">
            <div class="row">
                <div class="col-lg-12 mb-4">
                    <div class="accordion with-gap" id="generalFAQExample">
                        <div class="card">
                            <div class="card-header" data-bs-toggle="collapse" role="button" data-bs-target="#generalOne" aria-expanded="true" aria-controls="generalOne">
                                A. PARTE GERAL
                            </div>

                            <div id="generalOne" class="collapse show" data-bs-parent="#generalFAQExample">
                                <div class="card-body">

                                    <p> 1.1. RECOLHA E TRATAMENTO DE DADOS DO UTILIZADOR</p>

                                    <p> No âmbito da disponibilização do website, zumu_sms.com, alojado em XXXXXX
                                        e dos serviços e comunicações ali disponibilizados, a zumu_sms, com sede em
                                        Luanda, Município de Belas, Distrito Urbano da Samba, Bairro Morro Bento,
                                        Avenida 21 de Janeiro, Casa nº 31, sob o número único de matrícula e pessoa coletiva
                                        260 /14. Poderá requisitar ao Utilizador que disponibilize dados pessoais, isto é,
                                        informações fornecidas pelo Utilizador que permitam a zumu_sms identificálo e/ou contatá-lo (“Dados Pessoais”).
                                        Por regra, os Dados Pessoais são requisitados quando o Utilizador se regista no Site,
                                        solicita um contacto e/ou envio de newsletters, subscreve um determinado Serviço,
                                        adquire um produto ou estabelece uma relação contratual com a zumu_sms.</p>

                                    <p> Os Dados Pessoais recolhidos e tratados consistem em informação relativa ao nome,
                                        sexo, e-mail, credenciais de acesso, número de filhos, nome dos filhos, data de
                                        nascimento dos filhos, login/logout (sessões), páginas vistas (não identificadas e
                                        identificadas por identificador do utilizador) e compras de bens e serviços, embora
                                        possam vir a ser recolhidos outros Dados Pessoais que possam ser necessários ou
                                        convenientes para a prestação de Serviços por parte da zumu_sms.</p>

                                    <p> Através da presente Política de Privacidade a zumu_sms presta ao Utilizador
                                        informações detalhadas acerca da natureza dos dados recolhidos e acerca da
                                        finalidade e do tratamento que será realizado relativamente aos Dados Pessoais, e,
                                        bem assim, as informações mencionadas na cláusula 8.</p>

                                    <p> A zumu_sms também recolhe e trata informação sobre o seu hardware e
                                        software, assim como informação sobre as páginas visitadas pelo Utilizador dentro
                                        do Site.</p>
                                    <p> Esta informação pode incluir: o seu tipo de browser, o nome de domínio,
                                        os tempos de acesso e as hiperligações através das quais o Utilizador acedeu ao Site
                                        (“Informação de Usabilidade”). Utilizamos esta informação apenas para melhorar a
                                        qualidade da sua visita ao nosso Site.</p>
                                    A Informação de Usabilidade e os Dados Pessoais são designados na presente
                                    Política de Privacidade por “Dados do Utilizador”.

                                </div>
                            </div>
                        </div>
                        <div class="card">
                            <div class="card-header" data-bs-toggle="collapse" role="button" data-bs-target="#generalTwo" aria-expanded="false" aria-controls="generalTwo">
                                1.2. ENTIDADES SUBCONTRATADAS

                            </div>

                            <div id="generalTwo" class="collapse" data-bs-parent="#generalFAQExample">
                                <div class="card-body">

                                    <p> No âmbito do tratamento dos Dados do Utilizador, a zumu_sms recorre ou
                                        poderá recorrer a entidades terceiras, por si subcontratadas, para, em nome da
                                        zumu_sms, e de acordo com as instruções dadas por esta, procederem ao
                                        tratamento dos Dados do Utilizador, em estrito cumprimento com o disposto na lei
                                        e na presente Política de Privacidade.</p>

                                    <p>Estas entidades subcontratadas não poderão transmitir os Dados do Utilizador a
                                        outras entidades.</p>

                                    <p> A zumu_sms assume o compromisso de subcontratar apenas entidades que
                                        apresentem garantias suficientes de execução das medidas técnicas e organizativas
                                        adequadas, de forma a assegurar a defesa dos direitos do Utilizador.</p>

                                    <p> Todas as entidades subcontratadas pela zumu_sms ficam vinculadas a esta última através
                                        de um contrato escrito no qual são regulados, nomeadamente, o objeto e a duração
                                        do tratamento, a natureza e finalidade do tratamento, o tipo de dados pessoais, as
                                        categorias dos titulares dos dados e os direitos e obrigações das partes.</p>

                                    <p> Aquando da recolha dos dados pessoais, a zumu_sms presta ao Utilizador
                                        informações acerca das categorias de entidades subcontratadas que, no caso
                                        concreto, possam efetuar tratamentos de dados em nome da zumu_sms.</p>
                                </div>
                            </div>
                        </div>
                        <div class="card">
                            <div class="card-header" data-bs-toggle="collapse" role="button" data-bs-target="#generalThree" aria-expanded="false" aria-controls="generalThree">
                                1.3. CANAIS DE RECOLHA DOS DADOS

                            </div>

                            <div id="generalThree" class="collapse" data-bs-parent="#generalFAQExample">
                                <div class="card-body">
                                    <p>
                                        A zumu_sms poderá recolher dados de forma direta (i.e., diretamente junto
                                        do Utilizador) ou de forma indireta (i.e., através de entidades parceiras ou terceiros).
                                        A recolha pode ser feita através dos seguintes canais:</p>
                                    <p>Recolha direta:
                                    <p> presencialmente, por telefone, por e-mail e através do Site.</p>
                                </div>
                            </div>
                        </div>
                        <div class="card">
                            <div class="card-header" data-bs-toggle="collapse" role="button" data-bs-target="#generalSeven" aria-expanded="false" aria-controls="generalSeven">
                                2. PRINCÍPIOS GERAIS APLICÁVEIS AO TRATAMENTO DE DADOS DO UTILIZADOR
                            </div>

                            <div id="generalSeven" class="collapse" data-bs-parent="#generalFAQExample">
                                <div class="card-body">

                                    <p> Em termos de princípios gerais relativos ao tratamento de dados pessoais, a
                                        zumu_sms compromete-se a assegurar que os Dados do Utilizador por si
                                        tratados são:</p>

                                    <p>
                                        <li>
                                            Objeto de um tratamento lícito, leal e transparente em relação ao Utilizador;
                                        </li>
                                        <li>
                                            Recolhidos para finalidades determinadas, explícitas e legítimas, não sendo tratados
                                            posteriormente de uma forma incompatível com essas finalidades;</li>
                                    </p>
                                    <p>
                                        <li>
                                            • Adequados, pertinentes e limitados ao que é necessário relativamente às finalidades
                                            para as quais são tratados;
                                        </li>
                                        <li>
                                            • Exatos e atualizados sempre que necessário, sendo adotadas todas as medidas
                                            adequadas para que os dados inexatos, tendo em conta as finalidades para que são
                                            tratados, sejam apagados ou retificados sem demora;
                                        </li>
                                        <li>
                                            • Conservados de uma forma que permite a identificação do Utilizador apenas
                                            durante o período necessário para as finalidades para as quais os dados são tratado
                                        </li>
                                        <li>
                                            • Tratados de uma forma que garante a sua segurança, incluindo a proteção contra o
                                            seu tratamento não autorizado ou ilícito e contra a sua perda, destruição ou
                                            danificação acidental, sendo adotadas as medidas técnicas ou organizativas
                                            adequadas
                                        </li>
                                        .
                                    </p>
                                    <p>Os tratamentos de dados efetuados pela zumu_sms são lícitos quando se
                                        verifique pelo menos uma das seguintes situações:</p>

                                    <p>
                                        <li>
                                            • O Utilizador tiver dado o seu consentimento explícito para o tratamento dos Dados
                                            do Utilizador para uma ou mais finalidades específicas;
                                        </li>
                                        <li>
                                            • O tratamento for necessário para a execução de um contrato no qual o Utilizador
                                            é parte, ou para diligências pré-contratuais a pedido do Utilizador;
                                        </li>
                                        <li>
                                            O tratamento for necessário para o cumprimento de uma obrigação jurídica a que
                                            a zumu_sms esteja sujeita;
                                        </li>
                                        <li>
                                            O tratamento for necessário para a defesa de interesses vitais do Utilizador ou de
                                            outra pessoa singular;
                                        </li>
                                    </p>
                                    <p>
                                        O tratamento for necessário para efeito dos interesses legítimos prosseguidos pela
                                        zumu_sms ou por terceiros (exceto se prevalecerem os interesses ou direitos e
                                        liberdades fundamentais do Utilizador que exijam a proteção dos dados pessoais).
                                        A zumu_sms compromete-se a assegurar que o tratamento dos Dados do
                                        Utilizador apenas é feito nas condições acima elencadas e com respeito pelos
                                        princípios acima mencionados.
                                    </p>
                                    <p>Quando o tratamento dos Dados do Utilizador for realizado pela zumu_sms
                                        com base no consentimento do Utilizador, este tem o direito de retirar o seu
                                        consentimento a qualquer momento. A retirada do consentimento, todavia, não
                                        compromete a licitude do tratamento efetuado pela zumu_sms com base no
                                        consentimento previamente dado pelo Utilizador.</p>

                                    <p> O período de tempo durante o qual os dados são armazenados e conservados varia
                                        de acordo com a finalidade para a qual a informação é tratada.</p>
                                    <p> Efetivamente, existem requisitos legais que obrigam a conservar os dados por um
                                        período de tempo mínimo. Assim, e sempre que não exista uma exigência legal
                                        especifica, os dados serão armazenados e conservados apenas pelo período mínimo
                                        necessário para as finalidades que motivaram a sua recolha ou o seu posterior
                                        tratamento, findo o qual os mesmos serão eliminados.</p>
                                </div>
                            </div>
                        </div>

                        <div class="card">
                            <div class="card-header" data-bs-toggle="collapse" role="button" data-bs-target="#generalThree1" aria-expanded="false" aria-controls="generalThree1">
                                3. UTILIZAÇÃO E FINALIDADES DO TRATAMENTO DE DADOS DO
                                UTILIZADOR

                            </div>

                            <div id="generalThree1" class="collapse" data-bs-parent="#generalFAQExample">
                                <div class="card-body">
                                    <p>
                                        Em termos gerais, a zumu_sms utiliza os Dados do Utilizador para as seguintes
                                        finalidades:
                                    </p>
                                    <p>
                                        <li> Gestão de contatos com o Utilizador</li>
                                        <li> Faturação e cobrança ao Utilizador;</li>
                                        <li> Registo do Utilizador no Site;</li>
                                    </p>
                                    <p>
                                    <p>
                                        <li>
                                            Permitir o acesso a áreas restritas do Site, de acordo com termos previamente
                                            estabelecidos;
                                        </li>
                                        <li>
                                            Garantir que o Site vai ao encontro das necessidades do Utilizador, através do
                                            desenvolvimento e publicação de conteúdos o mais adaptados possível às
                                            solicitações e ao tipo de Utilizador, da melhoria das capacidades de pesquisa e
                                            funcionalidades do Site e da obtenção de informação agregada ou estatística
                                            relativamente ao perfil tipo do Utilizador (análise de perfis de consumo);
                                        </li>
                                        <li>
                                            Envio de newsletters, inquéritos de opinião, ou outras informações sobre produtos
                                            requisitados ou comprados pelo Utilizador;
                                        </li>
                                        <li>
                                            Gravação das chamadas telefónicas que vierem a ser realizadas no âmbito da
                                            relação contratual, quer na fase de formação do contrato, quer durante a sua vigência;
                                        </li>
                                        <li>
                                            A zumu_sms pode combinar Informação de Usabilidade com informação
                                            demográfica anónima para efeitos de pesquisa, e podemos usar o resultado dessa
                                            combinação para fornecer conteúdos mais relevantes no Site. Em determinadas
                                            áreas restritas do Site, a zumu_sms pode combinar Dados Pessoais com
                                            Informação de Usabilidade para fornecer ao Utilizador um conteúdo mais
                                            personalizado.
                                        </li>

                                    </p>

                                    <p> Os Dados do Utilizador recolhidos pela zumu_sms não são partilhados com
                                        terceiros sem consentimento do Utilizador, com exceção das situações referidas no
                                        parágrafo a seguir. No entanto, no caso de o Utilizador contratar junto da
                                        zumu_sms serviços que sejam prestados por outras entidades responsáveis
                                        pelo tratamento de dados pessoais, os Dados do Utilizador poderão ser consultados
                                        ou acedidos por essas entidades, na medida em que tal seja necessário à prestação
                                        dos referidos serviços.</p>
                                    <p>
                                        Nos termos legais aplicáveis, a zumu_sms poderá transmitir ou comunicar os
                                        Dados do Utilizador a outras entidades no caso de essa transmissão ou comunicação
                                        ser necessária para a execução do contrato estabelecido entre o Utilizador e a
                                        zumu_sms, ou para diligências pré-contratuais a pedido do Utilizador, no caso
                                        de ser necessária para o cumprimento de uma obrigação jurídica a que a
                                        zumu_sms esteja sujeito ou no caso de ser necessária para efeito da
                                        prossecução de interesses legítimos da zumu_sms ou de terceiro.
                                    </p>
                                    <p>
                                        Ocorrendo
                                        uma transmissão de Dados do Utilizador a terceiros, envidaremos os esforços
                                    </p>

                                    <p>
                                        considerados razoáveis para que o transmissário utilize os Dados do Utilizador
                                        transmitidos de forma consentânea com a nossa Política de Privacidade
                                    </p>
                                    </p>

                                </div>
                            </div>
                        </div>

                        <div class="card">
                            <div class="card-header" data-bs-toggle="collapse" role="button" data-bs-target="#generalThree2" aria-expanded="false" aria-controls="generalThree2">
                                4. MEDIDAS TÉCNICAS, ORGANIZATIVAS E DE SEGURANÇA
                                IMPLEMENTADAS

                            </div>

                            <div id="generalThree2" class="collapse" data-bs-parent="#generalFAQExample">
                                <div class="card-body">
                                    <p>

                                    <p>
                                        Para garantir a segurança dos Dados do Utilizador e a máxima confidencialidade,
                                        tratamos a informação que nos forneceu de forma absolutamente confidencial, de
                                        acordo com as nossas políticas e procedimentos internos de segurança e
                                        confidencialidade, os quais são atualizados periodicamente consoante as
                                        necessidades, bem como de acordo com os termos e condições legalmente previstos.
                                    </p>
                                    <p>
                                        Em função da natureza, do âmbito, do contexto e das finalidades do tratamento dos
                                        dados, bem como dos riscos decorrentes do tratamento para os direitos e liberdades
                                        do Utilizador, a zumu_sms compromete-se a aplicar, tanto no momento de
                                        definição dos meios de tratamento como no momento do próprio tratamento, as
                                        medidas técnicas e organizativas necessárias e adequadas à proteção dos Dados do
                                        Utilizador e ao cumprimento dos requisitos legais.
                                    </p>
                                    <p>
                                        Compromete-se ainda a assegurar que, por defeito, só sejam tratados os dados que
                                        forem necessários para cada finalidade específica do tratamento e que esses dados
                                        não sejam disponibilizados sem intervenção humana a um número indeterminado
                                        de pessoas.
                                    </p>

                                    <p>
                                        Em termos de medidas gerais, a zumu_sms adota as seguintes:
                                    </p>
                                    <p>
                                        <li>
                                            Auditorias regulares com vista a aferir a eficácia das medidas técnicas e
                                            organizativas implementadas;
                                        </li>
                                        <li>
                                            Sensibilização e formação do pessoal implicado nas operações de tratamento de
                                            dados;
                                        </li>
                                        <li>
                                            Pseudonimização e cifragem de dados pessoais;
                                        </li>
                                        <li>
                                            Mecanismos capazes de assegurar a confidencialidade, disponibilidade e resiliência
                                            permanentes dos sistemas de informação;
                                        </li>
                                        <li>
                                            Mecanismos que asseguram o restabelecimento dos sistemas de informação e o
                                            acesso aos dados pessoais de forma atempada no caso de um incidente físico ou
                                            técnico;
                                        </li>
                                    </p>

                                    </p>
                                </div>
                            </div>
                        </div>

                        <div class="card">
                            <div class="card-header" data-bs-toggle="collapse" role="button" data-bs-target="#generalThree" aria-expanded="false" aria-controls="generalThree">
                                --*---

                            </div>

                            <div id="generalThree" class="collapse" data-bs-parent="#generalFAQExample">
                                <div class="card-body">
                                    <p>
                                        A zumu_sms poderá recolher dados de forma direta (i.e., diretamente junto
                                        do Utilizador) ou de forma indireta (i.e., através de entidades parceiras ou terceiros).
                                        A recolha pode ser feita através dos seguintes canais:</p>
                                    <p>Recolha direta:
                                    <p> presencialmente, por telefone, por e-mail e através do Site.</p>
                                </div>
                            </div>
                        </div>

                        <div class="card">
                            <div class="card-header" data-bs-toggle="collapse" role="button" data-bs-target="#generalThree" aria-expanded="false" aria-controls="generalThree">
                                --*---

                            </div>

                            <div id="generalThree" class="collapse" data-bs-parent="#generalFAQExample">
                                <div class="card-body">
                                    <p>
                                        A zumu_sms poderá recolher dados de forma direta (i.e., diretamente junto
                                        do Utilizador) ou de forma indireta (i.e., através de entidades parceiras ou terceiros).
                                        A recolha pode ser feita através dos seguintes canais:</p>
                                    <p>Recolha direta:
                                    <p> presencialmente, por telefone, por e-mail e através do Site.</p>
                                </div>
                            </div>
                        </div>

                        <div class="card">
                            <div class="card-header" data-bs-toggle="collapse" role="button" data-bs-target="#generalThree" aria-expanded="false" aria-controls="generalThree">
                                --*---

                            </div>

                            <div id="generalThree" class="collapse" data-bs-parent="#generalFAQExample">
                                <div class="card-body">
                                    <p>
                                        A zumu_sms poderá recolher dados de forma direta (i.e., diretamente junto
                                        do Utilizador) ou de forma indireta (i.e., através de entidades parceiras ou terceiros).
                                        A recolha pode ser feita através dos seguintes canais:</p>
                                    <p>Recolha direta:
                                    <p> presencialmente, por telefone, por e-mail e através do Site.</p>
                                </div>
                            </div>
                        </div>

                        <div class="card">
                            <div class="card-header" data-bs-toggle="collapse" role="button" data-bs-target="#generalThree" aria-expanded="false" aria-controls="generalThree">
                                --*---

                            </div>

                            <div id="generalThree" class="collapse" data-bs-parent="#generalFAQExample">
                                <div class="card-body">
                                    <p>
                                        A zumu_sms poderá recolher dados de forma direta (i.e., diretamente junto
                                        do Utilizador) ou de forma indireta (i.e., através de entidades parceiras ou terceiros).
                                        A recolha pode ser feita através dos seguintes canais:</p>
                                    <p>Recolha direta:
                                    <p> presencialmente, por telefone, por e-mail e através do Site.</p>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <!-- Categories End -->

        <!-- Form Start -->
        <div class="section dark-overlay dark-overlay-3 bg-cover bg-center bg-norepeat" style="background-image: url(assets/img/bg4.jpg)">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-6 mb-lg-30">
                        <form class=" m-0 mf_form_validate ajax_submit" action="/envioemail" method="post" enctype="multipart/form-data">
                            <div class="form-row">
                                <div class="col-lg-6">
                                    <div class="form-group ">
                                        <i class="far fa-envelope"></i>
                                        <input type="email" placeholder="Seu Endereço Email" class="form-control transparent" name="email">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <i class="far fa-user"></i>
                                        <input type="text" placeholder="Seu nome completo" class="form-control transparent" name="name">
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <i class="far fa-pencil"></i>
                                        <input type="text" placeholder="Assunto" class="form-control transparent" name="Subesubject">
                                    </div>
                                </div>
                                <input type="hidden" placeholder="token" class="form-control transparent" value="<?= $this->authCsrf ?>" name="token">
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <textarea name="message" placeholder="Deixa a sua mensagen " cols="45" rows="5" class="form-control transparent"></textarea>
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <button type="submit" class="sigma_btn-custom d-block w-100" id="button" name="button"> Enviar <i class="far fa-arrow-right"></i> </button>
                                </div>
                                <div class="server_response w-100">
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="col-lg-6">
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="sigma_client">
                                    <img src="assets/img/clients/1.png" alt="client">
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="sigma_client">
                                    <img src="assets/img/clients/2.png" alt="client">
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="sigma_client">
                                    <img src="assets/img/clients/3.png" alt="client">
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="sigma_client">
                                    <img src="assets/img/clients/4.png" alt="client">
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="sigma_client">
                                    <img src="assets/img/clients/5.png" alt="client">
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="sigma_client">
                                    <img src="assets/img/clients/6.png" alt="client">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <!-- Form End -->

        <!-- partial:partia/__footer.html -->
        <?php include_once("footer_zumu_sms.phtml"); ?>
        <!-- partial -->


        <!-- partial:partia/__scripts.html -->
        <script src="assets/js/plugins/jquery-3.4.1.min.js"></script>
        <script src="assets/js/plugins/popper.min.js"></script>
        <script src="assets/js/plugins/bootstrap.min.js"></script>
        <script src="assets/js/plugins/imagesloaded.min.js"></script>
        <script src="assets/js/plugins/jquery.magnific-popup.min.js"></script>
        <script src="assets/js/plugins/jquery.countdown.min.js"></script>
        <script src="assets/js/plugins/jquery.waypoints.min.js"></script>
        <script src="assets/js/plugins/jquery.counterup.min.js"></script>
        <script src="assets/js/plugins/jquery.zoom.min.js"></script>
        <script src="assets/js/plugins/jquery.inview.min.js"></script>
        <script src="assets/js/plugins/jquery.event.move.js"></script>
        <script src="assets/js/plugins/wow.min.js"></script>
        <script src="assets/js/plugins/isotope.pkgd.min.js"></script>
        <script src="assets/js/plugins/slick.min.js"></script>
        <script src="assets/js/plugins/ion.rangeSlider.min.js"></script>
        <script src="assets/js/plugins/jquery.validate.min.js"></script>

        <script src="assets/js/main.js"></script>
        <script src="assets/functions/mf_form.js"></script>
        <!-- partial -->

</body>

</html>
