<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title><?=$this->configuracao->dataEmpresa->nome_sistema ?? ''?> </title>
    <meta content=" <?=$this->configuracao->dataEmpresa->objectivo ?? ''?>" name="description">
    <meta content="Marketing de mensagem,sms,agendamento de sms,notificaçãoes sms, Angola sms,envio de sms" name="keywords">

    <!-- Favicons -->
    <link href="<?=API_URL_LOGO . "" . $_SESSION['LOGO_SISTEMA'] ?? ''?>" rel="icon">
    <link href="<?=API_URL_LOGO . "" . $_SESSION['LOGO_SISTEMA'] ?? ''?>" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="assets/vendor/aos/aos.css" rel="stylesheet">

    <link href="assets/vendor/bootstrap/css/bt.css" rel="stylesheet">
    <link href="assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

    <!-- Template Main CSS File bootstrap.min -->
    <link href="assets/css/style.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />

    <!-- =======================================================
  * Template Name: Bocor
  * Updated: Mar 10 2023 with Bootstrap v5.2.3
  * Template URL: https://.com/bocor-bootstrap-template-nice-animation/
  * Author: .com
  * License: https://.com/license/
  ======================================================== -->
</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header">
        <!-- Preloader Start -->
        <div class="sigma_preloader ">
            <img class="animate__animated animate__bounce" src="<?=API_URL_LOGO . "" . $_SESSION['LOGO_SISTEMA'] ?? ''?>" alt="ZUMU SMS" width="200">
        </div>
        <!-- Preloader End -->
        <div class="container d-flex align-items-center justify-content-between">

            <div class="logo">
                <!--  Uncomment below if you prefer to use an image logo -->
                <a href="/"><img src="<?=API_URL_LOGO . "" . $_SESSION['LOGO_SISTEMA'] ?? ''?>" alt="<?=$this->configuracao->dataEmpresa->nome_sistema ?? ''?>" class="img-fluid"></a>
                <!--  <h1><a href="/"><?=$this->configuracao->dataEmpresa->nome_sistema ?? ''?><span>.</span></a></h1>-->
            </div>

            <nav id="navbar" class="navbar">
                <ul>

                    <li><a class="nav-link scrollto active" href="#hero">INICIO</a></li>
                    <li><a class="nav-link scrollto" href="#about">SOBRE</a></li>
                    <li><a class="nav-link scrollto" href="#pricing">PACOTE</a></li>
                    <li><a class="nav-link scrollto" href="tel:<?=$this->configuracao->dataEmpresa->contacto ?? ''?>">(+244) <?=$this->configuracao->dataEmpresa->contacto ?? ''?></a></li>
                    <li><a class="getstarted scrollto" href="/login">LOGIN</a></li>
                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav><!-- .navbar -->

        </div>
    </header><!-- End Header -->

    <!-- ======= Hero Section ======= -->
    <section id="hero">

        <div class="container">
            <div class="row d-flex align-items-center mb-2">
                <div class=" col-lg-6 py-5 py-lg-0 order-2 order-lg-1" data-aos="fade-right">
                    <h1><?=$this->configuracao->dataEmpresa->dica_sistema ?? ''?></h1>
                    <h2> <?=$this->configuracao->dataEmpresa->objectivo ?? ''?></h2>
                    <a href="/login" class="btn-get-started scrollto">LOGIN</a>
                    <a href="/register" class="btn-get-started scrollto">REGISTER</a>
                </div>
                <div class="col-lg-6 order-1 order-lg-2 hero-img mb-5 animate__animated animate__rotateIn">
                    <img src="assets/img/zumu.png" class="img-fluid" alt="<?=$this->configuracao->dataEmpresa->nome_sistema ?? ''?>" width="">
                </div>
            </div>
            <br>
            <br>

        </div>

    </section><!-- End Hero -->

    <main id="main">

        <!-- ======= Clients Section ======= -->
        <section id="clients" class="clients section-bg">
            <div class="container">

                <div class="row no-gutters clients-wrap clearfix " data-aos="fade-up">

                    <div class="col-lg-2 col-md-4 col-6">
                        <div class="client-logo">
                            <img src="assets/img/clients/client-1.png" class="img-fluid" alt="" >
                        </div>
                    </div>

                    <div class="col-lg-2 col-md-4 col-6">
                        <div class="client-logo">
                            <img src="assets/img/clients/client-2.png" class="img-fluid" alt=""  data-aos-delay="100">
                        </div>
                    </div>

                    <div class="col-lg-2 col-md-4 col-6">
                        <div class="client-logo">
                            <img src="assets/img/clients/client-3.png" class="img-fluid" alt=""  data-aos-delay="200">
                        </div>
                    </div>

                    <div class="col-lg-2 col-md-4 col-6">
                        <div class="client-logo">
                            <img src="assets/img/clients/client-4.png" class="img-fluid" alt=""  data-aos-delay="300">
                        </div>
                    </div>

                    <div class="col-lg-2 col-md-4 col-6">
                        <div class="client-logo">
                            <img src="assets/img/clients/client-5.png" class="img-fluid" alt=""  data-aos-delay="400">
                        </div>
                    </div>

                    <div class="col-lg-2 col-md-4 col-6">
                        <div class="client-logo">
                            <img src="assets/img/clients/client-6.png" class="img-fluid" alt=""  data-aos-delay="500">
                        </div>
                    </div>

                </div>

            </div>
        </section><!-- End Clients Section -->

        <!-- ======= About Section ======= -->
        <section id="about" class="about section-bg">
            <div class="container">

                <div class="row gy-4">
                    <div class="image col-xl-5">
                        <img src="<?=API_URL_LOGO . "" . $_SESSION['LOGO_SISTEMA'] ?? ''?>" class="img-fluid" alt="">
                    </div>
                    <div class="col-xl-7">
                        <div class="content d-flex flex-column justify-content-center ps-0 ps-xl-4">
                            <h3 data-aos="fade-in" data-aos-delay="100">Sobre o <?=$this->configuracao->dataEmpresa->nome_sistema ?? ''?></h3>
                            <p data-aos="fade-in">
                                <?=$this->configuracao->dataEmpresa->nome_sistema ?? ''?> <p>Introduzindo uma plataforma online completa e profissional dedicada ao envio estratégico de SMS em Angola. Nossa solução abrange tanto o campo do SMS Marketing quanto o envio de Notificações por SMS. Equipada com uma extensa variedade de recursos e funcionalidades, nossa plataforma oferece uma experiência de usuário singular e altamente satisfatória.</p>
                            </p>
                            <div class="row gy-4 mt-3">
                                <div class="col-md-6 icon-box" data-aos="fade-up">
                                    <i class="bx bx-receipt"></i>
                                    <h4><a href="#">NIF</a></h4>
                                    <p><?=$_SESSION['NIF_SISTEMA'] ?? ''?></a></p>
                                </div>
                                <div class="col-md-6 icon-box" data-aos="fade-up" data-aos-delay="100">
                                    <i class="bx bx-cube-alt"></i>
                                    <h4><a href="#">ATENDIMENTO</a></h4>
                                    <p> <?=$_SESSION['hora_atendimento_inicio'] ?? ''?>H | <?=$_SESSION['hora_atendimento_termino'] ?? ''?>H</a> </p>
                                </div>
                                <div class="col-md-6 icon-box" data-aos="fade-up" data-aos-delay="200">
                                    <i class="bx bx-images"></i>
                                    <h4><a href="#">EMAIL</a></h4>
                                    <p><?=$this->configuracao->dataEmpresa->email ?? ''?></p>
                                </div>
                                <div class="col-md-6 icon-box" data-aos="fade-up" data-aos-delay="300">
                                    <i class="bx bx-shield"></i>
                                    <h4><a href="#">NÍVEL</a></h4>
                                    <p>Plataforma profissional para envio de SMS.</p>
                                </div>
                            </div>
                        </div><!-- End .content-->
                    </div>
                </div>

            </div>
        </section><!-- End About Section -->


      <!-- ======= Seção de Recursos ======= -->
<section id="features" class="features section-bg">
    <div class="container">

        <div class="section-title">
            <h2 data-aos="fade-in">Recursos</h2>
            <p data-aos="fade-in">Plataforma Completa e Avançada</p>
        </div>

        <div class="row content">
            <div class="col-md-5" data-aos="fade-right">
                <img src="assets/img/features-1.svg" class="img-fluid" alt="Ilustração de Recursos">
            </div>
            <div class="col-md-7 pt-4" data-aos="fade-left">
                <h3>UM SÓ PASSO, VÁRIOS BENEFÍCIOS</h3>
                <p class="fst-italic">
                    Nossos recursos foram cuidadosamente projetados para oferecer a melhor e mais completa experiência de utilização, atendendo às necessidades de diversas empresas.
                </p>
                <ul>
                    <li><i class="bi bi-check"></i> Campanhas de SMS Marketing.</li>
                    <li><i class="bi bi-check"></i> Envio em massa de SMS.</li>
                    <li><i class="bi bi-check"></i> Agendamentos de envio de mensagens (Grupos, em massa).</li>
                    <li><i class="bi bi-check"></i> Importação de Contatos (Excel).</li>
                    <li><i class="bi bi-check"></i> Exportação de Contatos (Excel).</li>
                    <li><i class="bi bi-check"></i> Envio para múltiplos contatos.</li>
                    <li><i class="bi bi-check"></i> Sender ID da sua empresa Grátis.</li>
                </ul>
            </div>
        </div>

    </div>
</section><!-- Fim da Seção de Recursos -->


        <!-- ======= Pricing Section ======= -->
        <section id="pricing" class="pricing section-bg">
        <div class="container">

<div class="section-title">
    <h2 data-aos="fade-in">PACOTES SMS</h2>
    <p data-aos="fade-in">Alcance todos os seus clientes e atinja seu público-alvo com nossa poderosa ferramenta de SMS Marketing.</p>
</div>

<section id='pacote'>
    <div class="d-flex justify-content-center">
        <div class="spinner-border text-primary" style="width: 50px; height: 50px;" role="status">
            <span class="visually-hidden">Carregando...</span>
        </div>
    </div>
</section>

</div>


            <input type="hidden" name="token" id="token" class="form-control" value="<?=$this->authCsrf?>">
        </section><!-- End Pricing Section -->



    </main><!-- End #main -->

    <!-- ======= Footer ======= -->
    <footer id="footer">

        <div class="footer-top">

            <div class="container">

                <div class="row  justify-content-center">
                    <div class="col-lg-6">
                        <div class="logo">
                            <!-- Uncomment below if you prefer to use an image logo -->
                            <h1><a href="/"><?=$this->configuracao->dataEmpresa->nome_sistema ?? ''?><span>.</span></a></h1>
                        </div>
                        <p>Descubra uma plataforma completa e profissional, repleta de recursos estratégicos para otimizar suas campanhas de marketing e fortalecer a comunicação com seus clientes e parceiros em Angola por meio de mensagens SMS. Maximize o impacto, alcance seu público-alvo e eleve sua presença de marca com nossa solução de SMS Marketing de ponta.</p>
                    </div>
                </div>

                <div class="row footer-newsletter justify-content-center">
                    <div class="col-lg-6">
                        <form action="" method="post">
                            <input type="email" name="email" placeholder="Enter your Email"><input type="submit" value="Subscribe">
                        </form>
                    </div>
                </div>

                <div class="social-links">
                    <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                    <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                    <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                    <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
                    <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
                </div>

            </div>
        </div>

        <div class="container footer-bottom clearfix">
            <div class="copyright">
                &copy; <strong><span><?=$this->configuracao->dataEmpresa->nome_sistema ?? ''?></span></strong>. All Rights Reserved
            </div>
            <div class="credits">

                Designed by <a href=""><?=$this->configuracao->dataEmpresa->nome_sistema ?? ''?></a>
            </div>
        </div>
    </footer><!-- End Footer -->

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="assets/js/plugins/jquery-3.4.1.min.js"></script>
    <script src="assets/vendor/aos/aos.js"></script>
    <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="assets/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="assets/vendor/swiper/swiper-bundle.min.js"></script>
    <script src="assets/vendor/php-email-form/validate.js"></script>
    <script src="dist/js/Pacotes.js"></script>
    <!-- Template Main JS File -->
    <script src="assets/js/main.js"></script>

    <script>
        if (!!(window.addEventListener)) window.addEventListener('DOMContentLoaded', main);
        else window.attachEvent('onload', main);

        function main() {

            if (localStorage.getItem("theme") == 1) {
                $('body').addClass('dark-mode')
            }
            getPacotesSite();
        }
    </script>
</body>

</html>
