<div class="container-md">
<a href="/" class="btn btn-info"><i class="fas fa-arrow-circle-left"></i></a>
</div>

<div class="login-box">

    <div class="login-logo">
        <div class="image">
            <img src="<?=API_URL_LOGO."".$_SESSION['LOGO_SISTEMA']??''?>" alt="<?=$this->configuracao->dataEmpresa->nome_sistema??'Sem conexão / olá serviços'?>" class="brand-image img-circle " width="100" style="opacity: .8">
        </div>
        <a href="/" class="text-white"><b> <?=$this->configuracao->dataEmpresa->nome_sistema??''?></b></a>
    </div>
    <!-- /.login-logo -->
    <div class="card">
        <div class="card-body login-card-body">
            <p class="login-box-msg">Iniciar Sessão</p>
            <div id="messagem"></div>

            <form method="post" id="quickFormLogin" onsubmit="return false">
                <div class="input-group mb-3 form-group">
                    <input type="text" name="email" id="email" class="form-control" placeholder="Email">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-envelope"></span>
                        </div>
                    </div>
                    <div class="input-group mb-2 form-group" id="erroemail">
                    </div>
                </div>

                <input type="hidden" name="token" id="token" class="form-control" value="<?= $this->authCsrf ?>">

                <div class="input-group mb-3 form-group">
                    <input type="password" name="password" id="password" class="form-control" placeholder="Password">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                        </div>
                    </div>
                    <div class="input-group mb-2 form-group" id="erropassword">
                    </div>
                </div>

                <div class="row">
                    <!-- /.col -->
                    <div class="col-4">
                        <button type="submit" class="btn btn-primary btn-block" id="login">Entrar</button>
                    </div>
                    <!-- /.col -->
                </div>
            </form>

            <div class="social-auth-links text-center mb-3">
                <!--         <a href="#" class="btn btn-block btn-primary">
          <i class="fab fa-facebook mr-2"></i> Entrar com Facebook
        </a>
        <a href="#" class="btn btn-block btn-danger">
          <i class="fab fa-google-plus mr-2"></i> Entrar com Google
        </a> -->
            </div>
            <!-- /.social-auth-links -->

            <p class="mb-1">
                <a href="/forgot_password">Recuperar minha senha</a>
            </p>
            <p class="mb-0">
                <a href="/register" class="text-center">Criar conta</a>
            </p>
        </div>
        <!-- /.login-card-body -->
    </div>
    <div class="modal fade" id="modal-termos">

<div class="modal-dialog modal-dialog-centered">
    <div class="modal-content ">
        <div class="modal-header">
            <h4 class="modal-title">Termos de serviço.</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body animate__animated animate__bounceIn">
            <div class="row">
                <!-- left column -->
                <div class="col-md-12 animate__animated animate__slideInLeft">
                    <!-- jquery validation -->
                    <div class="card card-primary">

                        <form method="post" accept="image/*" name="from_membro" class="mf_form_validate_contacto ajax_submit_contacto" action="/createContacto" enctype="multipart/form-data">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-12">
                                    <p class="text-danger">Aceito todos os termos aplicado ao serviços</p>
                                    <p>O processo de alteração de telemovel ou email tem custos</p>
                                    </div>
                                </div>
                            </div>
                            <div class="modal-footer justify-content-between">
                            </div>
                        </form>
                    </div>
                    <!-- /.card -->
                </div>
            </div>
        </div>
        <div class="modal-footer justify-content-between">

            <button type="button" class="btn btn-danger" data-dismiss="modal">CANCELAR</button>

        </div>
    </div>
    <!-- /.modal-content -->
</div>
<!-- /.modal-dialog -->
</div>

</div>
