<style>
    body {
        background-color: #151F32 !important;
    }
</style>

<body class="hold-transition lockscreen">
    <!-- Automatic element centering -->
    <div class="lockscreen-wrapper">
        <div class="lockscreen-logo">
            <a href="/" class="text-white"><b> <?= $this->configuracao->dataEmpresa->nome_sistema ?? '' ?></b></a>
        </div>

        <!-- User name -->
        <div class="lockscreen-name text-center font-weight-600 text-white"><?= $_COOKIE['name_cook'] ?? '' ?></div>

        <!-- START LOCK SCREEN ITEM -->
        <div class="lockscreen-item">
            <!-- lockscreen image -->
            <div class="lockscreen-image ">
                <img src="<?= API_URL_LOGO . "" . $_SESSION['LOGO_SISTEMA'] ?? '' ?>" alt="<?= $this->configuracao->dataEmpresa->nome_sistema ?? 'Sem conexão / olá serviços' ?>" class="brand-image img-circle " style="opacity: .8">
            </div>
            <!-- /.lockscreen-image -->

            <!-- lockscreen credentials (contains the form) -->
            <form class="lockscreen-credentials" method="post" id="quickFormLogin" onsubmit="return false">
                <div class="input-group">
                    <input type="hidden" name="email" id="email" class="form-control" placeholder="email" value="<?= $_COOKIE['email_cook'] ?? '' ?>">

                    <input type="password" name="password" id="password" class="form-control" placeholder="password">

                    <input type="hidden" name="token" id="token" class="form-control" value="<?= $this->authCsrf ?>">
                    <div class="input-group-append">
                        <button type="submit" class="btn" id="login">
                            <i class="fas fa-arrow-right text-muted"></i>
                        </button>
                    </div>
                </div>
            </form>


            <!-- /.lockscreen credentials -->

        </div>
        <div class="container">
            <div id="messagem"></div>
            <div class="row">
                <div class="input-group form-group" id="erroemail">
                </div>

                <div class="input-group form-group" id="erropassword">
                </div>
            </div>

        </div>
        <!-- /.lockscreen-item -->
        <div class="help-block text-center text-white">
            Digite sua senha para recuperar sua sessão
        </div>
        <div class="text-center">
            <a href="/login?type=userd">Ou entre como um usuário diferente</a>
        </div>
        <div class="lockscreen-footer text-center text-white">
             &copy; 2022-<?= date('Y') ?> <b><a href="/" class=" text-white"><?= $this->configuracao->dataEmpresa->nome_sistema ?? '' ?></a></b><br>

        </div>
    </div>
    <!-- /.center -->

    <!-- jQuery -->
    <script src="../../plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
</body>
