 <!-- Small boxes (Stat box) -->

 <div class="row">

          <div class="col-lg-4 col-6">

            <!-- small box -->

            <div class="small-box bg-info">

              <div class="inner">

                <h3><?=$this->smsCount??'0'?></h3>

                <p>MINHAS SMS</p>

              </div>

              <div class="icon">

                <i class="ion ion-bag"></i>

              </div>

              

            </div>

          </div>

          <!-- ./col -->

          <div class="col-lg-4 col-6">

            <!-- small box -->

            <div class="small-box bg-success">

              <div class="inner">

                <h3><?=$this->sms_send??'0'?><sup style="font-size: 20px"></sup></h3>

                <p>MINHAS SMS RESTANTES</p>

              </div>

              <div class="icon">

                <i class="ion ion-stats-bars"></i>

              </div>

              

            </div>

          </div>

          <!-- ./col -->

          <div class="col-lg-4 col-6">

            <!-- small box -->

            <div class="small-box bg-warning">

              <div class="inner">

                <h3><?=$this->amunto_value."Kz"?></h3>
                <p>SALDO</p>

              </div>

              <div class="icon">

                <i class="ion ion-person-add"></i>

              </div>

              

            </div>

          </div>

          <!-- ./col -->

        </div>

