 <!-- Small boxes (Stat box) -->
 <div class="row">
     <div class="col-lg-3 col-12">
         <div class="small-box bg-info">
             <div class="inner">
                 <p>AGENDAR NOVO CULTO</p>
             </div>
             <div class="icon">
                 <i class="ion ion-stats-bars"></i>
             </div>
             <button type="button" class="btn btn-default" data-toggle="modal" data-target="#modal-culto">
                 AGENDAR
             </button>
         </div>
     </div>
     <div class="col-lg-3 col-12">
         <div class="small-box bg-info">
             <div class="inner">

                 <p>AGENDAR NOVO REUNIÃO</p>
             </div>
             <div class="icon">
                 <i class="ion ion-stats-bars"></i>
             </div>
             <button type="button" class="btn btn-default" data-toggle="modal" data-target="#modal-reuniao">
                 AGENDAR
             </button>
         </div>
     </div>
     <div class="col-lg-3 col-12">
         <div class="small-box bg-info">
             <div class="inner">

                 <p>AGENDAR NOVO EVENTOS</p>
             </div>
             <div class="icon">
                 <i class="ion ion-stats-bars"></i>
             </div>
             <button type="button" class="btn btn-default" data-toggle="modal" data-target="#modal-evento">
                 AGENDAR
             </button>
         </div>
     </div>
     <div class="col-lg-3 col-12">
         <div class="small-box bg-info">
             <div class="inner">

                 <p>AGENDAR NOVO CONSULTA PATSORAL</p>

             </div>
             <div class="icon">
                 <i class="ion ion-stats-bars"></i>
             </div>
             <button type="button" class="btn btn-default" data-toggle="modal" data-target="#modal-pastoral">
                 AGENDAR
             </button>
         </div>
     </div>
 </div>
