 <!-- Small boxes (Stat box) -->

 <div class="col-lg-6 col-12">
     <!-- small box -->
     <div class="small-box bg-info">
         <div class="inner">
             <h3 id="total_de_venda_sms">0</h3>
             <p>TOTAL DE OPERAÇÕES</p>
         </div>
         <div class="icon">
             <i class="fas fa-inbox"></i>
         </div>
        
     </div>
 </div>
 <!-- ./col -->
 <div class="col-lg-6 col-12">
     <!-- small box -->
     <div class="small-box bg-purple">
         <div class="inner">
             <h3 id="total_sms_venda_sms">0</h3>
             <p>TOTAL DE SMS</p>
         </div>
         <div class="icon">
             <i class="fas fa-file-invoice"></i>
         </div>
        
     </div>
 </div>
