<table id="example1" class="table table-bordered table-striped">
    <thead>

        <tr>
            <th>Nome</th>
            <th>Email</th>
            <th>PHONE</th>
            <th>Sald Actual</th>
            <th>Sald gasto</th>
            <th>SMS DISP</th>
            <th>SMS ENVD</th>
            <th>Senha</th>
            <th>Acção</th>
        </tr>

    </thead>
    <tbody id="corpo_institucional">
        <!-- for $this->category -->
        <?php foreach ($this->clienteData->data->data ?? [] as  $value) { ?>
            <tr>
                <td><?= $value->nome_membro ?? '' ?></td>
                <td><?= $value->email ?? '' ?></td>
                <td><?= $value->telefone ?? '' ?></td>
                <td><?= $value->saldoKz_actual ?? '' ?></td>
                <td><?= $value->saldoKz_gasto ?? '' ?></td>
                <td><?= $value->total_sms ?? '' ?></td>
                <td><?= $value->total_enviado ?? '' ?></td>
                <td><?= $value->senha_member ?? '' ?></td>

                <td>
                    <span class="btn btn-danger btn-sm" id="delete<?= $value->id ?>" onclick="deletamembro('<?= $value->id ?>','<?= $this->authCsrf ?>')"><i class="fas fa-trash"></i></span>
                    <button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#modal-default<?= $value->id ?? '' ?>"><i class="fas fa-pen-nib"></i></button>
                </td>
            </tr>

            <!-- /////////////////////////////////////////////////////////////////////////////////// -->
            <div class="modal fade" id="modal-default<?= $value->id ?>">
                <div class="modal-dialog ">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title">EDITAR CLIENTE </h4>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="card">
                                <div class="card-body register-card-body">

                                    <div id="messagem"></div>

                                    <form method="post" accept="image/*" name="from_publicacao<?= $value->id ?>" class="mf_form_validate<?= $value->id ?> ajax_submit<?= $value->id ?>" enctype="multipart/form-data">
                                        <div class="row">
                                            <div class="col-lg-12 col-12">
                                                <div class="form-group">
                                                    <label>NOME DO MEMBRO</label>
                                                    <input type="text" name="nome_membro<?= $value->id ?? '' ?>" id="nome_membro<?= $value->id ?? '' ?>" class="form-control" value="<?= $value->nome_membro ?>" placeholder="NOME DO MEMBRO">
                                                    <div class="input-group mb-2 form-group" id="erronome_membro<?= $value->id ?? '' ?>">
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-lg-12 col-12">
                                                <div class="form-group">
                                                    <label>TELEFONE DO MEMBRO</label>
                                                    <input type="number" name="telefone<?= $value->id ?? '' ?>" id="telefone<?= $value->id ?? '' ?>" class="form-control" value="<?= $value->telefone ?? '' ?>" placeholder="Número DO MEMBRO">
                                                    <div class="input-group mb-2 form-group" id="errotelefone<?= $value->id ?? '' ?>">
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-lg-12 col-12">
                                                <div class=" form-group">
                                                    <label>EMAIL DO MEMBRO</label>
                                                    <input type="email" name="email_membro<?= $value->id ?? '' ?>" id="email_membro<?= $value->id ?? '' ?>" class="form-control" value="<?= $value->email ?>" placeholder="EMAIL DO MEMBRO">
                                                    <div class="input-group mb-2 form-group" id="erroemail_membro<?= $value->id ?? '' ?>">
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="col-lg-12 col-12">
                                                <div class="form-group">
                                                    <label>SENHA DE ACESSO</label>
                                                    <input type="text" name="password<?= $value->id ?? '' ?>" id="password<?= $value->id ?? '' ?>" class="form-control" value="<?= $value->senha_member ?>" placeholder="SENHA DE ACESSO">
                                                    <div class="input-group mb-2 form-group" id="erropassword<?= $value->id ?? '' ?>">
                                                    </div>
                                                </div>
                                            </div>


                                        </div>

                                        <input type="hidden" name="token" id="token<?= $value->id ?>" class="form-control" value="<?= $this->authCsrf ?>">

                                        <div class="row">
                                            <!-- /.col -->
                                            <div class="col-4">
                                                <button type="button" class="btn btn-primary btn-block" onclick="membroeditar(<?= $value->id ?>)" id="register<?= $value->id ?>">EDITAR</button>
                                            </div>
                                            <!-- /.col -->
                                        </div>
                                    </form>
                                </div>
                                <!-- /.form-box -->
                            </div><!-- /.card -->
                        </div>
                        <div class="modal-footer justify-content-between">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>
        <?php } ?>
        <!-- end for -->
    </tbody>
    <tfoot>
        <tr>
            <th>Nome</th>
            <th>Email</th>
            <th>PHONE</th>
            <th>Sald Actual</th>
            <th>Sald gasto</th>
            <th>SMS DISP</th>
            <th>SMS ENVD</th>
            <th>Senha</th>
            <th>Acção</th>
        </tr>
    </tfoot>
</table>

<div class="float-md-right align-content-center">
    <nav aria-label="Page navigation example" class="">
        <ul class="pagination">
            <?php foreach ($this->clienteData->data->links ?? [] as  $value) {

                $itemarray = explode('page=', $value->url ?? '');
                //$item = explode('=', $itemarray[1] ?? '');
            ?>
                <li class="page-item <?= $value->active ? 'active' : '' ?>">
                    <a class="page-link" href="#" onclick="getMember('<?= $itemarray[1] ?? '' ?>')"><?= $value->label ?></a>
                </li>
            <?php } ?>


        </ul>
    </nav>
</div>
<input type="hidden" id="activado" value="<?= $this->clienteData->totalActive ?? '' ?>">
