<div class="wrapper">



    <!-- Navbar --> <!-- inicio menu top -->

    <?php include_once("menu_center.phtml"); ?>

    <!-- /.navbar -->

    <?php include_once("menu_lateral.phtml"); ?>

    <div class="content-wrapper">

        <!-- Content Header (Page header) -->

        <div class="content-header">

            <div class="container-fluid">

                <div class="row mb-2">

                    <div class="col-sm-6">

                        <h1 class="m-0">Dashboard</h1>

                    </div>

                    <div class="col-sm-6">

                        <ol class="breadcrumb float-sm-right">

                            <li class="breadcrumb-item"><a href="#">Home</a></li>

                            <li class="breadcrumb-item active">Dashboard</li>

                        </ol>

                    </div>

                </div>

            </div>

        </div>



        <!-- Main content -->

        <section class="content">

            <div class="container-fluid">

                <!-- Small boxes (Stat box) -->

                <?php include_once("cards.phtml"); ?>

                <div class="row">

                    <section class="col-lg-12 connectedSortable">

                        <div class="row">

                            <div class="col-md-12">

                                <div class="card card-primary card-outline">

                                    <div class="card-header">

                                        <h3 class="card-title">

                                            <i class="far fa-chart-bar"></i>
                                            Quantidade de entregas de mes
                                        </h3>
                                        <button type="button" class="btn btn-tool" data-card-widget="collapse">

                                            <i class="fas fa-minus"></i>

                                        </button>

                                        <div class="card-tools">



                                            <div class="col-12 col-sm-12 col-md-12">
                                                <div class="input-group form-group mr-4">
                                                    <select class="form-control p-2 select2" style="width: 100%;" name="Year" id="Year" onchange="getYear(this.value)">
                                                        <option selected="selected" value="<?= date('Y') ?>">ESCOLHER ANO</option>
                                                        <option value="<?= date('Y') ?>"><?= date('Y') ?></option>
                                                        <option value="<?= date('Y') - 1 ?>"><?= date('Y') - 1 ?></option>
                                                        <option value="<?= date('Y') - 2 ?>"><?= date('Y') - 2 ?></option>
                                                    </select>
                                                </div>
                                            </div>

                                        </div>

                                    </div>

                                    <div class="card-body">
                                    <div id="sales-chart" style="height: 300px;"></div>
                                      <!--   <div id='data_sms' class="text-center">
                                            <div class="d-flex justify-content-center">
                                                <div class="spinner-border text-primary" style="width: 50px; height: 50px;" role="status">
                                                    <span class="visually-hidden"></span>
                                                </div>
                                            </div>
                                        </div> -->

                                    </div>

                                    <!-- /.card-body-->
                                    <input type="hidden" name="token" id="token" class="form-control" value="<?= $this->authCsrf ?>">
                                </div>

                            </div>

                            <!-- /.col -->

                        </div>

                    </section>

                </div>

            </div>

        </section>

    </div>

    <?php include_once("footer_info.phtml"); ?>


    <!-- Control Sidebar -->

    <aside class="control-sidebar control-sidebar-dark">

        <!-- Control sidebar content goes here -->

    </aside>

    <!-- /.control-sidebar -->

</div>

<!-- ./wrapper -->

<script>
    if (!!(window.addEventListener)) window.addEventListener('DOMContentLoaded', main);
    else window.attachEvent('onload', main);

    function main() {
        if (localStorage.getItem("theme") == 1) {
            $('body').addClass('dark-mode')
        }
        //getYear(<?= date('Y') ?>)

    }


</script>


<script>
    $(function() {
        'use strict'

        var ticksStyle = {
            fontColor: '#495057',
            fontStyle: 'bold'
        }

        var mode = 'index'
        var intersect = true

        var $salesChart = $('#sales-chart')
        // eslint-disable-next-line no-unused-vars
        var salesChart = new Chart($salesChart, {
            type: 'bar',
            data: {
                labels: ['JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DECss'],
                datasets: [{
                        backgroundColor: '#007bff',
                        borderColor: '#007bff',
                        data: [1000, 2000, 3000, 2500, 2700, 2500, 30]
                    },
                    {
                        backgroundColor: '#ced4da',
                        borderColor: '#ced4da',
                        data: [700, 1700, 2700, 2000, 1800, 1500, 2000]
                    }
                ]
            },
            options: {
                maintainAspectRatio: false,
                tooltips: {
                    mode: mode,
                    intersect: intersect
                },
                hover: {
                    mode: mode,
                    intersect: intersect
                },
                legend: {
                    display: false
                },
                scales: {
                    yAxes: [{
                        // display: false,
                        gridLines: {
                            display: true,
                            lineWidth: '4px',
                            color: 'rgba(0, 0, 0, .2)',
                            zeroLineColor: 'transparent'
                        },
                        ticks: $.extend({
                            beginAtZero: true,

                            // Include a dollar sign in the ticks
                            /* callback: function (value) {

                              if (value >= 9000) {
                                value /= 1000
                                value += 'k'
                              }

                              return '$' + value
                            } */
                        }, ticksStyle)
                    }],
                    xAxes: [{
                        display: true,
                        gridLines: {
                            display: false
                        },
                        ticks: ticksStyle
                    }]
                }
            }
        })
    })
</script>
