<?php include_once("menu_center.phtml"); ?>
<!-- /.navbar -->
<?php include_once("menu_lateral.phtml"); ?>

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Meus Grupos</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/my_send_sms">ENVIAR SMS</a></li>
                        <li class="breadcrumb-item active">CARTEIRA</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <div class="align-content-lg-between  animate__animated animate__bounceIn">
        <div class="card-footer ">
            <a class="btn btn-app bg-success " data-toggle="modal" data-target="#modal-default">
                <i class="fas fa-plus"></i> NOVO
            </a>
        </div>
    </div>


    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h3 class="card-title">MEUS GRUPOS</h3>

                        <div class="card-tools">
                            <div class="input-group input-group-sm">
                                <input type="text" class="form-control" name="pesquisar" id="pesquisar" value="<?= $_SESSION['pesquisar'] ?? '' ?>" onchange="getGrupo()" placeholder="contacto ...">
                                <div class="input-group-append">
                                    <div class="btn btn-primary"  type="button" id="buscar" onclick="getGrupo()">
                                        <i class="fas fa-search"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-tools -->
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body p-0">

                        <div class="table-responsive mailbox-messages">
                            <div class="card-body">
                                <div id='grupos'>
                                    <div class="d-flex justify-content-center">
                                        <div class="spinner-border text-primary" style="width: 50px; height: 50px;" role="status">
                                            <span class="visually-hidden"></span>
                                        </div>
                                    </div>
                                </div>
                                <!--  {{ $dados['data']->links('vendor.pagination.bootstrap-5') }}-->
                            </div>
                        </div>
                        <!-- /.mail-box-messages -->
                    </div>
                    <!-- /.card-body -->

                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>

        <div class="modal fade" id="modal-default">

            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content ">
                    <div class="modal-header">
                        <h4 class="modal-title">NOVO GRUPO</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body animate__animated animate__bounceIn">
                        <div class="row">
                            <!-- left column -->
                            <div class="col-md-12 animate__animated animate__slideInLeft">
                                <!-- jquery validation -->
                                <div class="card card-primary">

                                    <form method="post" accept="image/*" name="from_membro" class="mf_form_validate_grupo ajax_submit_grupo" action="/createGrupo" enctype="multipart/form-data">
                                        <div class="card-body">
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <div class="form-group">
                                                        <label>NOME GRUPO</label>
                                                        <input type="text" name="nome_grupo" id="nome_grupo" class="form-control" placeholder="NOVO GRUPO">
                                                        <div class="input-group mb-2 form-group" id="erronome">
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-md-12">
                                                    <div class="form-group">
                                                        <label>NOME GRUPO</label>
                                                        <textarea name="descricao" id="descricao" cols="10" rows="5" class="form-control" placeholder="descrição"></textarea>
                                                        <div class="input-group mb-2 form-group" id="erronome">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <input type="hidden" name="token" id="token" class="form-control" value="<?= $this->authCsrf ?>">
                                        <div class="modal-footer justify-content-between">
                                            <button type="submit" class="btn btn-primary btn-block" id="register">GRAVAR</button>
                                        </div>
                                    </form>
                                </div>
                                <!-- /.card -->
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer justify-content-between">

                        <button type="button" class="btn btn-danger" data-dismiss="modal">CANCELAR</button>

                    </div>
                </div>
                <!-- /.modal-content -->
            </div>
            <!-- /.modal-dialog -->
        </div>


    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
<?php include_once("footer_info.phtml"); ?>

<style>
    .componente {
        float: right;
        /* faz o componente flutuar à direita */
        clear: both;
        /* garante que o componente não fique ao lado de outros elementos flutuantes */
        margin-top: 10px;
        /* define a margem superior para que o componente fique abaixo dos elementos anteriores */
    }
</style>

<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
</aside>
<!-- /.control-sidebar -->




<script>
    if (!!(window.addEventListener)) window.addEventListener('DOMContentLoaded', main);
    else window.attachEvent('onload', main);

    function main() {
        if (localStorage.getItem("theme") == 1) {
            $('body').addClass('dark-mode')
        }
        $(function() {
            //Enable check and uncheck all functionality
            $('.checkbox-toggle').click(function() {
                var clicks = $(this).data('clicks')
                if (clicks) {
                    //Uncheck all checkboxes
                    $('.mailbox-messages input[type=\'checkbox\']').prop('checked', false)
                    $('.checkbox-toggle .far.fa-check-square').removeClass('fa-check-square').addClass('fa-square')
                } else {
                    //Check all checkboxes
                    $('.mailbox-messages input[type=\'checkbox\']').prop('checked', true)
                    $('.checkbox-toggle .far.fa-square').removeClass('fa-square').addClass('fa-check-square')
                }
                $(this).data('clicks', !clicks)
            })

            //Handle starring for font awesome
            $('.mailbox-star').click(function(e) {
                e.preventDefault()
                //detect type
                var $this = $(this).find('a > i')
                var fa = $this.hasClass('fa')

                //Switch states
                if (fa) {
                    $this.toggleClass('fa-star')
                    $this.toggleClass('fa-star-o')
                }
            })
        })
        getGrupo();

    }
</script>

    <!-- Page specific script -->
    <script>

    </script>
