<?php include_once("menu_center.phtml"); ?>
<!-- /.navbar -->
<?php include_once("menu_lateral.phtml"); ?>

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h5 class="m-0">SOLICITAÇÃO DE CARREGAMENTO</h5>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="">CLIENTES</a></li>
                        <li class="breadcrumb-item active">CARREGAR CONTA</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->

            <div class="row animate__animated animate__heartBeat">
                <?php include_once("cardsolicitacao.phtml"); ?>
            </div>
            <!-- /.card-body -->

            <div class="align-content-lg-between animate__animated animate__bounceIn">
                <div class="card-footer ">
                    <a class="btn btn-app bg-success componente" data-toggle="modal" data-target="#modal-default">
                        <i class="fas fa-plus"></i> CRIAR NOVO PEDIDO
                    </a>
                </div>
            </div>

        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">

            <div class="row">
                <div class="col-12 ">
                    <div class="card  card-primary card-outline">
                        <div class="card-header">

                            <h3 class="card-title">

                                <i class="far fa-chart-bar"></i>
                                SOLICITAÇÕE DE CARREGAMENTOS
                            </h3>
                            <button type="button" class="btn btn-tool" data-card-widget="collapse">

                                <i class="fas fa-minus"></i>

                            </button>

                            <div class="card-tools">
                                <div class="col-12 col-sm-12 col-md-12">
                                    <div class="input-group form-group">
                                        <input type="text"  name="pesquisar" id="pesquisar" onchange="getCarregamento()" class="form-control" placeholder="nome...">
                                        <div class="input-group-append">
                                            <div class="input-group-text">
                                                <a class=" cursor-pointer" type="button" id="buscar" onclick="getCarregamento()">
                                                    <span class="fas fa-search"></span>
                                                </a>
                                            </div>
                                        </div>

                                    </div>
                                </div>

                            </div>

                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <div id='carregamento'>
                                <div class="d-flex justify-content-center">
                                    <div class="spinner-border text-primary" style="width: 50px; height: 50px;" role="status">
                                        <span class="visually-hidden"></span>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->


                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>


            <div class="modal fade" id="modal-default">

                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content ">
                        <div class="modal-header">
                            <h4 class="modal-title">CARREGAR CONTA</h4>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="row">
                                <!-- left column -->
                                <div class="col-md-12 animate__animated animate__slideInLeft">
                                    <!-- jquery validation -->
                                    <div class="card card-primary">

                                        <form method="post" name="from_carregamento" class="mf_form_validate_carregamento ajax_submit_carregamento" action="/createsolictacao" enctype="multipart/form-data">
                                            <div class="card-body">
                                                <div class="row">
                                                    <div class="col-md-12">
                                                        <div class="form-group">
                                                            <label for="exampleInputPassword1">
                                                                FORNEÇA O VALOR TRANSFERIDO (AKz)
                                                            </label>
                                                            <input type="number" name="amount_kz" id="amount_kz" class="form-control" placeholder="FORNEÇA O VALOR TRANSFERIDO (AKz)">

                                                        </div>
                                                    </div>
                                                    <div class="col-md-12">
                                                        <div class="form-group">
                                                            <label>FORNEÇA O COMPROVATIVO</label>
                                                            <input type="file" name="comprovativo" id="comprovativo" class="form-control" accept="application/pdf, image/*">
                                                            <div class="input-group mb-2 form-group" id="errocomprovativo_pacote">
                                                            </div>

                                                        </div>
                                                    </div>
                                                    <div class="col-md-12">
                                                        <div class="form-group">
                                                            <label> FORNEÇA UMA NOTA</label>
                                                            <input type="text" name="nota" id="nota" class="form-control" placeholder="NOTA DE CARREGAMENTO">
                                                            <div class="input-group mb-2 form-group" id="erroqtduser_pacote">
                                                            </div>

                                                        </div>
                                                    </div>

                                                </div>
                                                <small class="text-success">Beneficiário: <?= $_SESSION['BENEFICIARIO_SISTEMA_ZUMU']  ?? '' ?></small><br>
                                                <small class="text-success">IBAN: <?= $_SESSION['IBAN_SISTEMA_ZUMU']   ?? '' ?></small>
                                            </div>

                                            <input type="hidden" name="token" id="token" class="form-control" value="<?= $this->authCsrf ?>">

                                            <div class="modal-footer justify-content-between">
                                                <button type="submit" class="btn btn-primary btn-block" id="createpedido">SOLICITAR</button>
                                            </div>
                                        </form>

                                    </div>
                                    <!-- /.card -->
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer justify-content-between">

                            <button type="button" class="btn btn-danger" data-dismiss="modal">CANCELAR</button>

                        </div>
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>




        </div>
        <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>

<?php include_once("footer_info.phtml"); ?>

<style>
    .componente {
        float: right;
        /* faz o componente flutuar à direita */
        clear: both;
        /* garante que o componente não fique ao lado de outros elementos flutuantes */
        margin-top: 10px;
        /* define a margem superior para que o componente fique abaixo dos elementos anteriores */
    }
</style>


<script>
    if (!!(window.addEventListener)) window.addEventListener('DOMContentLoaded', main);
    else window.attachEvent('onload', main);

    function main() {
        if (localStorage.getItem("theme") == 1) {
            $('body').addClass('dark-mode')
        }
        getCarregamento();

    }
</script>
