<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?= $_SESSION['NOME_SISTEMA'] ?? '' ?> | Dashboard</title>

    <link href="<?= API_URL_LOGO . "" . $_SESSION['LOGO_SISTEMA'] ?? '' ?>" rel="icon">
    <link href="<?= API_URL_LOGO . "" . $_SESSION['LOGO_SISTEMA'] ?? '' ?>" rel="apple-touch-icon">
    <link rel="shortcut icon" href="<?= API_URL_LOGO . "" . $_SESSION['LOGO_SISTEMA'] ?? '' ?>" type="image/x-icon">
    <link rel="manifest" href="<?= $this->urlcaminho ?>/manifest.json">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="theme-color" content="#ffffff">

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="dist/css/adminlte.min.css">
    <link rel="stylesheet" href="plugins/overlayScrollbars/css/OverlayScrollbars.min.css">

</head>

<body class="hold-transition sidebar-mini layout-fixed">
    <?= $this->content() ?>

    <!-- jQuery -->
    <script src="plugins/jquery/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="plugins/jquery-ui/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <!-- Bootstrap 4 -->
    <script src="plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- ChartJS -->

    <script src="plugins/sparklines/sparkline.js"></script>
    <!-- JQVMap -->
    <!-- overlayScrollbars -->
    <script src="plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE App -->
    <script src="dist/js/adminlte.js"></script>

    <!-- AdminLTE for demo purposes -->
    <script src="dist/js/demo.js"></script>

    <script src="assets/js/plugins/jquery.validate.min.js"></script>

    <script src="assets/js/main.js"></script>
    <script src="assets/functions/mf_form.js"></script>
    <!-- Toastr -->
    <script src="plugins/toastr/toastr.min.js"></script>
    <script src="plugins/sweetalert2/sweetalert2.min.js"></script>
    <!-- FLOT CHARTS -->
    <script src="<?= $this->urlcaminho ?>plugins/flot/jquery.flot.js"></script>
    <!-- FLOT RESIZE PLUGIN - allows the chart to redraw when the window is resized -->
    <script src="<?= $this->urlcaminho ?>plugins/flot/plugins/jquery.flot.resize.js"></script>
    <!-- FLOT PIE PLUGIN - also used to draw donut charts -->
    <script src="<?= $this->urlcaminho ?>plugins/flot/plugins/jquery.flot.pie.js"></script>
    <script src="dist/js/GetdataSms.js"></script>
</body>
<script>
    $(function() {
        /* END AREA CHART */

        /*
         * BAR CHART
         * ---------
         */

        var bar_data = {
            data: [
                <?php for ($i = 1; $i <= 12; $i++) { ?>[parseInt(<?= intval($i) ?>), parseInt(<?= intval($this->total_do_ano[$i]) ?>)],
                <?php  } ?>
            ],
            bars: {
                show: true
            }
        }
        $.plot('#bar-chart', [bar_data], {
            grid: {
                borderWidth: 1,
                borderColor: '#f3f3f3',
                tickColor: '#f3f3f3'
            },
            series: {
                bars: {
                    show: true,
                    barWidth: 0.5,
                    align: 'center',
                },
            },
            colors: ['#3c8dbc'],
            xaxis: {
                ticks: [
                    [1, 'Janeiro'],
                    [2, 'Fevereiro'],
                    [3, 'Marco'],
                    [4, 'Abril'],
                    [5, 'Maio'],
                    [6, 'Junho'],
                    [7, 'Julho'],
                    [8, 'Agosto'],
                    [9, 'Setembro'],
                    [10, 'Outubro'],
                    [11, 'Novembro'],
                    [12, 'Dezembro']
                ]
            }
        })
        /* END BAR CHART */
    })
</script>
<script>
    if ('serviceWorker' in navigator) {
        window.addEventListener('load', function() {

            navigator.serviceWorker.register('/sw.js').then(function(registration) {
                console.log('Service Worker registered with scope: ', registration.scope);
            }, function(err) {
                console.error('Service Worker registration failed: ', err);
            });

        });
    }
</script>

</html>
