<!DOCTYPE html>

<html lang="en">

<head>

    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title><?= $_SESSION['NOME_SISTEMA']??''?> | Log in</title>

    <!-- Google Font: Source Sans Pro -->

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">

    <!-- Font Awesome -->

    <link rel="stylesheet" href="<?= $this->urlcaminho ?>plugins/fontawesome-free/css/all.min.css">

    <!-- icheck bootstrap -->

    <link rel="stylesheet" href="<?= $this->urlcaminho ?>plugins/icheck-bootstrap/icheck-bootstrap.min.css">

    <!-- Theme style -->

    <link rel="stylesheet" href="<?= $this->urlcaminho ?>dist/css/adminlte.min.css">

    <link rel="stylesheet" href="<?= $this->urlcaminho ?>plugins/select2/css/select2.min.css">

    <link rel="stylesheet" href="<?= $this->urlcaminho ?>plugins/fontawesome-free/css/all.min.css">

    <!-- Theme style -->

    <link rel="stylesheet" href="<?= $this->urlcaminho ?>dist/css/adminlte.min.css">

    <link rel="stylesheet" href="plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css">

    <!-- Toastr -->

    <link rel="stylesheet" href="plugins/toastr/toastr.min.css">


    <!-- Favicon -->
    <link rel="icon" type="image/png" sizes="32x32" href="<?= API_URL_LOGO . "" . $_SESSION['LOGO_SISTEMA'] ?? '' ?>">


</head>

<style>
    body {
        background-color: #151F32 !important;
    }
</style>

<body class="hold-transition login-page">





    <?= $this->content() ?>





    <!-- /.login-box -->



    <!-- jQuery -->

    <script src="<?= $this->urlcaminho ?>plugins/jquery/jquery.min.js"></script>

    <!-- Bootstrap 4 -->

    <script src="<?= $this->urlcaminho ?>plugins/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- AdminLTE App -->

    <script src="<?= $this->urlcaminho ?>dist/js/adminlte.min.js"></script>

    <script src="<?= $this->urlcaminho ?>dist/js/registar.js"></script>

    <script src="<?= $this->urlcaminho ?>dist/js/login.js"></script>

    <script src="<?= $this->urlcaminho ?>dist/js/forgotpassword.js"></script>

    <script src="<?= $this->urlcaminho ?>plugins/jquery-validation/jquery.validate.min.js"></script>

    <script src="<?= $this->urlcaminho ?>plugins/jquery-validation/additional-methods.min.js"></script>



    <script src="plugins/sweetalert2/sweetalert2.min.js"></script>

    <!-- Toastr -->

    <script src="plugins/toastr/toastr.min.js"></script>

    <script src="dist/js/sweetalert2.min.js"></script>

    <!-- AdminLTE for demo purposes -->

    <!-- Page specific script -->



</body>



</html>

