 <!-- Small boxes (Stat box) -->

 <div class="col-lg-6 col-12">
     <!-- small box -->
     <div class="small-box bg-info">
         <div class="inner">
             <h3 id="activeValue">0</h3>
             <p>TOTAL DE SMS</p>
         </div>
         <div class="icon">
             <i class="fas fa-inbox"></i>
         </div>
         <a href="#" class="small-box-footer"> <i class="fas fa-arrow-circle-right"></i></a>
     </div>
 </div>
 <!-- ./col -->
 <div class="col-lg-6 col-12">
     <!-- small box -->
     <div class="small-box bg-purple">
         <div class="inner">
             <h3 id="restantesSmsMostrar">0</h3>
             <p>TOTAL DE GASTO</p>
         </div>
         <div class="icon">
             <i class="fas fa-file-invoice"></i>
         </div>
         <a href="#" class="small-box-footer"> <i class="fas fa-arrow-circle-right"></i></a>
     </div>
 </div>
