 <!-- Small boxes (Stat box) -->
 <div class="row">


     <div class="col-lg-4 col-12">
         <!-- small box -->
         <div class="small-box bg-info">
             <div class="inner">
                 <h3  id="total_item">0</h3>

                 <p>Carrinho Total</p>
             </div>
             <div class="icon">
                 <i class="ion ion-bag"></i>
             </div>
         </div>
     </div>

     <div class="col-lg-4 col-12">
         <!-- small box -->
         <div class="small-box bg-info">
             <div class="inner">
                 <h3><?=count($this->servicos??[])?></h3>

                 <p>TOTAL DE SERVIÇOS</p>
             </div>
             <div class="icon">
                 <i class="ion ion-bag"></i>
             </div>
         </div>
     </div>
     <div class="col-lg-4 col-12">
         <!-- small box -->
         <div class="small-box bg-info">
             <div class="inner">
                 <h3><?=count($this->produtos??[])?></h3>

                 <p>TOTAL DE PRODUTOS</p>
             </div>
             <div class="icon">
                 <i class="ion ion-bag"></i>
             </div>
         </div>
     </div>
     <!-- ./col -->


 </div>
