 <!-- Small boxes (Stat box) -->

     <div class="col-lg-6 col-12">
         <!-- small box -->
         <div class="small-box bg-info">
             <div class="inner">
                 <h3 id="activeValue">0</h3>
                 <p>Activos</p>
             </div>
             <div class="icon">
                 <i class="fas fa-inbox"></i>
             </div>
         </div>
     </div>
     <!-- ./col -->
     <div class="col-lg-6 col-12">
         <!-- small box -->
         <div class="small-box bg-info">
             <div class="inner">
                 <h3 id="restantesSmsMostrar">0</h3>
                 <p>Feitos</p>
             </div>
             <div class="icon">
                 <i class="fas fa-file-invoice"></i>
             </div>
         </div>
     </div>


