<!--
    {
        "id": 12,
        "nome_membro": "Rodrigues 34",
        "telefone": "923898844",
        "email": "mechackantonio23@gmail.com",
        "regular_price": "3.00",
        "typeOperacao": 1
      }
 -->


<table id="example1" class="table table-bordered table-striped">
    <thead>

        <tr>
            <th>Nome</th>
            <th>PHONE</th>
            <th>PACOTE SMS</th>
            <th>TOTAL SMS</th>
            <th>OPERAÇÃO</th>
            <th>DATA</th>
            <th>VER</th>
        </tr>

    </thead>
    <tbody id="corpo_institucional">
        <!-- for $this->category -->
        <?php foreach ($this->clienteData->data->data ?? [] as  $value) { ?>
            <tr>
                <td><?= $value->name ?? '' ?></td>
                <td><?= $value->phone ?? '' ?></td>
                <td><?= $value->nomepacote ?? '' ?></td>
                <td><?= $value->regular_price ?? '' ?></td>
                <td><?= $value->typeOperacao ? '<small class="text-muted text-danger">SAIDA</small> ' : '<small class=" text-success">ENTRADA</small>' ?></td>
                <td>
                    <?= $value->created_at ?? 0 ?></td>
                </td>
                <td>
                    <a href="#" type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal-default<?= $value->id ?? '' ?>"><i class="fas fa-expand"></i></a>
                </td>
            </tr>

            <div class="modal fade" id="modal-default<?= $value->id ?? '' ?>">

                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content ">
                        <div class="modal-header">
                            <h4 class="modal-title">DETALHES DO ENVIO</h4>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="row">
                                <!-- left column -->
                                <div class="col-md-12 animate__animated animate__slideInLeft">
                                    <!-- jquery validation -->
                                    <div class="card card-primary">
                                        <form>
                                            <div class="card-body">
                                                <div class="row">
                                                    <div class="col-md-12">
                                                        <div class="form-group">
                                                            <span class="text-muted">MENSAGEN: <?= $value->regular_price ?? '' ?>SMS</span><br>
                                                            <span class="text-muted">CLIENTE: <?= $value->nome_membro ?? '' ?></span>

                                                        </div>
                                                    </div>
                                                </div>
                                            </div>

                                        </form>
                                    </div>
                                    <!-- /.card -->
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer justify-content-between">

                            <button type="button" class="btn btn-danger" data-dismiss="modal">CANCELAR</button>

                        </div>
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>

        <?php } ?>
        <!-- end for -->
    </tbody>
    <tfoot>
        <tr>
            <th>Nome</th>
            <th>PHONE</th>
            <th>PACOTE SMS</th>
            <th>TOTAL SMS</th>
            <th>OPERAÇÃO</th>
            <th>DATA</th>
            <th>VER</th>
        </tr>
    </tfoot>
</table>

<div class="float-md-right align-content-center">
    <nav aria-label="Page navigation example" class="">
        <ul class="pagination">
            <?php foreach ($this->clienteData->data->links ?? [] as  $value) {

                $itemarray = explode('page=', $value->url ?? '');
                //$item = explode('=', $itemarray[1] ?? '');
            ?>
                <li class="page-item <?= $value->active ? 'active' : '' ?>">
                    <a class="page-link" href="#" onclick="getOperationvenda('<?= $itemarray[1] ?? '' ?>')"><?= $value->label ?></a>
                </li>
            <?php } ?>


        </ul>
    </nav>
</div>


<input type="hidden" id="total_de_venda" value="<?= $this->clienteData->activadoSsms ?? 0 ?>">
<input type="hidden" id="total_sms_venda" value="<?= $this->clienteData-> restantesSms?? '0' ?>">
