
<footer class="main-footer">
    ©
    <a href="https://<?= $_SESSION['NOME_DOMINIO'] ?? '' ?>"><?= $_SESSION['NOME_SISTEMA'] ?? '' ?>.</a></strong>
    <div class="float-right d-none d-sm-inline-block">
        <b class="mr-2">Suporte: <?= $_SESSION['NOME_TELEFONE'] ?? '' ?> </b> <b>Version</b> 0.2.1
    </div>
</footer>
<aside class="control-sidebar control-sidebar-dark">

<!-- Control sidebar content goes here -->

</aside>
