    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <!-- Brand Logo -->
        <a href="/" class="brand-link">
            <img src="<?= API_URL_LOGO . "" . $_SESSION['LOGO_SISTEMA'] ?? '' ?>" alt="<?= $_SESSION['NOME_SISTEMA'] ?? '' ?>" class="brand-image img-circle " style="opacity: .8">
            <span class="brand-text font-weight-light"><?= $_SESSION['NOME_SISTEMA'] ?? '' ?></span>
        </a>

        <!-- Sidebar -->
        <div class="sidebar">
            <!-- Sidebar user panel (optional) -->
            <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                <div class="image">
                    <img src="dist/icons/perfil.png" class="img-circle elevation-2" alt="User Image">
                </div>
                <div class="info">
                    <a href="/user_profile" class="d-block"><?= $_SESSION['nameUser'] ?></a>
                </div>
            </div>

            <!-- SidebarSearch Form -->
            <div class="form-inline">
                <div class="input-group" data-widget="sidebar-search">
                    <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
                    <div class="input-group-append">
                        <button class="btn btn-sidebar">
                            <i class="fas fa-search fa-fw"></i>
                        </button>
                    </div>
                </div>
            </div>

            <!-- Sidebar Menu -->
            <nav class="mt-2">
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                    <!-- Add icons to the links using the .nav-icon class
             with font-awesome or any other icon font library -->
                    <li class="nav-item ">
                        <a href="/dashboard" class="nav-link" id="dashboard" onclick="menuActive(this.id);">
                            <i class="nav-icon fas fa-tachometer-alt"></i>
                            <p>
                                INICIO
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="/my_send_sms" class="nav-link" id="my_send_sms" onclick="menuActive(this.id);">
                            <i class="nav-icon fas fa-inbox"></i>
                            <p>
                                 MENSAGENS
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="/my_sender" class="nav-link" id="my_sender" onclick="menuActive(this.id);">
                            <i class="nav-icon fas fa-user"></i>
                            <p>
                                SENDER ID
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="/my_pacotes_sms" class="nav-link" id="my_pacotes_sms" onclick="menuActive(this.id);">
                            <i class="nav-icon fas fa-check"></i>
                            <p>
                                COMPRAR SMS
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="/my_solitation_card" class="nav-link" id="my_solitation_card" onclick="menuActive(this.id);">
                            <i class="nav-icon fas fa-wallet"></i>
                            <p>
                                CARTEIRA (AKZ)
                            </p>
                        </a>
                    </li>


                    <li class="nav-item">
                        <a href="/my_vendas_sms" class="nav-link" id="my_vendas_sms" onclick="menuActive(this.id);">
                            <i class="nav-icon fas fa-chart-bar"></i>
                            <p>
                            COMPRA DE SMS
                            </p>
                        </a>
                    </li>


                </ul>
            </nav>
            <!-- /.sidebar-menu -->
        </div>
        <!-- /.sidebar -->
    </aside>


    <script>
        function menuActive(id) {

            localStorage.setItem("idMenu", id);
        }
        let idMenu = localStorage.getItem("idMenu");
        /*         if (idMenu == 'perfil' || idMenu == 'logo')
                    idMenu = 'dashboard' */
        document.getElementById(idMenu).classList.add("active");
    </script>
