<!-- inicio menu top -->
<?php include_once "menu_center.phtml";?>
<!-- /.navbar -->
<?php include_once "menu_lateral.phtml";?>
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">


            <div class="row animate__animated animate__heartBeat">
                <?php include_once "cardsSendSmsAgendas.phtml";?>
            </div>
            <!-- /.card-body -->

            <div class="align-content-lg-between animate__animated animate__bounceIn">
                <div class="card-footer ">
                    <a class="btn btn-app bg-success componente" href="/my_send_sms" >
                        <i class="fas fa-plus"></i> Enviar sms
                    </a>
                </div>
            </div>

        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">

            <div class="row">
                <div class="col-12 ">
                    <div class="card  card-primary card-outline">

                        <div class="card-header">

                            <h3 class="card-title">

                                <i class="far fa-chart-bar"></i>
                                Mensagens
                            </h3>
                            <button type="button" class="btn btn-tool" data-card-widget="collapse">

                                <i class="fas fa-minus"></i>

                            </button>

                            <div class="card-tools">



                                <div class="col-12 col-sm-12 col-md-12">
                                    <div class="input-group form-group">

                                        <input type="text" name="pesquisar" id="pesquisar" value="<?=$_SESSION['pesquisar'] ?? ''?>" onchange="getOperation()" class="form-control" placeholder="Mensagem">
                                        <div class="input-group-append">
                                            <div class="input-group-text">
                                                <a class="cursor-pointer" type="button" id="buscar" onclick="getOperation()">
                                                    <span class="fas fa-search"></span>
                                                </a>

                                            </div>
                                        </div>

                                    </div>
                                </div>

                            </div>

                        </div>

                        <!-- /.card-header -->
                        <div class="card-body">
                            <div id='Operation'>
                                <div class="d-flex justify-content-center">
                                    <div class="spinner-border text-primary" style="width: 50px; height: 50px;" role="status">
                                        <span class="visually-hidden"></span>
                                    </div>
                                </div>
                            </div>
                            <!--  {{ $dados['data']->links('vendor.pagination.bootstrap-5') }}-->
                        </div>
                    </div>
                </div>
                <!-- /.col -->
            </div>

            <!-- //////////////////////////////////////////// -->

        </div>
    </section>
    <!-- /////////////////////////////////////////////////////////////////////////////////// -->
</div>
<input type="hidden" name="token" id="token" class="form-control" value="<?=$this->authCsrf?>">
<?php include_once "footer_info.phtml";?>

<script>
    if (!!(window.addEventListener)) window.addEventListener('DOMContentLoaded', main);
    else window.attachEvent('onload', main);

    function main() {
        if (localStorage.getItem("theme") == 1) {
            $('body').addClass('dark-mode')
        }
        getOperation();
    }



</script>

<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->

</aside>
<!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->
