<div class="content-wrapper">
    <!-- Content Header (Page header) -->

    <!-- Navbar -->
    <!-- inicio menu top -->
    <?php include_once("menu_center.phtml"); ?>
    <!-- /.navbar -->
    <?php include_once("menu_lateral.phtml"); ?>

    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0">SENDER</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">

                            <li class="breadcrumb-item active">SENDER</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <!-- Small boxes (Stat box) -->
                <?php include_once("cardsSender.phtml"); ?>

                <div class="row">
                    <section class="col-lg-12 connectedSortable">
                        <button type="button" class="btn btn-default bg-dark mb-2" data-toggle="modal" data-target="#modal-default">
                            CRIAR NOVA SENDER
                        </button>
                        <div class="col-lg-12 mt-4">

                            <div class="row">
                                <div class="col-lg-12 col-12 ">
                                    <div class="input-group form-group">
                                        <div class="col-lg-4 form-group">
                                            <input type="text" name="pesquisar" id="pesquisar" onkeyup="getBuscarSender()" class="form-control" placeholder="Nome sender">
                                        </div>
                                        <div class="col-lg-2 form-group">
                                            <button type="submit" class="btn btn-primary btn-block" id="buscar" onclick="getBuscarSender()">Pesquiar</button>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div id='sender' class="text-center">
                                <div class="d-flex justify-content-center">
                                    <div class="spinner-border text-primary" style="width: 50px; height: 50px;" role="status">
                                        <span class="visually-hidden"></span>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </section>
                </div>
            </div>
        </section>

        <!-- /////////////////////////////////////////////////////////////////////////////////// -->
        <div class="modal fade" id="modal-default">
            <div class="modal-dialog ">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">NOVO SENDER</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="card">
                            <div class="card-body register-card-body">

                                <div id="messagem"></div>

                                <form method="post" accept="image/*" name="from_publicacao" class="mf_form_validate_obr ajax_submit_obr" action="/creteObreiros" enctype="multipart/form-data">

                                    <div class="row">
                                        <div class="col-lg-12 col-12">
                                            <label>NOME SENDER ID</label>
                                            <div class="input-group form-group">
                                                <div class="col-md-12 form-group">
                                                    <div class="form-group  ">
                                                        <input type="text" name="nome_sender" id="token" class="form-control" value="" maxlength="11">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <!-- /.col -->
                                    </div>

                                    <input type="hidden" name="token" id="token" class="form-control" value="<?= $this->authCsrf ?>">
                                    <div class="row">
                                        <!-- /.col -->
                                        <div class="col-4">
                                            <button type="submit" class="btn btn-primary btn-block" id="register">CRIAR</button>
                                        </div>
                                        <!-- /.col -->
                                    </div>
                                </form>
                            </div>
                            <!-- /.form-box -->
                        </div><!-- /.card -->
                    </div>
                    <div class="modal-footer justify-content-between">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

                    </div>
                </div>
                <!-- /.modal-content -->
            </div>
            <!-- /.modal-dialog -->
        </div>
        

    </div>
    <?php include_once("footer_info.phtml"); ?>

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->

    </aside>
    <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<script>
    if (!!(window.addEventListener)) window.addEventListener('DOMContentLoaded', main);
    else window.attachEvent('onload', main);

    function main() {
        getSender();
    }
</script>
