<div class="wrapper">

    <!-- Navbar -->
    <!-- inicio menu top -->
    <?php include_once("menu_center.phtml"); ?>
    <!-- /.navbar -->
    <?php include_once("menu_lateral.phtml"); ?>
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0">Solicitações</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item active">Solicitações</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">

                <div class="row">
                    <section class="col-lg-12 connectedSortable">
                        <!-- Main content -->
                        <section class="content">
                            <div class="row">

                                <section class="col-lg-12 connectedSortable">
                                    <h6 id="tipo_de_tabela">Solicitações</h6>
                                    <hr>
                                    <div id="">
                                        <input type="hidden" name="token_tabela" id="token_tabela" class="form-control" value="<?= $this->authCsrf ?>">
                                        <table id="example1" class="table table-bordered table-striped example1_lede example_conf">
                                            <thead>
                                                <tr id="tr_change">
                                                    <th>#</th>
                                                    <th>Nome do Produto</th>
                                                    <th>Imagem</th>
                                                    <th>Quantidade</th>
                                                    <th> Preço por pagar</th>
                                                    <th>Acção</th>
                                                </tr>

                                            </thead>
                                            <tbody id="corpo_institucional">

                                                <!-- for $this->category -->
                                                <?php foreach ($this->itens ?? [] as $key => $value) { ?>
                                                    <tr>
                                                        <td><?= $value['id'] ?? '' ?></td>
                                                        <td><?= $value['nome_servico'] ?? '' ?></td>
                                                        <td> <img alt="imagem " class="table-avatar" width="50" src="assets/img/usuarios/igrejas/<?= $value['imagem'] ?? '' ?>"></td>
                                                        <td>
                                                            <div class="progress progress-sm">
                                                                <div class="progress-bar bg-green" role="progressbar" aria-valuenow="<?= $value['quantidade'] ?>" aria-valuemin="0" aria-valuemax="100" style="width: 57%">
                                                                </div>
                                                            </div>
                                                            <small>
                                                                <?= $value['quantidade_iten'] ?>% Complete
                                                            </small>
                                                        </td>
                                                        <td><?= $value['preco_total'] ?> KZ</td>
                                                        <td>
                                                            <a class="btn btn-primary btn-sm" href="/viewItemOne_sl?item=<?= $value['id'] ?? '' ?>">
                                                                <i class="fas fa-folder">
                                                                </i>
                                                                ver
                                                            </a>
                                                            <?php if ($value['estado_da_operacao'] == 0) { ?>
                                                                <a class="btn btn-danger btn-sm" id="btnstop<?= $value['id'] ?? '' ?>" onclick="itenStop(<?= $value['id'] ?? '' ?>,'<?= $this->authCsrf ?>')" id="btnAddrm<?= $value['id'] ?>">
                                                                    <i class="fas fa-stop">
                                                                    </i>
                                                                    Cancelar
                                                                </a>
                                                            <?php } else { ?>
                                                                <span class="text-info text-muted bold">
                                                                    <i class="fas fa-close">
                                                                    </i>
                                                                    Teminado
                                                                </span>
                                                            <?php  } ?>

                                                        </td>
                                                    </tr>
                                                <?php } ?>
                                                <!-- end for -->
                                            </tbody>
                                            <tfoot>
                                                <tr id="tr_change">
                                                    <th>#</th>
                                                    <th>Nome do Produto</th>
                                                    <th>Imagem</th>
                                                    <th>Quantidade</th>
                                                    <th> Preço por pagar</th>
                                                    <th>Acção</th>
                                                </tr>
                                            </tfoot>
                                        </table>
                                    </div>
                                </section>
                            </div>
                        </section>
                    </section>
                </div>
            </div>
        </section>
    </div>


    <!-- /////////////////////////////////////////////////////////////////////////////////// -->
    <div class="modal fade" id="modal-departamento">
        <div class="modal-dialog ">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">CRIAR NOVA DEPARTAMENTO </h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="card">
                        <div class="card-body register-card-body">
                            <div id="messagem"></div>
                            <form method="post" accept="image/*" name="from_departamento" id="quickFormCreateDepartamento" enctype="multipart/form-data">
                                <div class="row">
                                    <div class="col-lg-12 col-12">
                                        <div class="input-group mb-3 form-group">
                                            <input type="text" name="nome_departamento" id="nome_departamento" class="form-control" placeholder="INSIRA O NOME DO DEPARTAMENTO?">
                                            <div class="input-group-append">
                                                <div class="input-group-text">
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-lg-12 col-12">
                                        <div class="input-group mb-3 form-group">
                                            <input type="text" name="cargo_departamento" id="cargo_departamento" class="form-control" placeholder="FUNÇÃO DO  DEPARTAMETO ?">
                                            <div class="input-group-append">
                                                <div class="input-group-text">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-12 col-12">
                                        <div class="input-group form-group">
                                            <div class="col-md-12 form-group">
                                                <div class="form-group  ">
                                                    <select class="form-control p-2 id_igrejas_dp" style="width: 100%;" name="id_igrejas_dp" id="id_igrejas_dp">
                                                        <option selected="selected" value="">Para qual igreja ?</option>
                                                        <?php foreach ($this->igrejas as $value) { ?>
                                                            <option value="<?= $value['id'] ?>"><?= $value['nome_igrejas'] ?></option>
                                                        <?php } ?>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- /.col -->
                                </div>
                                <div class="row">
                                    <!-- /.col -->
                                    <div class="col-lg-12">
                                        <label>FOTO DO DEPARTAMETO</label>
                                        <div class="input-group mb-3 form-group">
                                            <div id="preview2"></div><br>
                                            <input type="file" name="imagem_principal" id="imagem_principal" class="form-control" placeholder="Imagem principal ?">
                                            <div class="input-group-append">
                                                <div class="input-group-text">
                                                </div>
                                            </div>
                                            <div id="err2"></div>
                                        </div>
                                    </div>
                                    <!-- /.col -->
                                </div>
                                <div class="row">

                                    <div class="col-lg-12 col-12">
                                        <div class="input-group mb-3 form-group">
                                            <div class="form-group col-lg-12">
                                                <label for="message-text" class="col-form-label">DESCRIÇÃO DO DEPARTAMENTO:</label>
                                                <textarea class="form-control" rows="15" id="message-text" name="descricao_departamento"></textarea>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- /.col -->
                                </div>

                                <input type="hidden" name="token" id="token" class="form-control" value="<?= $this->authCsrf ?>">
                                <div class="row">
                                    <!-- /.col -->
                                    <div class="col-4">
                                        <button type="submit" class="btn btn-primary btn-block" id="register_departamento">CRIAR</button>
                                    </div>
                                    <!-- /.col -->
                                </div>
                            </form>
                        </div>
                        <!-- /.form-box -->
                    </div><!-- /.card -->
                </div>
                <div class="modal-footer justify-content-between">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>


    <footer class="main-footer">
        © zumu_sms.
        <a href="https://zumu_sms.com">zumu_sms</a>.- Desenvolvido pela <a href="https://qlerius.com" class="text-dark">Qlerius</a> </strong>
        <div class="float-right d-none d-sm-inline-block">
            <b>Version</b> 3.2.0
        </div>
    </footer>

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->

    </aside>
    <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->
