 <!-- Small boxes (Stat box) -->

 <div class="col-lg-4 col-sm-12">
     <!-- small box -->
     <div class="small-box bg-info">
         <div class="inner">
             <h3 id="pendentes_Value">0</h3>
             <p>SOLICITAÇÃO</p>
         </div>
         <div class="icon">
             <i class="ion ion-bag"></i>
         </div>
     </div>
 </div>
 <!-- ./col -->
 <div class="col-lg-4 col-sm-12">
     <!-- small box -->
     <div class="small-box bg-gradient-success">
         <div class="inner">
             <h3 id="activados_Value">0</h3>

             <p>ACTIVADOS</p>
         </div>
         <div class="icon">
             <i class="ion ion-stats-bars"></i>
         </div>
     </div>
 </div>

 <div class="col-lg-4 col-sm-12">
     <!-- small box -->
     <div class="small-box bg-gradient-purple">
         <div class="inner">
             <h3 id="saldo_kz">0</h3>

             <p>SALDO (AKZ)</p>
         </div>
         <div class="icon">
             <i class="ion ion-stats-bars"></i>
         </div>
     </div>
 </div>
