<?php include_once("menu_center.phtml"); ?>
<!-- /.navbar -->
<?php include_once("menu_lateral.phtml"); ?>

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">ENVIPO DE SMS</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/">INICIO</a></li>
                        <li class="breadcrumb-item active"><a href="/my_send_sms" class="cursor-pointer">ENVIAR SMS</a></li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->

            <div class="row animate__animated animate__heartBeat">
                <?php include_once("cardsGestaoSms.phtml"); ?>
            </div>
            <!-- /.card-body -->


        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">

            <div class="row">
                <div class="col-12 ">
                    <div class="card  card-primary card-outline">
                        <div class="card-header">

                            <h3 class="card-title">

                                <i class="far fa-chart-bar"></i>
                                MOVIMENTOS DE MENSAGENS
                            </h3>
                            <button type="button" class="btn btn-tool" data-card-widget="collapse">

                                <i class="fas fa-minus"></i>

                            </button>

                            <div class="card-tools">

                                <div class="col-12 col-sm-12 col-md-12">
                                    <div class="input-group form-group">

                                        <input type="text" name="pesquisar" id="pesquisar" value="<?= $_SESSION['pesquisar'] ?? '' ?>" onchange="getOperation()" class="form-control" placeholder="Nome Cliente">
                                        <div class="input-group-append">
                                            <div class="input-group-text">
                                                <a class=" cursor-pointer" type="button" id="buscar" onclick="getOperation()">
                                                    <span class="fas fa-search"></span>
                                                </a>

                                            </div>
                                        </div>

                                    </div>
                                </div>

                            </div>

                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <div id='Operation'>
                                <div class="d-flex justify-content-center">
                                    <div class="spinner-border text-primary" style="width: 50px; height: 50px;" role="status">
                                        <span class="visually-hidden"></span>
                                    </div>
                                </div>
                            </div>
                            <!--  {{ $dados['data']->links('vendor.pagination.bootstrap-5') }}-->
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->


                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>

            <div class="modal fade" id="modal-default">

                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content ">
                        <div class="modal-header">
                            <h4 class="modal-title">ENVIAR SMS PARA CLIENTE</h4>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="row">
                                <!-- left column -->
                                <div class="col-md-12 animate__animated animate__bounceIn">
                                    <!-- jquery validation -->
                                    <div class="card card-primary">

                                        <form method="post" accept="image/*" name="from_membro" class="mf_form_validate_membro ajax_submit_membro" action="/creteOperationSms" enctype="multipart/form-data">
                                            <div class="card-body">
                                                <div class="row">
                                                    <div class="col-md-12">
                                                        <div class="form-group">
                                                            <label>EMAIL DO SEU CLIENTE</label>
                                                            <input type="email" name="email_user" id="email_user" class="form-control" placeholder="EMAIL DO SEU CLIENTE">
                                                            <div class="input-group mb-2 form-group" id="erroemail_user_pacote">
                                                            </div>
                                                        </div>
                                                    </div>

                                                    <div class="col-md-12">
                                                        <div class="form-group">
                                                            <label>QUANTIA DE SMS</label>
                                                            <input type="number" name="quantia_de_sms" id="quantia_de_sms" class="form-control" placeholder="QUANTIA DE SMS">
                                                            <div class="input-group mb-2 form-group" id="erroquantia_de_sms_pacote">
                                                            </div>
                                                        </div>
                                                    </div>

                                                    <div class="col-md-12">
                                                        <div class="form-group">
                                                            <label>TIPO DE OPERAÇÃO</label>
                                                            <select class="form-control p-2 " style="width: 100%;" name="typeopercao" id="typeopercao">
                                                                <option selected="selected" value="">TIPO DE OPERAÇÃO</option>
                                                                <option value="1" class="text-success">ENTRADA SMS</option>
                                                                <option value="0" class=" text-danger">SAIDA SMS</option>
                                                            </select>
                                                            <div class="input-group mb-2 form-group" id="errotypeopercao_pacote">
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <input type="hidden" name="token" id="token" class="form-control" value="<?= $this->authCsrf ?>">
                                            <div class="modal-footer justify-content-between">
                                                <button type="submit" class="btn btn-primary btn-block" id="register">CRIAR</button>
                                            </div>
                                        </form>
                                    </div>
                                    <!-- /.card -->
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer justify-content-between">

                            <button type="button" class="btn btn-danger" data-dismiss="modal">CANCELAR</button>

                        </div>
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>

        </div>
        <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>

<?php include_once("footer_info.phtml"); ?>

<style>
    .componente {
        float: right;
        /* faz o componente flutuar à direita */
        clear: both;
        /* garante que o componente não fique ao lado de outros elementos flutuantes */
        margin-top: 10px;
        /* define a margem superior para que o componente fique abaixo dos elementos anteriores */
    }
</style>


<script>
    if (!!(window.addEventListener)) window.addEventListener('DOMContentLoaded', main);
    else window.attachEvent('onload', main);

    function main() {
        if (localStorage.getItem("theme") == 1) {
            $('body').addClass('dark-mode')
        }
        getOperation();
    }
</script>

