<div class="wrapper">

    <!-- Navbar -->
    <!-- inicio menu top -->
    <?php include_once("menu_center.phtml"); ?>
    <!-- /.navbar -->
    <?php include_once("menu_lateral.phtml"); ?>
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0">SEND DE SMS</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item active">MENSAGEM</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <!-- Small boxes (Stat box) -->
                <?php include_once("cardsSendSms.phtml"); ?>

                <div class="row">
                    <div class="col-lg-6 col-6 mt-2">
                        <div class="input-group form-group">
                            <div class="col-md-12 form-group">
                                <div class="form-group " id="relatorioCrescimento">
                                </div>
                            </div>
                        </div>
                    </div>

                    <section class="col-lg-12 connectedSortable">
                        <button type="button" class="btn btn-default bg-dark mb-2" data-toggle="modal" data-target="#modal-default">
                            ENVIAR SMS
                        </button>

                        <div class="row">
                            <div class="col-lg-12 col-12 ">
                                <div class="input-group form-group">
                                    <div class="col-lg-4 form-group">
                                        <input type="text" name="pesquisar" id="pesquisar" value="<?= $_SESSION['pesquisar'] ?? '' ?>" onchange="getOperation()" class="form-control" placeholder="Nome Cliente">
                                    </div>
                                    <div class="col-lg-2 form-group">
                                        <button type="submit" class="btn btn-primary" id="buscar" onclick="getOperation()"><i class="fas fa-search"></i></button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-12 mt-2">
                            <div id='Operation' class="text-center">
                                <div class="d-flex justify-content-center">
                                    <div class="spinner-border text-primary" style="width: 50px; height: 50px;" role="status">
                                        <span class="visually-hidden"></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </section>
        <!-- /////////////////////////////////////////////////////////////////////////////////// -->
        <div class="modal fade" id="modal-default">

            <div class="modal-dialog ">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">ENVIAR MENSAGEM </h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="card">
                            <div class="card-body register-card-body">

                                <div id="messagem"></div>

                                <form method="post" accept="image/*" name="from_membro" class="mf_form_validate_send ajax_submit_send" action="/sendOperationSms" enctype="multipart/form-data">

                                    <div class="row">
                                        <div class="row">
                                            <div class="col-lg-6 col-md-6">
                                                <label>APLICAÇÃO DE ENVIO</label>
                                                <div class="input-group form-group">
                                                    <div class="col-md-12 form-group">
                                                        <select class="form-control p-2 select2" style="width: 100%;" name="id_sender" id="id_sender">
                                                            <option selected="selected" value="">SELECIONAR</option>
                                                        </select>
                                                    </div>
                                                    <div class="input-group mb-2 form-group" id="erroid_sender">
                                                    </div>
                                                </div>
                                            </div>


                                            <div class="col-lg-6 col-md-6">
                                                <label>ENVIO EM MASSA: ( .xslx )</label>
                                                <div class="input-group form-group">
                                                    <div class="col-lg-12 form-group">
                                                        <input type="file" name="file" id="file" class="form-control" placeholder="">

                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="col-lg-12 col-md-12">
                                            <label>DESTINATARIO</label>
                                            <div class="input-group form-group">
                                                <div class="col-lg-12 form-group">
                                                    <input type="text" name="number_phone" id="number_phone" class="form-control" placeholder="ex: 9xxxxxxxx, 9xxxxxxxx, 9xxxxxxxx">
                                                    <div class="input-group mb-2 form-group" id="erronumber_phone">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="col-12">
                                            <label>CORPO DA MENSAGEM</label>
                                            <div class="input-group form-group">
                                                <div class="col-lg-12 form-group">
                                                    <textarea type="text" name="message_body" id="message_body" rows="5" class="form-control" placeholder="CORPO DA MENSAGEM"></textarea>
                                                    <div class="input-group mb-2 form-group" id="erromessage_body">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <input type="hidden" name="token" id="token" class="form-control" value="<?= $this->authCsrf ?>">
                                    <div class="row">
                                        <!-- /.col -->
                                        <div class="col-4">
                                            <button type="submit" class="btn btn-primary btn-block" id="register">CRIAR</button>
                                        </div>
                                        <!-- /.col -->
                                    </div>
                                </form>
                            </div>
                            <!-- /.form-box -->
                        </div><!-- /.card -->
                    </div>
                    <div class="modal-footer justify-content-between">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

                    </div>
                </div>
                <!-- /.modal-content -->
            </div>
            <!-- /.modal-dialog -->
        </div>
    </div>

    <?php include_once("footer_info.phtml"); ?>

    <script>
        if (!!(window.addEventListener)) window.addEventListener('DOMContentLoaded', main);
        else window.attachEvent('onload', main);

        function main() {
            if (localStorage.getItem("theme") == 1) {
                $('body').addClass('dark-mode')
            }
            getOperation();
            getsender_Operation()
            //
        }
    </script>
</div>
<!-- ./wrapper -->
