<div class="wrapper">

    <!-- Navbar -->
    <!-- inicio menu top -->
    <?php include_once("menu_center.phtml"); ?>
    <!-- /.navbar -->
    <?php include_once("menu_lateral.phtml"); ?>
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0">Publicações</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item active">Publicações</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <!-- Small boxes (Stat box) -->
                <?php include_once("cardsservicos.phtml"); ?>
                <div class="row">
                    <section class="col-lg-12 connectedSortable">
                        <!--  -->
                        <h5 class="mb-2">MEUS SERVIÇOS</h5>
                        <a href="/viewItemCard" class="btn btn-default bg-dark mb-2">
                            MEU CARRINHO
                        </a>
                        <div class=" container ">
                            <span class="d-lg-block text-danger display-5 bold">ITEM <span class="d-lg-block text-danger display-4 font-weight-900" id="total_item1"> 0</span></span>
                        </div>
                        <div class="card card-success">

                            <div class="col">
                                <div class="card-body">

                                    <h6>SERVIÇOS</h6>
                                    <hr>
                                    <div class="row">

                                        <?php foreach ($this->servicos ?? [] as $value) { ?>
                                            <div class="col-md-3">
                                                <div class="card card-outline card-primary">
                                                    <div class="card-header">
                                                        <h3 class="card-title"><?= $value['nome_servico'] ?></h3>
                                                        <img src="/assets/img/usuarios/igrejas/<?= $value['imagem'] ?>" class="product-image" alt="Product Image">
                                                        <div class="card-tools">
                                                            <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                                                <i class="fas fa-minus"></i>
                                                            </button>
                                                        </div>
                                                        <!-- /.card-tools -->
                                                    </div>
                                                    <!-- /.card-header -->
                                                    <div class="card-body">
                                                        <div class="card-footer p-0">
                                                            <ul class="nav flex-column">

                                                                <li class="nav-item">
                                                                    <a href="#" class="nav-link">
                                                                        PREÇO: <span class="float-right badge bg-info"><?= number_format($value['preco_servico'], 2, ",", ".") ?? '' ?> Kz</span>
                                                                    </a>
                                                                </li>
                                                                <div id="total_intemOne<?= $value['id'] ?? '' ?>">

                                                                </div>
                                                                <!--  <li class="nav-item">
                                                                    <a href="#" class="nav-link">
                                                                        Nº SOLICITAÇÕES <span class="float-right badge bg-danger">842</span>
                                                                    </a>
                                                                </li> -->

                                                                <li class="nav-item">
                                                                    <span class="btn btn-block btn-dark btn-sm" id="btnAdd<?= $value['id'] ?? '' ?>" onclick="addItem(<?= $value['id'] ?? '' ?>,'<?= $this->authCsrf ?>')">ADD CARD</span>
                                                                </li>
                                                                <li class="nav-item">
                                                                    <a href="/viewItemOne?item=<?= $value['id'] ?? '' ?>" class="btn btn-block btn-info btn-sm">ver</a>
                                                                </li>

                                                            </ul>
                                                        </div>
                                                    </div>
                                                    <!-- /.card-body -->
                                                </div>
                                                <!-- //////////////////////////// Editar/////////////////////////////////////////////////////// -->

                                            </div>
                                        <?php } ?>
                                    </div>
                                </div>

                                <div class="card-body">

                                    <h6>PRODUTOS</h6>
                                    <hr>
                                    <div class="row">
                                        <?php foreach ($this->produtos ?? [] as $value) { ?>
                                            <div class="col-md-3">
                                                <div class="card card-outline card-primary">
                                                    <div class="card-header">
                                                        <h3 class="card-title"><?= $value['nome_servico'] ?></h3>
                                                        <img src="/assets/img/usuarios/igrejas/<?= $value['imagem'] ?>" class="product-image" alt="Product Image">
                                                        <div class="card-tools">
                                                            <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                                                <i class="fas fa-minus"></i>
                                                            </button>
                                                        </div>
                                                        <!-- /.card-tools -->
                                                    </div>
                                                    <!-- /.card-header -->
                                                    <div class="card-body">
                                                        <div class="card-footer p-0">
                                                            <ul class="nav flex-column">

                                                                <li class="nav-item">
                                                                    <a href="#" class="nav-link">
                                                                        PREÇO: <span class="float-right badge bg-info"><?= number_format($value['preco_servico'], 2, ",", ".") ?? '' ?> Kz</span>
                                                                    </a>
                                                                </li>
                                                                <div id="total_intemOne<?= $value['id'] ?? '' ?>">

                                                                </div>
                                                                <li class="nav-item">
                                                                    <span class="btn btn-block btn-dark btn-sm" id="btnAdd<?= $value['id'] ?? '' ?>" onclick="addItem(<?= $value['id'] ?? '' ?>,'<?= $this->authCsrf ?>')">ADD CARD</span>
                                                                </li>
                                                                <li class="nav-item">
                                                                    <a href="/viewItemOne?item=<?= $value['id'] ?? '' ?>" class="btn btn-block btn-info btn-sm">ver</a>
                                                                </li>

                                                            </ul>
                                                        </div>
                                                    </div>



                                                    <!-- /.card-body -->
                                                </div>
                                                <!-- /.card -->
                                            </div>
                                        <?php } ?>
                                    </div>
                                </div>
                            </div>
                        </div><!-- /.container-fluid -->
                    </section>
                </div>
            </div>
        </section>
    </div>






    <footer class="main-footer">
        © zumu_sms.
        <a href="https://zumu_sms.com">zumu_sms</a>.- Desenvolvido pela <a href="https://qlerius.com" class="text-dark">Qlerius</a> </strong>
        <div class="float-right d-none d-sm-inline-block">
            <b>Version</b> 3.2.0
        </div>
    </footer>

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->

    </aside>
    <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->
