 <!-- Small boxes (Stat box) -->

     <div class="col-lg-6 col-12">
         <!-- small box -->
         <div class="small-box bg-info">
             <div class="inner">
                 <h3 id="activeValue">0</h3>
                 <p>MEUS CLIENTES</p>
             </div>
             <div class="icon">
                 <i class="ion ion-bag"></i>
             </div>
         </div>
     </div>
     <!-- ./col -->
     <div class="col-lg-6 col-12">
         <!-- small box -->
         <div class="small-box bg-info">
             <div class="inner">
                 <h3><sup style="font-size: 20px"></sup></h3>

                 <p>CRIAR CLIENTES</p>
             </div>
             <div class="icon">
                 <i class="ion ion-stats-bars"></i>
             </div>
             <button type="button" class="btn btn-default" data-toggle="modal" data-target="#modal-default">
                 CRIAR AGORA
             </button>
         </div>
     </div>

