<div class="mailbox-controls">
    <!-- Check all button -->
    <button type="button" class="btn btn-default btn-sm checkbox-toggle"><i class="far fa-square"></i>
    </button>
    <div class="btn-group">
        <button type="button" class="btn btn-default btn-sm" onclick="selecionados()">
            <i class="far fa-trash-alt"></i>
        </button>

    </div>
    <!-- /.btn-group -->
    <button type="button" class="btn btn-default btn-sm" onclick="getContacto()">
        <i class="fas fa-sync-alt"></i>
    </button>

    <!-- /.float-right -->
</div>

<table id="example1" class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>#</th>
            <th>NOME</th>
            <th>TELEFONE</th>
            <th>EMAIL</th>
            <th>Data</th>
            <th>Acção</th>
        </tr>
    </thead>
    <?php foreach ($this->clienteData->data->data ?? [] as $value) {?>
        <tr>
            <td>
                <div class="icheck-primary">
                    <input type="checkbox" value="<?=$value->id?>" id="check<?=$value->id?>">
                    <label for="check<?=$value->id?>"></label>
                </div>
            </td>

            <td class="mailbox-name"><a href="#"><?=$value->nome?></a></td>
            <td class="mailbox-subject"><b><?=$value->numero_telefone?></b>
            </td>
            <td class="mailbox-subject d-none  d-lg-block "> <b><?=$value->email?></b>
            </td>
            <td class="mailbox-subject "> <?php
if (!empty($value->created_at)) {
    $dateTime = new DateTime($value->created_at);
    $formattedDate = $dateTime->format('d/m/Y H:i:s');
    echo $formattedDate;
} else {
    echo $value->created_at;
}
?>


 </td>
            <td class="mailbox-subject text-center">
                <button type="button" class="btn btn-default btn-sm" data-toggle="modal" data-target="#modal-edit<?=$value->id?>">
                    <i class="fas fa-pencil-alt"></i>
                </button>
            </td>

        </tr>

        <div class="modal fade" id="modal-edit<?=$value->id?>">

            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content ">
                    <div class="modal-header">
                        <h4 class="modal-title">EDITAR CONTACTO</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body animate__animated animate__bounceIn">
                        <div class="row">
                            <!-- left column -->
                            <div class="col-md-12 animate__animated animate__slideInLeft">
                                <!-- jquery validation -->
                                <div class="card card-primary">

                                    <form method="post" accept="image/*" enctype="multipart/form-data">
                                        <div class="card-body">
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <div class="form-group">
                                                        <label>NOME CONTACTO</label>
                                                        <input type="text" name="nome_contacto<?=$value->id?>" id="nome_contacto<?=$value->id?>" class="form-control" value="<?=$value->nome ?? ''?>" placeholder="NOME CONTACTO">
                                                        <div class="input-group mb-2 form-group" id="erronome<?=$value->id?>">
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-md-12">
                                                    <div class="form-group">
                                                        <label>TELEFONE</label>
                                                        <input type="number" name="telefone<?=$value->id?>" id="telefone<?=$value->id?>" class="form-control" value="<?=$value->numero_telefone ?? ''?>" placeholder="TELEFONE">
                                                        <div class="input-group mb-2 form-group" id="errotelefone<?=$value->id?>">
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-md-12">
                                                    <div class="form-group">
                                                        <label>EMAIL DO SEU CLIENTE</label>
                                                        <input type="email" name="email_contacto<?=$value->id?>" id="email_contacto<?=$value->id?>" class="form-control" value="<?=$value->email ?? ''?>" placeholder="EMAIL DO SEU CLIENTE">
                                                        <div class="input-group mb-2 form-group" id="erroemail_contacto<?=$value->id?>">
                                                        </div>
                                                    </div>
                                                </div>

                                            </div>
                                        </div>
                                        <input type="hidden" name="token<?=$value->id?>" id="token<?=$value->id?>" class="form-control" value="<?=$this->authCsrf?>">
                                        <div class="modal-footer justify-content-between">
                                            <button type="submit" class="btn btn-primary btn-block" id="Editar<?=$value->id?>" onclick="Contactoeditar(<?=$value->id?>)">Editar</button>
                                        </div>
                                    </form>
                                </div>
                                <!-- /.card -->
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer justify-content-between">

                        <button type="button" class="btn btn-danger" data-dismiss="modal">CANCELAR</button>

                    </div>
                </div>
                <!-- /.modal-content -->
            </div>
            <!-- /.modal-dialog -->
        </div>
    <?php }?>
    </tbody>
</table>
<!-- /.table -->
<div class="card-footer p-0">
    <div class="mailbox-controls">
        <!-- Check all button -->
        <button type="button" class="btn btn-default btn-sm checkbox-toggle">
            <i class="far fa-square"></i>
        </button>
        <div class="btn-group">
            <button type="button" class="btn btn-default btn-sm">
                <i class="far fa-trash-alt"></i>
            </button>
        </div>
        <!-- /.btn-group -->
        <button type="button" class="btn btn-default btn-sm" onclick="getContacto()">
            <i class="fas fa-sync-alt"></i>
        </button>
        <div class="float-right">
            <?=$this->clienteData->data->from ?? 0?>-<?=$this->clienteData->data->to ?? 0?>/<?=$this->clienteData->data->total ?? 0?>

            <?php foreach ($this->clienteData->data->links ?? [] as $value) {

    $itemarray = explode('page=', $value->url ?? '');
    //$item = explode('=', $itemarray[1] ?? '');
    ?>
                <div class="btn-group">
                    <!--<button type="button" class="btn btn-default btn-sm" onclick="getOperation('<?=$itemarray[1] ?? ''?>')">
                        <i class="fas fa-chevron-left"></i>
                    </button> -->
                    <button type="button" class="btn btn-sm <?=$value->active ? 'btn-primary' : 'btn-default'?> " onclick="getContacto('<?=$itemarray[1] ?? ''?>')">
                        <?=$value->label?>
                    </button>
                    <!--<button type="button" class="btn btn-default btn-sm">
                        <i class="fas fa-chevron-right"></i>
                    </button> -->
                </div>
            <?php }?>
            <!-- /.btn-group -->
        </div>
        <!-- /.float-right -->
    </div>
</div>
