  <!-- Content Wrapper. Contains page content -->

  <!-- Main content -->
  <section class="content">
      <!-- Default box -->
      <div class="card card-solid">
          <div class="card-body pb-0">
              <div class="row">
                  <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch flex-column">
                      <div class="card bg-light d-flex flex-fill">
                          <div class="card-header text-muted border-bottom-0">
                              PACOTE NOME
                          </div>
                          <div class="card-body pt-0">
                              <div class="row">
                                  <div class="col-7">
                                      <h2 class="lead"><b>MÓDULO COMERCIAL</b></h2>
                                      <p class="text-muted text-sm"><b>IDEAL: </b>PARA MAIS DE 46 NEGÓCIOS</p>
                                      <ul class="ml-4 mb-0 fa-ul text-muted">
                                          <li class="small"><span class="fa-li"><i class="fas fa-lg fa-building"></i></span> SERVIÇOS WEB</li>
                                          <li class="small"><span class="fa-li"><i class="fas fa-lg fa-phone"></i></span>SUPORTE: + 923 696 938</li>
                                      </ul>
                                  </div>
                                  <div class="col-5 text-center">
                                      <img src="{{asset('dist/img/COMERCIAL.png')}}" alt="COMERCIAL" class="img-circle img-fluid">
                                  </div>
                              </div>
                          </div>
                          <div class="card-footer">
                              <div class="text-right">

                                  <a href="{{route('comercial.dashboard')}}" class="btn btn-sm btn-primary">
                                      <i class="fas fa-user"></i> Selecionar
                                  </a>
                              </div>
                          </div>
                      </div>
                  </div>

              </div>
          </div>

      </div>
      <!-- /.card -->
