<div class="wrapper">



    <!-- Navbar --> <!-- inicio menu top -->

    <?php include_once("menu_center.phtml"); ?>

    <!-- /.navbar -->

    <?php include_once("menu_lateral.phtml"); ?>

    <div class="content-wrapper">

        <!-- Content Header (Page header) -->

        <div class="content-header">

            <div class="container-fluid">

                <div class="row mb-2">

                    <div class="col-sm-6">

                        <h1 class="m-0">Dashboard</h1>

                    </div>

                    <div class="col-sm-6">

                        <ol class="breadcrumb float-sm-right">

                            <li class="breadcrumb-item"><a href="#">Home</a></li>

                            <li class="breadcrumb-item active">Dashboard</li>

                        </ol>

                    </div>

                </div>

            </div>

        </div>



        <!-- Main content -->

        <section class="content">

            <div class="container-fluid">

                <!-- Small boxes (Stat box) -->

                <?php include_once("cards.phtml"); ?>

                <div class="row">

                    <section class="col-lg-12 connectedSortable">

                        <div class="row">

                            <div class="col-md-12">

                                <div class="card card-primary card-outline">

                                    <div class="card-header">

                                        <h3 class="card-title">

                                            <i class="far fa-chart-bar"></i>
                                            Quantidade de entregas de <?php
                                                                        $mesAtual = date('n');
                                                                        $formatador = new IntlDateFormatter('pt_AO', IntlDateFormatter::LONG, IntlDateFormatter::NONE);
                                                                        $mesExtenso = $formatador->format(new DateTime(date('Y')."-$mesAtual-".date('d')));
                                                                        echo $mesExtenso;?>

                                        </h3>
                                        <button type="button" class="btn btn-tool" data-card-widget="collapse">

                                            <i class="fas fa-minus"></i>

                                        </button>

                                        <div class="card-tools">



                                            <div class="col-12 col-sm-12 col-md-12">
                                                <div class="input-group form-group mr-4">
                                                    <select class="form-control p-2 select2" style="width: 100%;" name="Year" id="Year" disabled onchange="getYear(this.value)">
                                                        <option selected="selected" value="<?= date('Y') ?>">ESCOLHER ANO</option>
                                                        <option value="<?= date('Y') ?>"><?= date('Y') ?></option>
                                                        <option value="<?= date('Y') - 1 ?>"><?= date('Y') - 1 ?></option>
                                                        <option value="<?= date('Y') - 2 ?>"><?= date('Y') - 2 ?></option>
                                                    </select>
                                                </div>
                                            </div>

                                        </div>

                                    </div>

                                    <div class="card-body" id="data_sms">

                                        <div id="bar-chart" style="height: 300px;"></div>

                                    </div>

                                    <div class="card-body d-none" id="data2022">

                                        <div id="bar-chart" style="height: 300px;"></div>

                                    </div>

                                    <div class="card-body d-none" id="data2021">

                                        <div id="bar-chart" style="height: 300px;"></div>

                                    </div>

                                    <!-- /.card-body-->

                                </div>

                            </div>

                            <!-- /.col -->

                        </div>

                    </section>

                </div>

            </div>

        </section>

    </div>

    <?php include_once("footer_info.phtml"); ?>


    <!-- Control Sidebar -->

    <aside class="control-sidebar control-sidebar-dark">

        <!-- Control sidebar content goes here -->



    </aside>

    <!-- /.control-sidebar -->

</div>

<!-- ./wrapper -->

<script>
    if (!!(window.addEventListener)) window.addEventListener('DOMContentLoaded', main);
    else window.attachEvent('onload', main);

    function main() {
        if (localStorage.getItem("theme") == 1) {
            $('body').addClass('dark-mode')
        }
    }

    function getCurrentMonth() {
        const date = new Date();
        const month = date.getMonth();

        // Adicione 1 ao valor do mês, pois ele é baseado em zero
        return month + 1;
    }
</script>
