<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>zumu_sms</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="../../plugins/fontawesome-free/css/all.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="../../dist/css/adminlte.min.css">
</head>

<body>
    <div class="wrapper">
        <!-- Main content -->
        <section class="invoice">
            <!-- title row -->
            <div class="row">
                <div class="col-12">
                    <h2 class="page-header">
                        <i class="fas fa-globe"></i> zumu_sms, Inc.
                        <small class="float-right">Date: 2/10/2014</small>
                    </h2>
                </div>

            </div>
            <!-- info row -->
          <!--   <div class="row invoice-info">
                <div class="col-sm-4 invoice-col">
                    From
                    <address>
                        <strong>Admin, Inc.</strong><br>
                        795 Folsom Ave, Suite 600<br>
                        San Francisco, CA 94107<br>
                        Phone: (804) 123-5432<br>
                        Email: info@almasaeedstudio.com
                    </address>
                </div>

                <div class="col-sm-4 invoice-col">
                    To
                    <address>
                        <strong>John Doe</strong><br>
                        795 Folsom Ave, Suite 600<br>
                        San Francisco, CA 94107<br>
                        Phone: (555) 539-1037<br>
                        Email: john.doe@example.com
                    </address>
                </div>

                <div class="col-sm-4 invoice-col">
                    <b>Invoice #007612</b><br>
                    <br>
                    <b>Order ID:</b> 4F3S8J<br>
                    <b>Payment Due:</b> 2/22/2014<br>
                    <b>Account:</b> 968-34567
                </div>

            </div> -->
            <!-- /.row -->

            <!-- Table row -->
            <div class="row">
                <div class="col-12 table-responsive">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>

                            <tr>
                                <th>Nome do Membro</th>

                            </tr>

                        </thead>
                        <tbody id="corpo_institucional">
                            <!-- for $this->category -->
                            <div class="col-md-12">
                                <div class="row">
                                    <th class="row">
                                        <?php foreach ($this->membros ?? [] as $value) { ?>
                                            <div class="col-md-4">
                                                <div class="credit-card-box" style="top:0px;position: relative;">
                                                    <div class="flip">
                                                        <div class="front">
                                                            <div class="chip">
                                                                <img src="assets/img/usuarios/igrejas/<?= $value['foto_membro'] ?? '' ?>" width="80" alt="zumu_sms cartões de membros">
                                                            </div>
                                                            <div class="logo">
                                                                <img src="assets/img/logotipo/semfundo/logo.png" width="70" />
                                                            </div>
                                                            <div class="number" style="font-size: 1.2rem;"> Igreja: <span class="text-dark"><?= $value["nome_igrejas"] ?? 'Inativo' ?></span> | Número: <?= $value["id"] ?? 'Inativo' ?></div>
                                                            <div class="card-holder">
                                                                <label>Titular Do Cartão</label>
                                                                <div><?= $value["nome_membro"] ?? 'Inativo' ?> </div>
                                                            </div>
                                                            <div class="card-expiration-date">
                                                                <label>Idades</label>
                                                                <div><?php

                                                                        $data = new \DateTime($value['date_nascimento_tempo'] ?? '');
                                                                        $inicio_date = date("d-m-Y H:i:s");
                                                                        $tempo_anterior = new \DateTime($inicio_date); // data do ultimos clique
                                                                        $intervalo = $data->diff($tempo_anterior);
                                                                        echo $intervalo->y ?></div>
                                                            </div>
                                                        </div>
                                                        <!-- Parte de tras do cartão -->
                                                        <div class="back">
                                                            <div class="strip"></div>
                                                            <div class="logo">
                                                                <img src="assets/img/logotipo/semfundo/logo.png" width="50" />
                                                            </div>
                                                            <div class="ccv">
                                                                <div><?= ($value['estado_de_vida']) ? 'EM VIDA' : 'FALECIDO' ?></div>
                                                            </div>
                                                        </div>
                                                        <!-- Fim da parte de tras -->
                                                    </div>
                                                </div>
                                            </div>
                                        <?php } ?>
                                    </th>
                                </div>
                            </div>
                            <!-- end for -->
                        </tbody>
                        <tfoot>
                            <tr>
                                <th>Nome do Membro</th>
                            </tr>
                        </tfoot>

                    </table>
                </div>

            </div>
            <!-- /.row -->
            <div class="row">
                <!-- accepted payments column -->

            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
    <!-- ./wrapper -->
    <!-- Page specific script -->
    <script>
        window.addEventListener("load", window.print());
    </script>
</body>

</html>
