<div class="wrapper">

    <!-- Navbar -->
    <!-- inicio menu top -->
    <?php include_once("menu_center.phtml"); ?>
    <!-- /.navbar -->
    <?php include_once("menu_lateral.phtml"); ?>
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0">Configuração-Sistema</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">

                            <li class="breadcrumb-item active">Configuração-<?= $this->configuracao->dataEmpresa->nome_sistema ?? '' ?></li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">

                <div class="row">
                    <section class="col-lg-12 connectedSortable">
                        <button type="button" class="btn btn-default bg-dark mb-2" data-toggle="modal" data-target="#modal-default">
                            VER OU EDITAR SISTEMA
                        </button>

                        <table id="example1" class="table table-bordered table-striped">
                            <thead>

                                <tr>
                                    <th>Nome</th>
                                    <th>Logo</th>
                                    <th>contactos</th>
                                    <th>Localização</th>
                                    <th>Hora de inicio</th>
                                    <th>Hora de termino</th>
                                    <th>Email</th>
                                    <th>SENDER GRÁTIS</th>
                                    <th>SLOGAN DO SISTEMA</th>
                                    <th>NIF</th>
                                </tr>

                            </thead>
                            <tbody>
                                <!-- for $this->category -->

                                <tr>
                                    <td><?= $this->configuracao->dataEmpresa->nome_sistema ?? '' ?></td>

                                    <td><img src="<?= API_URL_LOGO . "" . $_SESSION['LOGO_SISTEMA'] ?? '' ?>" alt="<?= $_SESSION['NOME_SISTEMA'] ?? '' ?>" class="brand-image img-circle " style="opacity: .8;" width="50"></td>
                                    <td><?= $this->configuracao->dataEmpresa->contacto ?? ''  ?></td>
                                    <td><?= $this->configuracao->dataEmpresa->endereco ?? '' ?></td>
                                    <td><?= $this->configuracao->dataEmpresa->hora_atendimento_inicio ?? '' ?></td>
                                    <td><?= $this->configuracao->dataEmpresa->hora_atendimento_termino ?? '' ?></td>
                                    <td><?= $this->configuracao->dataEmpresa->email ?? '' ?></td>
                                    <td><?= $this->configuracao->dataEmpresa->qtd_sender_grats ?? '' ?></td>
                                    <td><?= $this->configuracao->dataEmpresa->dica_sistema ?? '' ?></td>
                                    <td><?= $this->configuracao->dataEmpresa->nif ?? '' ?></td>
                                </tr>

                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>Nome</th>
                                    <th>Logo</th>
                                    <th>contactos</th>
                                    <th>Localização</th>
                                    <th>Hora de inicio</th>
                                    <th>Hora de termino</th>
                                    <th>Email</th>
                                    <th>SENDER GRÁTIS</th>
                                    <th>SLOGAN DO SISTEMA</th>
                                    <th>NIF</th>
                                </tr>

                            </tfoot>

                        </table>
                    </section>
                </div>
            </div>
        </section>

        <!-- /////////////////////////////////////////////////////////////////////////////////// -->
        <div class="modal fade animate__animated animate__bounceIn" id="modal-default">
            <div class="modal-dialog modal-xl ">
                <div class="modal-content">
                    <div class="modal-header">
                        <a class="cursor-pointer" type="button" id="buscar">
                            <img src="<?= API_URL_LOGO . "" . $_SESSION['LOGO_SISTEMA'] ?? '' ?>" alt="<?= $_SESSION['NOME_SISTEMA'] ?? '' ?>" class="brand-image img-circle " style="opacity: .8;" width="50">
                        </a>
                        <h4 class="modal-title ml-3">EDITAR EMPRESA</h4>

                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>

                    <div class="modal-body">
                        <div class="card card-primary">
                            <div class="card-body register-card-body">

                                <form method="post" accept="image/*" name="from_config" class="mf_form_validate ajax_submit" action="/creteConfg" enctype="multipart/form-data">

                                    <div class="row">
                                        <div class="col-lg-3 col-sm-12">
                                            <div class=" form-group">
                                                <label>NOME DO SISTEMA</label>
                                                <input type="text" name="nome_sistema" id="nome_sistema" class="form-control" value="<?= $this->configuracao->dataEmpresa->nome_sistema ?? '' ?? '' ?>" placeholder="NOME DO SISTEMA ?">
                                                <div class="input-group-append">
                                                </div>
                                            </div>
                                        </div>

                                        <div class="col-lg-3 col-sm-12">
                                            <div class="form-group">
                                                <label>E-mail</label>
                                                <input type="text" name="email" id="email" class="form-control" value="<?= $this->configuracao->dataEmpresa->email ?? '' ?>" placeholder="EMAIL DO SISTEMA ?">
                                                <div class="input-group-append">
                                                </div>
                                            </div>
                                        </div>

                                        <div class="col-lg-3 col-sm-12">
                                            <div class="form-group">
                                                <label>Logo da empresa</label>
                                                <input type="file" name="logo_sistema" id="logo_sistema" class="form-control" value="" placeholder="LOGO">
                                                <div class="input-group-append">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-3 col-12">
                                            <div class="col-lg-12 form-group">
                                                <label>CONTACTOS</label>
                                                <input type="number" name="contacto" id="contacto" value="<?= $this->configuracao->dataEmpresa->contacto ?? ''  ?>" class="form-control" placeholder="CONTACTOS ?">
                                                <div class="input-group-append">
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-lg-4 col-sm-12">
                                            <div class="form-group">
                                                <label>SENDER ID GRÁTIS <span><?= $this->configuracao->nome_sistem ?>: <?= $this->configuracao->qtd_sender_grats_zumu ?></span></label>
                                                <input type="number" name="qtd_sender_grats" id="qtd_sender_grats" class="form-control" value="<?= $this->configuracao->dataEmpresa->qtd_sender_grats ?? '' ?>" placeholder="QTD SENDER ID GRÁTIS">
                                                <div class="input-group-append">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-4 col-12">
                                            <div class="col-lg-12 form-group">
                                                <label> SENDER ID <?= $this->configuracao->nome_sistem ?>: <?= $this->configuracao->qtd_kz_sender_zumu ?></label>
                                                <input type="number" name="qtd_kz_sender" id="qtd_kz_sender" class="form-control" value="<?= $this->configuracao->dataEmpresa->qtd_kz_sender ?? '' ?>" placeholder="VALORE DE COMPRA DE SENDER ID">
                                                <div class="input-group-append">
                                                </div>
                                            </div>
                                        </div>

                                        <div class="col-lg-4 col-12">
                                            <div class="form-group">
                                                <label>Endereço</label>
                                                <input type="text" name="endereco" id="endereco" value="<?= $this->configuracao->dataEmpresa->endereco ?? '' ?>" class="form-control" placeholder="NOME DO SISTEMA ?">
                                                <div class="input-group-append">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-lg-4 col-12">
                                            <div class="form-group">
                                                <label>Beneficiário</label>
                                                <input type="text" name="beneficiario" id="beneficiario" value="<?= $this->configuracao->dataEmpresa->beneficiario ?? '' ?>" class="form-control" placeholder="Beneficiário BANCO">
                                                <div class="input-group-append">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-4 col-12">
                                            <div class="form-group">
                                                <label>IBAN</label>
                                                <input type="text" name="iban" id="iban" value="<?= $this->configuracao->dataEmpresa->iban ?? '' ?>" class="form-control" placeholder="IBAN BANCO">
                                                <div class="input-group-append">
                                                </div>
                                            </div>
                                        </div>

                                        <div class="col-lg-4 col-12">
                                            <div class=" form-group">
                                                <label>SLOGAN DO SISTEMA</label>
                                                <input type="text" name="dica_sistema" id="dica_sistema" value="<?= $this->configuracao->dataEmpresa->dica_sistema ?? '' ?>" class="form-control" placeholder="NOME DO SISTEMA ?">
                                                <div class="input-group-append">

                                                </div>
                                            </div>
                                        </div>

                                    </div>

                                    <div class="row">
                                        <div class="col-lg-4 col-12">
                                            <div class="col-lg-12 form-group">
                                                <label>Hora da abertura </label>
                                                <input type="time" name="hora_atendimento_inicio" id="hora_atendimento_inicio" class="form-control" value="<?= str_replace('h', '', $this->configuracao->dataEmpresa->hora_atendimento_inicio ?? '') ?>" placeholder="NOME DO SISTEMA ?">
                                                <div class="input-group-append">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-4 col-12">
                                            <div class="col-lg-12 form-group">
                                                <label>Hora de termino</label>
                                                <input type="time" name="hora_atendimento_termino" id="hora_atendimento_termino" class="form-control" value="<?= str_replace('h', '', $this->configuracao->dataEmpresa->hora_atendimento_termino ?? '') ?>" placeholder="NOME DO SISTEMA ?">
                                                <div class="input-group-append">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-4 col-12">
                                            <div class="col-lg-12 form-group">
                                                <label>NIF</label>
                                                <input type="text" name="nif" id="nif" value="<?= $this->configuracao->dataEmpresa->nif ?? '' ?>" class="form-control" placeholder="NIF DO SISTEMA ?">
                                                <div class="input-group-append">
                                                </div>
                                            </div>
                                        </div>

                                    </div>

                                    <div class="row">
                                        <div class="col-lg-12">
                                            <div class=" form-group">
                                                <label>OBJECTO SOCIAL</label>
                                                <textarea type="text" name="objectivo_sistema" id="objectivo_sistema" rows="5" class="form-control" placeholder="OBJECTO SOCIAL ?"><?= $this->configuracao->dataEmpresa->objectivo ?? '' ?></textarea>
                                                <div class="input-group-append">
                                                </div>
                                            </div>
                                        </div>
                                    </div>


                                    <!--<div class="row">
                                        <div class="form-group mb-4">
                                            <div class="custom-control custom-checkbox">
                                                <input type="checkbox" name="termsSolicitacao" class="custom-control-input" id="exampleCheck1" value="1">
                                                <label class="custom-control-label" for="exampleCheck1">Receber sms as solicitações dos clientes <br>
                                                    <a href="#">Seram descontado sem sua conta.</a>.</label>
                                            </div>
                                        </div>
                                    </div>-->

                                    <input type="hidden" name="token" id="token" class="form-control" value="<?= $this->authCsrf ?>">

                                    <div class="modal-footer justify-content-between">
                                        <button type="submit" class="btn btn-primary btn-block" id="register">GRAVAR</button>
                                    </div>

                                </form>
                            </div>
                            <!-- /.form-box -->
                        </div><!-- /.card -->
                    </div>

                    <div class="modal-footer justify-content-between">
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Fechar</button>
                    </div>
                </div>
                <!-- /.modal-content -->
            </div>
            <!-- /.modal-dialog -->
        </div>

    </div>
    <?php include_once("footer_info.phtml"); ?>

    <script>
        if (!!(window.addEventListener)) window.addEventListener('DOMContentLoaded', main);
        else window.attachEvent('onload', main);

        function main() {
            if (localStorage.getItem("theme") == 1) {
                $('body').addClass('dark-mode')
            }
        }
    </script>

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->

    </aside>
    <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->