 <!-- Small boxes (Stat box) -->


 <div class="col-lg-6 col-12">

     <!-- small box -->

     <div class="small-box bg-info">

         <div class="inner">

             <h3 id="activeValue">0</h3>



             <p>MEUS SENDER</p>

         </div>

         <div class="icon">

             <i class="ion ion-bag"></i>

         </div>

         

     </div>

 </div>

 <!-- ./col -->

 <div class="col-lg-6 col-12">

     <!-- small box -->

     <div class="small-box bg-purple">

         <div class="inner">

             <h3 id="pendenteValue">0</h3>

             <p>SENDER PENDENTES </p>

         </div>

         <div class="icon">

             <i class="ion ion-stats-bars"></i>

         </div>
         

     </div>

 </div>
