<table id="example1" class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Sender ID</th>
            <th>user</th>
            <th>Estado</th>
            <th>PAGO</th>
            <th>Data</th>
            <th>Acção</th>
        </tr>
    </thead>
    <tbody>
        <!-- for $this->category -->
        <?php foreach ($this->senderData->data->data ?? [] as  $value) { ?>
            <tr>
                <td><?= $value->name_sender_id ?? '' ?></td>
                <td> <?= $value->name ?? '' ?></td>
                <td> <?= $value->status_action ? '<span class="text-success" > ACTIVADO</span>' : '<span class="text-danger" >PENDENTE</span> ' ?></td>
                <td><?= $value->forma_sender_is_activ ?? '' ?></td>
                <td><?= $value->created_at ?? '' ?></td>
                <td class=" text-center">
                    <div class="btn-group">
                        <button type="button" class="btn-danger btn-sm mr-2 " id="delete<?= $value->id ?>" onclick="deletaobreiro('<?= $value->id ?? '' ?>','<?= $this->authCsrf ?>')"> <i class="fas fa-trash"></i> </button>
                        <?php
                        if (!$value->is_process && $value->forma_sender_is_activ=='Pago') { ?>
                        <button type="button" class="btn-info btn-sm" id="process_sender<?= $value->id ?>" onclick="processarSender('<?= $value->id ?? '' ?>','<?= $this->authCsrf ?>')"> <i class="nav-icon fas fa-check"></i> </button>
                        <?php } ?>
                    </div>
                </td>
            </tr>
        <?php } ?>
        <!-- end for -->
    </tbody>
    <tfoot>
        <tr>
            <th>Sender ID</th>
            <th>user</th>
            <th>Estado</th>
            <th>PAGO</th>
            <th>Data</th>
            <th>Acção</th>
        </tr>
    </tfoot>
</table>

<div class="float-md-right align-content-center">

    <nav aria-label="Page navigation example" class="">
        <ul class="pagination">
            <?php foreach ($this->senderData->data->links ?? [] as  $value) {

                $itemarray = explode('page=', $value->url ?? '');
                //$item = explode('=', $itemarray[1] ?? '');
            ?>
                <li class="page-item <?= $value->active ? 'active' : '' ?>">
                    <a class="page-link" href="#" onclick="getSender('<?= $itemarray[1] ?? '' ?>')"><?= $value->label ?></a>
                </li>
            <?php } ?>


        </ul>
    </nav>
</div>



<input type="hidden" id="pendente" value="<?= $this->senderData->totalPendente ?? '' ?>">
<input type="hidden" id="activado" value="<?= $this->senderData->totalActive ?? '' ?>">

<input type="hidden" id="total_sender" value="<?= ($this->configuracao->dataEmpresa->tota_sender ?? 0) + 1 ?? '' ?>">
<input type="hidden" id="total_sender_gratis" value="<?= $this->configuracao->qtd_sender_grats_zumu  ?? 0 ?>">
