<table id="example1" class="table table-bordered table-hover">
    <thead>

        <tr>
            <th>USER</th>
            <th>TELEFONE</th>
            <th>EMAIL</th>
            <th>AKZ </th>
            <th>COMPROVATIVO</th>
            <th>ESTADO</th>
            <th>DATA</th>
            <th>ACÇÃO</th>
        </tr>

    </thead>
    <tbody id="corpo_institucional">
        <!-- for $this->category -->
        <?php foreach ($this->clienteData->data->data ?? [] as  $value) { ?>
            <tr>
                <td><?= $value->name ?? '' ?></td>
                <td><?= $value->telefone ?? '' ?></td>
                <td><?= $value->email ?? '' ?></td>
                <td><?= $value->aumount_cart ?? 0 ?></td>
                <td><a href=" <?= API_URL_LOGO . "storage/" . $value->comprovativo ?? '' ?>" target="__black">COMPROVATIVO</a></td>
                <td><?= $value->status_action ? '<span class="text-danger">PENDENTE</span>' : '<span class="text-success">PROCESSADO</span>'  ?></td>

                <td>
                    <?= $value->created_at ?? 0 ?>
                </td>

                <td>
                    <button type="button" <?= $value->status_action ? '' : 'disabled'  ?> class="btn btn-success btn-flat " id="btnactive<?= $value->id ?>" onclick="activarpacote('<?= $value->id ?>')"> <?= $value->status_action ? 'Activar' : 'FEITO'  ?> </button>
                </td>
            </tr>


            <div class="modal fade" id="modal-default<?= $value->id ?>">

                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content ">
                        <div class="modal-header">
                            <h4 class="modal-title">ACTIVAR CARREGAMENTO DE: <?= $value->aumount_cart ?? 0 ?> KZ</h4>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="row">
                                <!-- left column -->
                                <div class="col-md-12 animate__animated animate__slideInLeft">
                                    <!-- jquery validation -->
                                    <div class="card card-primary">

                                        <form method="post" name="from_carregamento" enctype="multipart/form-data">
                                            <div class="card-body">
                                                <div class="row">
                                                    <div class="col-md-12">
                                                        <div class="form-group">
                                                            <label for="exampleInputPassword1">
                                                                A sua senha
                                                            </label>
                                                            <input type="password" name="password" id="password<?= $value->id ?>" class="form-control" placeholder="Password">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <input type="hidden" name="token" id="token" class="form-control" value="<?= $this->authCsrf ?>">
                                            <div class="modal-footer justify-content-between">
                                                <button type="submit" class="btn btn-primary btn-block" id="btnactivemodel<?= $value->id ?>" onclick="activarpacoteprocess('<?= $value->id ?>')">Activar</button>
                                            </div>
                                        </form>

                                    </div>

                                </div>
                            </div>
                        </div>
                        <div class="modal-footer justify-content-between">

                            <button type="button" class="btn btn-danger" data-dismiss="modal">CANCELAR</button>

                        </div>
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>

        <?php } ?>
        <!-- end for -->
    </tbody>
    <tfoot>
        <tr>
            <th>USER</th>
            <th>TELEFONE</th>
            <th>EMAIL</th>
            <th>AKZ </th>
            <th>COMPROVATIVO</th>
            <th>ESTADO</th>
            <th>DATA</th>
            <th>ACÇÃO</th>
        </tr>
    </tfoot>
</table>
<div class="float-md-right align-content-center">
    <nav aria-label="Page navigation example" class="">
        <ul class="pagination">
            <?php foreach ($this->clienteData->data->links ?? [] as  $value) {

                $itemarray = explode('page=', $value->url ?? '');
                //$item = explode('=', $itemarray[1] ?? '');
            ?>
                <li class="page-item <?= $value->active ? 'active' : '' ?>">
                    <a class="page-link" href="#" onclick="getCarregamento('<?= $itemarray[1] ?? '' ?>')"><?= $value->label ?></a>
                </li>
            <?php } ?>


        </ul>
    </nav>
</div>


<input type="hidden" id="carrega_pendetes" value="<?= $this->clienteData->pendetes ?? 0 ?>">
<input type="hidden" id="carrega_activados" value="<?= $this->clienteData->activados ?? '0' ?>">
<input type="hidden" id="saldo_account_kz" value="<?= $this->clienteData->saldo_account  ?? 0 ?>">
