     <!-- Preloader -->
     <!--  <div class="preloader flex-column justify-content-center align-items-center">
         <img class="animation__shake" src="<?= API_URL_LOGO . "" . $_SESSION['LOGO_SISTEMA'] ?? '' ?>" alt="zumu_sms igrejas" height="180" width="180">
     </div> -->

     <div class="preloader flex-column justify-content-center align-items-center">
         <div>
             <h2 class="display-4">Carregando... <i class="fa fa-sync fa-spin"></i></h2>

         </div>
     </div>


     <!-- Navbar -->
     <nav class="main-header navbar navbar-expand navbar-white navbar-light">
         <!-- Left navbar links -->
         <ul class="navbar-nav">
             <li class="nav-item">
                 <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
             </li>

             <li class="nav-item d-none d-sm-inline-block">
                 <a href="index3.html" class="nav-link">Home</a>
             </li>
             <li class="nav-item d-none d-sm-inline-block">
                 <a href="#" class="nav-link"><?= $_SESSION['NOME_SISTEMA'] ?? '' ?></a>
             </li>
         </ul>

         <!-- Right navbar links -->
         <ul class="navbar-nav ml-auto">
             <!-- Navbar Search -->

             <li class="nav-item">
                 <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                     <i class="fas fa-expand-arrows-alt"></i>
                 </a>
             </li>
             <li class="nav-item">
                 <a class="nav-link" data-widget="control-sidebar" data-controlsidebar-slide="true" href="#" role="button">
                     <i class="fas fa-th-large"></i>
                 </a>
             </li>
             <li class="nav-item">
                 <a class="nav-link" href="/logout" role="button">
                     <i class="fas fa-power-off text-danger"></i>
                 </a>
             </li>
         </ul>
     </nav>
     <!-- /.navbar -->
