<div class="wrapper">

    <!-- Navbar -->
    <!-- inicio menu top -->
    <?php include_once("menu_center.phtml"); ?>
    <!-- /.navbar -->
    <?php include_once("menu_lateral.phtml"); ?>
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0">Cartões Membros</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">

                            <li class="breadcrumb-item active">Membros</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <!-- Small boxes (Stat box) -->
                <?php include_once("cardsMembro.phtml"); ?>
                <div class="row">
                    <div class="col-lg-6 col-6">
                        <div class="input-group form-group">
                            <div class="col-md-12 form-group">
                                <div class="form-group  ">
                                    <select class="form-control p-2 tipo_institucional" style="width: 100%;" name="tipo_institucional" id="tipo_institucional" onchange="tbMembroTabela(this)">
                                        <option selected="selected" value="">VISUALIZAR OS MEMBROS DE UMA IGREJA</option>
                                        <?php foreach ($this->igrejas as $value) { ?>
                                            <option value="/get_tabela_membro_igrejas_card?id_igreja=<?= $value['id'] ?>"><?= $value['nome_igrejas'] ?></option>

                                        <?php } ?>
                                    </select>
                                    <input type="hidden" name="token" id="token" class="form-control" value="<?= $this->authCsrf ?>">
                                </div>
                            </div>
                        </div>
                    </div>
                    <section class="col-lg-12 connectedSortable">

                        <table id="example1" class="table table-bordered table-striped">
                            <thead>

                                <tr>
                                    <th>Cartões De Membros</th>

                                </tr>

                            </thead>
                            <tbody id="corpo_institucional">
                                <!-- for $this->category -->
                                <div class="col-md-12">
                                    <div class="row">
                                        <th class="row">
                                            <?php foreach ($this->membros ?? [] as $value) { ?>
                                                <div class="col-md-4">
                                                    <div class="credit-card-box" style="top:0px;position: relative;">
                                                        <div class="flip">
                                                            <div class="front">
                                                                <div class="chip">
                                                                    <img src="assets/img/usuarios/igrejas/<?= $value['foto_membro'] ?? '' ?>" width="80" alt="zumu_sms cartões de membros">
                                                                </div>
                                                                <div class="logo">
                                                                    <img src="assets/img/logotipo/semfundo/logo.png" width="70" />
                                                                </div>
                                                                <div class="number" style="font-size: 1.2rem;"> Igreja: <span class="text-dark"><?= $value["nome_igrejas"] ?? 'Inativo' ?></span> | Nº: <?= $value["id"] ?? 'Inativo' ?>
                                                            <br>
                                                            <p>Data Batismo: <?php $dados=explode(' ',$value["create_at"]??''); echo $dados[0]?></p>
                                                            </div>

                                                                <div class="card-holder">
                                                                    <label>Titular Do Cartão</label>
                                                                    <div><?= $value["nome_membro"] ?? 'Inativo' ?> </div>
                                                                </div>
                                                                <div class="card-expiration-date">
                                                                    <label>Idades</label>
                                                                    <div><?php

                                                                            $data = new \DateTime($value['date_nascimento_tempo'] ?? '');
                                                                            $inicio_date = date("d-m-Y H:i:s");
                                                                            $tempo_anterior = new \DateTime($inicio_date); // data do ultimos clique
                                                                            $intervalo = $data->diff($tempo_anterior);
                                                                            echo $intervalo->y ?></div>
                                                                </div>
                                                            </div>
                                                            <!-- Parte de tras do cartão -->
                                                            <div class="back">
                                                                <div class="strip"></div>
                                                                <div class="logo">
                                                                    <img src="assets/img/logotipo/semfundo/logo.png" width="50" />
                                                                </div>
                                                                <div class="ccv">
                                                                    <div><?= ($value['estado_de_vida']) ? 'EM VIDA' : 'FALECIDO' ?></div>
                                                                </div>
                                                            </div>
                                                            <!-- Fim da parte de tras -->
                                                        </div>
                                                    </div>
                                                </div>
                                            <?php } ?>
                                        </th>
                                    </div>
                                </div>
                                <!-- end for -->
                            </tbody>
                            <tfoot>
                                <tr>
                                <th>Cartões De Membros</th>
                                </tr>
                            </tfoot>

                        </table>
                        <!-- <div class="row no-print">
                            <div class="col-12">
                                <a href="/fragmento_cartaoes_imprime" rel="noopener" target="_blank" class="btn btn-default"><i class="fas fa-print"></i> Print</a>
                            </div>
                        </div> -->
                    </section>

                </div>
            </div>
        </section>


    </div>
    <footer class="main-footer">
        © zumu_sms.
        <a href="https://zumu_sms.com">zumu_sms</a>.- Desenvolvido pela <a href="https://qlerius.com" class="text-dark">Qlerius</a> </strong>
        <div class="float-right d-none d-sm-inline-block">
            <b>Version</b> 3.2.0
        </div>
    </footer>

    <!-- carde de pagamento -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
    <link rel='stylesheet' href='https://fonts.googleapis.com/css2?family=Inconsolata&amp;family=Open+Sans&amp;display=swap'>
    <link rel="stylesheet" href="./style.css">
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js'></script>
    <script src="./script.js"></script>
    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->

    </aside>
    <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->
<!-- <script>
  window.addEventListener("load", window.print());
</script> -->
