<?php include_once("menu_center.phtml"); ?>
<!-- /.navbar -->
<?php include_once("menu_lateral.phtml"); ?>

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>CONTACTOS</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">ENVIAR SMS</a></li>
                        <li class="breadcrumb-item active">CARTEIRA</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <div class="align-content-lg-between  animate__animated animate__bounceIn">
        <div class="card-footer ">
            <a class="btn btn-app bg-success " data-toggle="modal" data-target="#modal-default">
                <i class="fas fa-plus"></i> NOVO
            </a>
            <a class="btn btn-app bg-success " data-toggle="modal" data-target="#modal-import">
                <i class="fas fa-plus"></i> IMPORTAR
            </a>
            <a class="btn btn-app bg-success " href=" <?= API_URL ?>exportarContactosExcel?token=<?= $_SESSION['tokenjwt'] ?? '' ?>">
                <i class="fas fa-plus"></i> EXPORTAR
            </a>
        </div>
    </div>


    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h3 class="card-title">CONTACTOS</h3>

                        <div class="card-tools">
                            <div class="input-group input-group-sm">
                                <input type="text" class="form-control" name="pesquisar" id="pesquisar" value="<?= $_SESSION['pesquisar'] ?? '' ?>" onchange="getContacto()" placeholder="contacto ...">
                                <div class="input-group-append">
                                    <div class="btn btn-primary"  type="button" id="buscar" onclick="getContacto()">
                                        <i class="fas fa-search"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-tools -->
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body p-0">

                        <div class="table-responsive mailbox-messages">
                            <div class="card-body">
                                <div id='contactos'>
                                    <div class="d-flex justify-content-center">
                                        <div class="spinner-border text-primary" style="width: 50px; height: 50px;" role="status">
                                            <span class="visually-hidden"></span>
                                        </div>
                                    </div>
                                </div>
                                <!--  {{ $dados['data']->links('vendor.pagination.bootstrap-5') }}-->
                            </div>
                        </div>
                        <!-- /.mail-box-messages -->
                    </div>
                    <!-- /.card-body -->

                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>

        <div class="modal fade" id="modal-default">

            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content ">
                    <div class="modal-header">
                        <h4 class="modal-title">NOVO CONTACTO</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body animate__animated animate__bounceIn">
                        <div class="row">
                            <!-- left column -->
                            <div class="col-md-12 animate__animated animate__slideInLeft">
                                <!-- jquery validation -->
                                <div class="card card-primary">

                                    <form method="post" accept="image/*" name="from_membro" class="mf_form_validate_contacto ajax_submit_contacto" action="/createContacto" enctype="multipart/form-data">
                                        <div class="card-body">
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <div class="form-group">
                                                        <label>NOME CONTACTO</label>
                                                        <input type="text" name="nome_contacto" id="nome_contacto" class="form-control" placeholder="NOVO CONTACTO">
                                                        <div class="input-group mb-2 form-group" id="erronome">
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-md-12">
                                                    <div class="form-group">
                                                        <label>TELEFONE</label>
                                                        <input type="number" name="telefone" id="telefone" class="form-control" placeholder="TELEFONE">
                                                        <div class="input-group mb-2 form-group" id="errotelefone">
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-md-12">
                                                    <div class="form-group">
                                                        <label>EMAIL DO SEU CLIENTE</label>
                                                        <input type="email" name="email_contacto" id="email_contacto" class="form-control" placeholder="EMAIL DO SEU CLIENTE">
                                                        <div class="input-group mb-2 form-group" id="erroemail_contacto">
                                                        </div>
                                                    </div>
                                                </div>

                                            </div>
                                        </div>
                                        <input type="hidden" name="token" id="token" class="form-control" value="<?= $this->authCsrf ?>">
                                        <div class="modal-footer justify-content-between">
                                            <button type="submit" class="btn btn-primary btn-block" id="register">EDITAR</button>
                                        </div>
                                    </form>
                                </div>
                                <!-- /.card -->
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer justify-content-between">

                        <button type="button" class="btn btn-danger" data-dismiss="modal">CANCELAR</button>

                    </div>
                </div>
                <!-- /.modal-content -->
            </div>
            <!-- /.modal-dialog -->
        </div>

        <div class="modal fade" id="modal-import">

            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content ">
                    <div class="modal-header">
                        <h4 class="modal-title">IMPORTAR CONTACTO</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body animate__animated animate__bounceIn">
                        <div class="row">
                            <!-- left column -->
                            <div class="col-md-12 animate__animated animate__slideInLeft">
                                <!-- jquery validation -->
                                <div class="card card-primary">

                                    <form method="post" accept="image/*" name="from_membro" class="mf_form_validate_import ajax_submit_import" action="/importarContacto" enctype="multipart/form-data">
                                        <div class="card-body">
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <div class="form-group">
                                                        <label>ARQUIVO .( .xslx ) <a href=" <?= API_URL ?>contacts_exemplar/<?= $_SESSION['NOME_EMAIL'] ?? '' ?>" target="_blank">Exemplar</a></label>
                                                        <input type="file" name="file" id="file" class="form-control" placeholder="file">
                                                        <div class="input-group mb-2 form-group" id="errofile">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <input type="hidden" name="token" id="token" class="form-control" value="<?= $this->authCsrf ?>">
                                        <div class="modal-footer justify-content-between">
                                            <button type="submit" class="btn btn-primary btn-block" id="register_Import">IMPORTAR</button>
                                        </div>
                                    </form>
                                </div>
                                <!-- /.card -->
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer justify-content-between">

                        <button type="button" class="btn btn-danger" data-dismiss="modal">CANCELAR</button>

                    </div>
                </div>
                <!-- /.modal-content -->
            </div>
            <!-- /.modal-dialog -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
<?php include_once("footer_info.phtml"); ?>

<style>
    .componente {
        float: right;
        /* faz o componente flutuar à direita */
        clear: both;
        /* garante que o componente não fique ao lado de outros elementos flutuantes */
        margin-top: 10px;
        /* define a margem superior para que o componente fique abaixo dos elementos anteriores */
    }
</style>

<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
</aside>
<!-- /.control-sidebar -->




<script>
    if (!!(window.addEventListener)) window.addEventListener('DOMContentLoaded', main);
    else window.attachEvent('onload', main);

    function main() {
        if (localStorage.getItem("theme") == 1) {
            $('body').addClass('dark-mode')
        }
        
        $(function() {
            //Enable check and uncheck all functionality
            $('.checkbox-toggle').click(function() {
                var clicks = $(this).data('clicks')
                if (clicks) {
                    //Uncheck all checkboxes
                    $('.mailbox-messages input[type=\'checkbox\']').prop('checked', false)
                    $('.checkbox-toggle .far.fa-check-square').removeClass('fa-check-square').addClass('fa-square')
                } else {
                    //Check all checkboxes
                    $('.mailbox-messages input[type=\'checkbox\']').prop('checked', true)
                    $('.checkbox-toggle .far.fa-square').removeClass('fa-square').addClass('fa-check-square')
                }
                $(this).data('clicks', !clicks)
            })

            //Handle starring for font awesome
            $('.mailbox-star').click(function(e) {
                e.preventDefault()
                //detect type
                var $this = $(this).find('a > i')
                var fa = $this.hasClass('fa')

                //Switch states
                if (fa) {
                    $this.toggleClass('fa-star')
                    $this.toggleClass('fa-star-o')
                }
            })
        })
        getContacto();

    }
</script>

    <!-- Page specific script -->
    <script>

    </script>
