<?php include_once("menu_center.phtml"); ?>
<!-- /.navbar -->
<?php include_once("menu_lateral.phtml"); ?>

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">CLIENTES</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="">PEDIDOS</a></li>
                        <li class="breadcrumb-item active">CARREGAR CONTA</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->

            <div class="row animate__animated animate__heartBeat">
                <?php include_once("cardsMembro.phtml"); ?>
            </div>
            <!-- /.card-body -->

            <div class="align-content-lg-between animate__animated animate__bounceIn">
                <div class="card-footer ">
                    <a class="btn btn-app bg-success componente" data-toggle="modal" data-target="#modal-default">
                        <i class="fas fa-plus"></i> CRIAR CLIENTE
                    </a>
                </div>
            </div>

        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">

            <div class="row">
                <div class="col-12 ">
                    <div class="card  card-primary card-outline">
                        <div class="card-header">

                            <h3 class="card-title">

                                <i class="far fa-chart-bar"></i>
                                CLIENTES <?= $_SESSION['NOME_SISTEMA'] ?>
                            </h3>
                            <button type="button" class="btn btn-tool" data-card-widget="collapse">

                                <i class="fas fa-minus"></i>

                            </button>

                            <div class="card-tools">
                                <div class="col-12 col-sm-12 col-md-12">
                                    <div class="input-group form-group">

                                        <input type="text" name="pesquisar" id="pesquisar" onkeyup="getMember()" class="form-control" placeholder="cliente ...">
                                        <div class="input-group-append">
                                            <div class="input-group-text">
                                                <a class=" cursor-pointer" type="button" id="buscar" onclick="getMember()">
                                                    <span class="fas fa-search"></span>
                                                </a>

                                            </div>
                                        </div>

                                    </div>
                                </div>

                            </div>

                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <div id='member'>
                                <div class="d-flex justify-content-center">
                                    <div class="spinner-border text-primary" style="width: 50px; height: 50px;" role="status">
                                        <span class="visually-hidden"></span>
                                    </div>
                                </div>
                            </div>
                            <!--  {{ $dados['data']->links('vendor.pagination.bootstrap-5') }}-->
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->


                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>

            <div class="modal fade" id="modal-default">
                <div class="modal-dialog ">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title">CRIAR NOVO CLIENTE </h4>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="card">
                                <div class="card-body register-card-body">

                                    <div id="messagem"></div>

                                    <form method="post" accept="image/*" name="from_membro" class="mf_form_validate_membro ajax_submit_membro" action="/cretemember" enctype="multipart/form-data">

                                        <div class="row">
                                            <div class="col-lg-12 col-12">
                                                <div class="col-lg-12 form-group">
                                                    <label>NOME DO CLIENTE</label>
                                                    <input type="text" name="nome_membro" id="nome_membro" class="form-control" placeholder="NOME DO MEMBRO ?">
                                                    <div class="input-group-append">
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="col-lg-12 col-12">


                                                <div class="col-lg-12 form-group">
                                                    <label>TELEFONE DO CLIENTE</label>
                                                    <input type="number" name="telefone" id="telefone" class="form-control" placeholder="Número DO MEMBRO">
                                                    <div class="input-group mb-2 form-group" id="errotelefone">
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-lg-12 col-12">
                                                <div class="col-lg-12 form-group">
                                                    <label>EMAIL DO MEMBRO</label>
                                                    <input type="email" name="email_membro" id="email_membro" class="form-control" placeholder="EMAIL DO MEMBRO ">
                                                    <div class="input-group mb-2 form-group" id="erroemail_membro">
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="col-lg-12 col-12">
                                                    <div class="form-group">
                                                        <label>SENHA DE ACESSO</label>
                                                        <input type="text" name="password" id="password" class="form-control" placeholder="SENHA DE ACESSO">
                                                        <div class="input-group mb-2 form-group" id="erropassword">
                                                        </div>
                                                    </div>
                                            </div>

                                            <!-- /.col -->
                                        </div>

                                        <input type="hidden" name="token" id="token" class="form-control" value="<?= $this->authCsrf ?>">
                                        <div class="row">
                                            <!-- /.col -->
                                            <div class="col-4">
                                                <button type="submit" class="btn btn-primary btn-block" id="register">CRIAR</button>
                                            </div>
                                            <!-- /.col -->
                                        </div>
                                    </form>
                                </div>
                                <!-- /.form-box -->
                            </div><!-- /.card -->
                        </div>
                        <div class="modal-footer justify-content-between">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

                        </div>
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>
        </div>
        <input type="hidden" name="token" id="token" class="form-control" value="<?= $this->authCsrf ?>">
        <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>

<?php include_once("footer_info.phtml"); ?>

<script>
    if (!!(window.addEventListener)) window.addEventListener('DOMContentLoaded', main);
    else window.attachEvent('onload', main);

    function main() {
        if (localStorage.getItem("theme") == 1) {
            $('body').addClass('dark-mode')
        }
        getMember();

    }
</script>