<?php include_once("menu_center.phtml"); ?>
<!-- /.navbar -->
<?php include_once("menu_lateral.phtml"); ?>

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">PACOTES SMS</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="">CLIENTES</a></li>
                        <li class="breadcrumb-item active">CARREGAR CONTA</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->

            <div class="row animate__animated animate__heartBeat">
                <?php include_once("cardsPacotes.phtml"); ?>
            </div>
            <!-- /.card-body -->

            <div class="align-content-lg-between animate__animated animate__bounceIn">
                <div class="card-footer ">
                    <a class="btn btn-app bg-success componente" data-toggle="modal" data-target="#modal-default">
                        <i class="fas fa-plus"></i> CRIAR NOVO PACOTE
                    </a>
                </div>
            </div>

        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">

            <div class="row">
                <div class="col-12 ">
                    <div class="card  card-primary card-outline">
                        <div class="card-header">

                            <h3 class="card-title">

                                <i class="far fa-chart-bar"></i>
                                PACOTES
                            </h3>
                            <button type="button" class="btn btn-tool" data-card-widget="collapse">

                                <i class="fas fa-minus"></i>

                            </button>

                            <div class="card-tools">
                                <!--   <div class="col-12 col-sm-12 col-md-12">
                                    <div class="input-group form-group">

                                        <input type="text" name="pesquisar" id="pesquisar" onkeyup="getBuscarSender()" class="form-control" placeholder="Nome sender">
                                        <div class="input-group-append">
                                            <div class="input-group-text">
                                                <a class=" cursor-pointer" type="button" id="buscar" onclick="getBuscarSender()">
                                                    <span class="fas fa-search"></span>
                                                </a>

                                            </div>
                                        </div>

                                    </div>
                                </div> -->

                            </div>

                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <div id='pacote'>
                                <div class="d-flex justify-content-center">
                                    <div class="spinner-border text-primary" style="width: 50px; height: 50px;" role="status">
                                        <span class="visually-hidden"></span>
                                    </div>
                                </div>
                            </div>
                            <!--  {{ $dados['data']->links('vendor.pagination.bootstrap-5') }}-->
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->


                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>


            <div class="modal fade" id="modal-default">

                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content ">
                        <div class="modal-header">
                            <h4 class="modal-title">CRIAR NOVO PACOTE SMS </h4>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="row">
                                <!-- left column -->
                                <div class="col-md-12 animate__animated animate__slideInLeft">
                                    <!-- jquery validation -->
                                    <div class="card card-primary">

                                        <form method="post" accept="image/*" name="from_membro" class="mf_form_validate_membro ajax_submit_membro" action="/cretepacotes" enctype="multipart/form-data">
                                            <div class="card-body">
                                                <div class="row">
                                                    <div class="col-md-12">
                                                        <div class="form-group">
                                                            <label for="exampleInputPassword1">
                                                                NOME SENDER ID
                                                            </label>
                                                            <input type="text" name="nomepacote" id="nomepacote" class="form-control" placeholder="NOME DO PACOTE DE SMS">

                                                        </div>
                                                    </div>
                                                    <div class="col-md-12">
                                                        <div class="form-group">
                                                            <label>VALORES A REVENDER A SMS, SISTEMA <label class="text-success">1SMS/</label><label id="pacoteSmsMostrar" class="text-success">0</label> Kz</label>
                                                            <input type="number" name="qtduser" id="qtduser" class="form-control" placeholder="VALORES A REVENDER A SMS EM KZ" onkeyup="valorenveder(this.value)">
                                                            <div class="input-group mb-2 form-group" id="erroqtduser_pacote">
                                                            </div>
                                                        </div>
                                                    </div>

                                                    <div class="col-md-12">
                                                        <div class="form-group">
                                                            <label>QUANTIDADE DE SMS <label id="pacoteqtd_sms_userr" class="text-success"> 0.00 </label> Kz</label>
                                                            <input type="number" name="qtd_sms_user" id="qtd_sms_user" class="form-control" placeholder=" QUANTIDADE DE SMS" disabled>
                                                            <div class="input-group  form-group" id="erroqtd_sms_user_pacote">
                                                            </div>

                                                        </div>
                                                    </div>
                                                    <div class="col-md-12">
                                                        <div class="form-group">
                                                            <label>IDEAL PARA</label>
                                                            <input type="text" name="text_ideal" id="text_ideal" class="form-control" placeholder="IDEL PARA ">
                                                            <div class="input-group form-group" id="errotext_ideal_pacote">
                                                            </div>

                                                        </div>
                                                    </div>



                                                </div>
                                            </div>

                                            <div class="modal-footer justify-content-between">
                                                <button type="submit" class="btn btn-primary btn-block" id="register">CRIAR</button>
                                            </div>
                                        </form>

                                    </div>
                                    <!-- /.card -->
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer justify-content-between">

                            <button type="button" class="btn btn-danger" data-dismiss="modal">CANCELAR</button>

                        </div>
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>

        </div>
        <input type="hidden" name="token" id="token" class="form-control" value="<?= $this->authCsrf ?>">
        <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>

<?php include_once("footer_info.phtml"); ?>

<style>
    .componente {
        float: right;
        /* faz o componente flutuar à direita */
        clear: both;
        /* garante que o componente não fique ao lado de outros elementos flutuantes */
        margin-top: 10px;
        /* define a margem superior para que o componente fique abaixo dos elementos anteriores */
    }
</style>


<script>
    if (!!(window.addEventListener)) window.addEventListener('DOMContentLoaded', main);
    else window.attachEvent('onload', main);

    function main() {
        getPacotes();
        if (localStorage.getItem("theme") == 1) {
            $('body').addClass('dark-mode')
        }
    }
</script>